#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# educational_part2.py - الدفعة الثانية: 300+ مؤسسة تعليمية

educational_institutions_part2 = [
    # ===== 1. المكتبات الرقمية (100) =====
    "Library of Congress - مكتبة الكونغرس",
    "British Library - المكتبة البريطانية",
    "Bibliothèque Nationale de France - المكتبة الوطنية الفرنسية",
    "Deutsche Nationalbibliothek - المكتبة الوطنية الألمانية",
    "Biblioteca Nacional de España - المكتبة الوطنية الإسبانية",
    "Russian State Library - المكتبة الروسية",
    "National Library of China - المكتبة الصينية",
    "National Diet Library - المكتبة اليابانية",
    "National Library of India - المكتبة الهندية",
    "Biblioteca Apostolica Vaticana - مكتبة الفاتيكان",
    "Internet Archive - الأرشيف الرقمي",
    "HathiTrust - هاثي تراست",
    "Project Gutenberg - مشروع غوتنبرغ",
    "Google Books - كتب جوجل",
    "Open Library - المكتبة المفتوحة",
    "Europeana - يوروبيانا",
    "World Digital Library - المكتبة الرقمية العالمية",
    "Digital Public Library of America - المكتبة العامة الرقمية",
    "Biodiversity Heritage Library - مكتبة التنوع الحيوي",
    "Medical Heritage Library - المكتبة الطبية التراثية",
    "Smithsonian Libraries - مكتبات سميثسونيان",
    "Harvard Library - مكتبة هارفارد",
    "Yale Library - مكتبة ييل",
    "Oxford Library - مكتبة أكسفورد",
    "Cambridge Library - مكتبة كامبريدج",
    "MIT Library - مكتبة MIT",
    "Stanford Library - مكتبة ستانفورد",
    "Princeton Library - مكتبة برينستون",
    "Columbia Library - مكتبة كولومبيا",
    "University of Chicago Library - مكتبة شيكاغو",
    "Cornell Library - مكتبة كورنيل",
    "Duke Library - مكتبة ديوك",
    "Northwestern Library - مكتبة نورث وسترن",
    "Berkeley Library - مكتبة بيركلي",
    "UCLA Library - مكتبة لوس أنجلوس",
    "NYU Library - مكتبة نيويورك",
    "University of Michigan Library - مكتبة ميشيغان",
    "University of Toronto Library - مكتبة تورنتو",
    "McGill Library - مكتبة ماكغيل",
    "University of Tokyo Library - مكتبة طوكيو",
    "National Library of Singapore - مكتبة سنغافورة",
    "Bibliotheca Alexandrina - مكتبة الإسكندرية",
    "Qatar National Library - مكتبة قطر الوطنية",
    "King Fahd Library - مكتبة الملك فهد",
    "Al-Azhar Library - مكتبة الأزهر",
    "Zaytuna Library - مكتبة الزيتونة",
    "Al-Qarawiyyin Library - مكتبة القرويين",
    "Escorial Library - مكتبة الإسكوريال",
    "Bodleian Library - مكتبة بودليان",
    "Vatican Library - مكتبة الفاتيكان",
    "Bibliotheca Alexandrina Digital - مكتبة الإسكندرية الرقمية",
    "Digital Bodleian - بودليان الرقمية",
    "Cambridge Digital Library - كامبريدج الرقمية",
    "Oxford Digital Library - أكسفورد الرقمية",
    "Harvard Digital Collection - هارفارد الرقمية",
    "Yale Digital Collection - ييل الرقمية",
    "Stanford Digital Repository - ستانفورد الرقمية",
    "MIT Digital Collections - MIT الرقمية",
    "Princeton Digital Library - برينستون الرقمية",
    "Columbia Digital Collections - كولومبيا الرقمية",
    "Cornell Digital Collections - كورنيل الرقمية",
    "Duke Digital Collections - ديوك الرقمية",
    "Northwestern Digital - نورث وسترن الرقمية",
    "Berkeley Digital Collections - بيركلي الرقمية",
    "UCLA Digital Collections - لوس أنجلوس الرقمية",
    "NYU Digital Library - نيويورك الرقمية",
    "Michigan Digital Collections - ميشيغان الرقمية",
    "Toronto Digital Collections - تورنتو الرقمية",
    "McGill Digital Collections - ماكغيل الرقمية",
    "Tokyo Digital Collections - طوكيو الرقمية",
    "Singapore Digital Library - سنغافورة الرقمية",
    "Qatar Digital Library - قطر الرقمية",
    "King Fahd Digital Library - الملك فهد الرقمية",
    "Al-Azhar Digital Library - الأزهر الرقمية",
    "Zaytuna Digital Library - الزيتونة الرقمية",
    "Qarawiyyin Digital Library - القرويين الرقمية",
    "Escorial Digital Library - الإسكوريال الرقمية",
    "Vatican Digital Library - الفاتيكان الرقمية",
    "WorldCat - الفهرس العالمي",
    "OpenCat - الفهرس المفتوح",
    "LibraryThing - لايبراري ثينغ",
    "Goodreads - غود ريدز",
    "Shelfari - شيلفاري",
    "BookLikes - بوك لايكس",
    "Bookish - بوكيش",
    "Readernaut - ريدر نوت",
    "Revish - ريفيش",
    "aNobii - أنوبي",
    "BookRabbit - بوك رابيت",
    "BookArmy - بوك أرمي",
    "BookJetty - بوك جيتي",
    "Libib - ليبب",
    "BookDigits - بوك ديجيتس",
    "Riffle - ريفل",
    "BookLamp - بوك لامب",
    "BookTagger - بوك تاغر",
    "BookSprout - بوك سبراوت",

    # ===== 2. المنصات البحثية (100) =====
    "Google Scholar - جوجل سكولار",
    "ResearchGate - ريسيرش غيت",
    "Academia.edu - أكاديميا",
    "Semantic Scholar - سيمانتيك سكولار",
    "Web of Science - ويب أوف ساينس",
    "Scopus - سكوبس",
    "PubMed - بب ميد",
    "arXiv - أركايف",
    "JSTOR - جستور",
    "ScienceDirect - ساينس دايركت",
    "SpringerLink - سبرينغر لينك",
    "Wiley Online Library - وايلي",
    "Taylor & Francis - تايلور وفرانسيس",
    "SAGE Journals - سيج",
    "Oxford Academic - أكسفورد أكاديميك",
    "Cambridge Core - كامبريدج كور",
    "Nature.com - نيتشر",
    "Science.org - ساينس",
    "PLOS - بلوس",
    "MDPI - إم دي بي آي",
    "IEEE Xplore - آي تريبل إي",
    "ACM Digital Library - إيه سي إم",
    "SSRN - إس إس آر إن",
    "SocArXiv - سوك أركايف",
    "PhilPapers - فيل بيبرز",
    "RePEc - ريبيك",
    "IDEAS - آيديز",
    "NBER - إن بي إي آر",
    "CEPR - سي إي بي آر",
    "OpenAlex - أوبن أليكس",
    "Crossref - كروس ريف",
    "DataCite - داتا سايت",
    "ORCID - أوركيد",
    "figshare - فيغ شير",
    "Zenodo - زينودو",
    "Dryad - درياد",
    "Dataverse - داتافيرس",
    "Mendeley - مندلي",
    "Zotero - زوتيرو",
    "EndNote - إند نوت",
    "RefWorks - ريف وركس",
    "Papers - بيبرز",
    "ReadCube - ريد كيوب",
    "Kopernio - كوبرنيو",
    "Unpaywall - أنباي وول",
    "CORE - كور",
    "BASE - باز",
    "Dimensions - دايمنشنز",
    "Lens.org - لينز",
    "Scilit - سيليت",
    "OpenAIRE - أوبن إير",
    "Europe PMC - يوروب بي إم سي",
    "Cochrane Library - كوكرين",
    "Embase - إمبيس",
    "CINAHL - سيناهل",
    "PsycINFO - سايك إنفو",
    "ERIC - إريك",
    "ProQuest - بروكويست",
    "EBSCO - إبسكو",
    "Gale - غيل",
    "J-Gate - جي غيت",
    "DOAJ - دوج",
    "OpenDOAR - أوبن دوج",
    "SHERPA/RoMEO - شيربا",
    "ScienceOpen - ساينس أوبن",
    "F1000Research - إف 1000",
    "PeerJ - بير جي",
    "eLife - إي لايف",
    "BioMed Central - بيو ميد سنترال",
    "Hindawi - هنداوي",
    "Frontiers - فرونتيرز",
    "Bentham Science - بنثام",
    "Thieme - ثيم",
    "Karger - كارغر",
    "De Gruyter - دي غرويتر",
    "Brill - بريل",
    "Emerald - إميرالد",
    "Inderscience - إندرساينس",
    "IGI Global - آي جي آي",
    "World Scientific - ورلد ساينتيفيك",
    "Now Publishers - ناو",
    "Annual Reviews - أنيوال ريفيوز",
    "Portland Press - بورتلاند",
    "Royal Society - الجمعية الملكية",
    "National Academies - الأكاديميات الوطنية",
    "AAAS - الجمعية الأمريكية",
    "Royal Society of Chemistry - الجمعية الملكية للكيمياء",
    "American Chemical Society - الجمعية الكيميائية الأمريكية",
    "American Physical Society - الجمعية الفيزيائية الأمريكية",
    "Institute of Physics - معهد الفيزياء",
    "American Mathematical Society - الجمعية الرياضية الأمريكية",
    "Society for Industrial Mathematics - جمعية الرياضيات الصناعية",
    "American Statistical Association - الجمعية الإحصائية الأمريكية",
    "American Psychological Association - الجمعية النفسية الأمريكية",
    "American Sociological Association - الجمعية الاجتماعية الأمريكية",
    "American Economic Association - الجمعية الاقتصادية الأمريكية",

    # ===== 3. منصات إضافية متخصصة (100) =====
    "TED - تيد",
    "TED-Ed - تيد إد",
    "TEDx - تيد إكس",
    "Big Think - بيغ ثينك",
    "Crash Course - كراش كورس",
    "Vsauce - في سوس",
    "Veritasium - فيريتاسيوم",
    "MinutePhysics - مينيت فيزكس",
    "MinuteEarth - مينيت إيرث",
    "SciShow - ساي شو",
    "AsapSCIENCE - أساب ساينس",
    "Kurzgesagt - كورزغيساغت",
    "CGP Grey - سي جي بي غراي",
    "Numberphile - نامبر فايل",
    "3Blue1Brown - ثري بلو وان براون",
    "Computerphile - كمبيوتر فايل",
    "Sixty Symbols - سيكستي سيمبولز",
    "Periodic Videos - بيريوديك فيديوز",
    "Smarter Every Day - سمارتر إيفري داي",
    "Physics Girl - فيزكس غيرل",
    "Deep Look - ديب لوك",
    "Nature Documentaries - وثائقيات الطبيعة",
    "BBC Earth - بي بي سي إيرث",
    "National Geographic - ناشيونال جيوغرافيك",
    "Discovery - ديسكفري",
    "Smithsonian Channel - سميثسونيان",
    "History Channel - هيستوري",
    "Science Channel - ساينس تشانل",
    "NASA TV - ناسا تي في",
    "ESA TV - إيسا تي في",
    "SpaceX Live - سبيس إكس لايف",
    "CERN Live - سيرن لايف",
    "MIT OpenCourseWare - إم آي تي المفتوح",
    "OpenStax - أوبن ستاكس",
    "OER Commons - أو إي آر",
    "MERLOT - ميرلوت",
    "OpenLearn - أوبن ليرن",
    "Saylor Academy - سايلور",
    "Alison - أليسون",
    "Canvas Network - كانفاس",
    "Open Yale Courses - ييل المفتوح",
    "Harvard Online - هارفارد أونلاين",
    "Stanford Online - ستانفورد أونلاين",
    "Oxford Online - أكسفورد أونلاين",
    "Cambridge Online - كامبريدج أونلاين",
    "MITx - إم آي تي إكس",
    "HarvardX - هارفارد إكس",
    "StanfordX - ستانفورد إكس",
    "BerkeleyX - بيركلي إكس",
    "CornellX - كورنيل إكس",
    "PrincetonX - برينستون إكس",
    "YaleX - ييل إكس",
    "ColumbiaX - كولومبيا إكس",
    "PennX - بن إكس",
    "MichiganX - ميشيغان إكس",
    "JohnsHopkinsX - جونز هوبكنز إكس",
    "NorthwesternX - نورث وسترن إكس",
    "DukeX - ديوك إكس",
    "RiceX - رايس إكس",
    "BrownX - براون إكس",
    "DartmouthX - دارتموث إكس",
    "VanderbiltX - فاندربيلت إكس",
    "NotreDameX - نوتردام إكس",
    "GeorgetownX - جورجتاون إكس",
    "CarnegieMellonX - كارنيجي ميلون إكس",
    "CaltechX - كالتك إكس",
    "GeorgiaTechX - جورجيا تك إكس",
    "IllinoisX - إلينوي إكس",
    "WashingtonX - واشنطن إكس",
    "TorontoX - تورنتو إكس",
    "McGillX - ماكغيل إكس",
    "TokyoX - طوكيو إكس",
    "KyotoX - كيوتو إكس",
    "OsakaX - أوساكا إكس",
    "SeoulX - سيول إكس",
    "KAISTX - كايست إكس",
    "TsinghuaX - تسينغهوا إكس",
    "PekingX - بكين إكس",
    "FudanX - فودان إكس",
    "ShanghaiX - شنغهاي إكس",
    "SingaporeX - سنغافورة إكس",
    "NanyangX - نانيانغ إكس",
    "HongKongX - هونغ كونغ إكس",
    "MelbourneX - ملبورن إكس",
    "SydneyX - سيدني إكس",
    "QueenslandX - كوينزلاند إكس",
    "IITX - آي آي تي إكس",
    "KAUX - جامعة الملك عبدالعزيز إكس",
    "KSUX - جامعة الملك سعود إكس",
    "KFUPMX - جامعة الملك فهد إكس",
    "CairoX - القاهرة إكس",
    "AinShamsX - عين شمس إكس",
    "AlexandriaX - الإسكندرية إكس",
    "AUCX - الجامعة الأمريكية بالقاهرة إكس",
    "AUBX - الأمريكية ببيروت إكس",
    "BaghdadX - بغداد إكس",
    "DamascusX - دمشق إكس",
    "AleppoX - حلب إكس",
    "JordanX - الأردن إكس",
    "YarmoukX - اليرموك إكس",
    "KuwaitX - الكويت إكس"
]

def display_educational_part2():
    print("=" * 80)
    print(f"📚  المؤسسات التعليمية - الدفعة الثانية ({len(educational_institutions_part2)} مؤسسة)  📚")
    print("=" * 80)
    for i, institution in enumerate(educational_institutions_part2, 1):
        print(f"    {i:3d}. {institution}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(educational_institutions_part2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_educational_part2()
