#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# educational_part1.py - الدفعة الأولى: 300 مؤسسة تعليمية

educational_institutions_part1 = [
    # ===== 1. الجامعات العالمية (100) =====
    "Harvard University - هارفارد",
    "MIT - معهد ماساتشوستس للتكنولوجيا",
    "Stanford University - ستانفورد",
    "Yale University - ييل",
    "Princeton University - برينستون",
    "Columbia University - كولومبيا",
    "University of Chicago - شيكاغو",
    "University of Pennsylvania - بنسلفانيا",
    "Caltech - معهد كاليفورنيا للتكنولوجيا",
    "Duke University - ديوك",
    "Johns Hopkins University - جونز هوبكنز",
    "Northwestern University - نورث وسترن",
    "Cornell University - كورنيل",
    "Brown University - براون",
    "Rice University - رايس",
    "Dartmouth College - دارتموث",
    "Vanderbilt University - فاندربيلت",
    "Notre Dame University - نوتردام",
    "Georgetown University - جورجتاون",
    "Carnegie Mellon University - كارنيجي ميلون",
    "University of Michigan - ميشيغان",
    "UC Berkeley - بيركلي",
    "UCLA - لوس أنجلوس",
    "NYU - نيويورك",
    "University of Washington - واشنطن",
    "University of Oxford - أكسفورد",
    "University of Cambridge - كامبريدج",
    "Imperial College London - إمبريال كوليدج",
    "LSE - لندن للاقتصاد",
    "UCL - كلية لندن الجامعية",
    "King's College London - كينجز كوليدج",
    "University of Edinburgh - إدنبرة",
    "University of Manchester - مانشستر",
    "University of Bristol - بريستول",
    "University of Warwick - وارويك",
    "University of Glasgow - غلاسكو",
    "University of Birmingham - برمنغهام",
    "University of Leeds - ليدز",
    "University of Nottingham - نوتنغهام",
    "University of Southampton - ساوثهامبتون",
    "University of Sheffield - شيفيلد",
    "University of Liverpool - ليفربول",
    "Queen Mary University - كوين ماري",
    "Durham University - دورهام",
    "University of St Andrews - سانت أندروز",
    "ETH Zurich - زيورخ السويسرية",
    "EPFL - لوزان السويسرية",
    "Sorbonne University - السوربون",
    "Technical University of Munich - ميونخ",
    "LMU Munich - ميونخ",
    "Heidelberg University - هايدلبرغ",
    "Humboldt University - هومبولت",
    "University of Amsterdam - أمستردام",
    "Delft University - دلفت",
    "KU Leuven - لوفين",
    "University of Copenhagen - كوبنهاغن",
    "University of Helsinki - هلسنكي",
    "University of Oslo - أوسلو",
    "Stockholm University - ستوكهولم",
    "Karolinska Institute - كارولينسكا",
    "University of Vienna - فيينا",
    "Sapienza University - سابينزا روما",
    "University of Barcelona - برشلونة",
    "University of Madrid - مدريد",
    "University of Lisbon - لشبونة",
    "University of Tokyo - طوكيو",
    "Kyoto University - كيوتو",
    "Osaka University - أوساكا",
    "Tohoku University - توهوكو",
    "Seoul National University - سيول",
    "KAIST - كوريا للتكنولوجيا",
    "Tsinghua University - تسينغهوا",
    "Peking University - بكين",
    "Fudan University - فودان",
    "Shanghai Jiao Tong - شنغهاي",
    "National University of Singapore - سنغافورة",
    "Nanyang Technological University - نانيانغ",
    "University of Hong Kong - هونغ كونغ",
    "HKUST - هونغ كونغ للعلوم",
    "Chinese University of Hong Kong - الصينية",
    "University of Melbourne - ملبورن",
    "University of Sydney - سيدني",
    "ANU - الوطنية الأسترالية",
    "University of Queensland - كوينزلاند",
    "IIT Bombay - الهندية للتكنولوجيا",
    "جامعة الملك عبدالعزيز - السعودية",
    "جامعة الملك سعود - السعودية",
    "جامعة الملك فهد - السعودية",
    "جامعة القاهرة - مصر",
    "جامعة عين شمس - مصر",
    "جامعة الإسكندرية - مصر",
    "الجامعة الأمريكية بالقاهرة - مصر",
    "الجامعة الأمريكية ببيروت - لبنان",
    "الجامعة اللبنانية - لبنان",
    "جامعة بغداد - العراق",
    "جامعة دمشق - سوريا",
    "جامعة حلب - سوريا",
    "الجامعة الأردنية - الأردن",
    "جامعة اليرموك - الأردن",
    "جامعة الكويت - الكويت",

    # ===== 2. منصات التعلم الإلكتروني (100) =====
    "Coursera - كورسيرا",
    "edX - إيديكس",
    "Udemy - يوديمي",
    "Udacity - يوداسيتي",
    "FutureLearn - فيوتشرليرن",
    "Khan Academy - خان أكاديمي",
    "Codecademy - كودكاديمي",
    "Pluralsight - بلورالسايت",
    "LinkedIn Learning - لينكدإن ليرنينغ",
    "Skillshare - سكيلشير",
    "DataCamp - داتاكامب",
    "Treehouse - تريهاوس",
    "General Assembly - جنرال أسيمبلي",
    "Springboard - سبرينغبورد",
    "Lambda School - لامبدا سكول",
    "Ironhack - أيرونهاك",
    "Le Wagon - لو واجون",
    "App Academy - أب أكاديمي",
    "Hack Reactor - هاك رياكتور",
    "Flatiron School - فلاتيرون سكول",
    "Thinkful - ثينكفول",
    "CareerFoundry - كاريير فاوندري",
    "BrainStation - برين ستيشن",
    "Galvanize - جالفانايز",
    "Makers Academy - ميكرز أكاديمي",
    "Code Institute - كود إنستيتيوت",
    "Wild Code School - وايلد كود سكول",
    "42 School - سكول 42",
    "Holberton School - هولبرتون سكول",
    "Microverse - ميكروفيرس",
    "Duolingo - دوولينغو",
    "Babbel - بابل",
    "Rosetta Stone - روزيتا ستون",
    "Busuu - بوسوو",
    "Memrise - ممرايز",
    "Lingoda - لينغودا",
    "Italki - إيتالكي",
    "Preply - بريبلي",
    "Verbling - فيربلينغ",
    "HelloTalk - هيلو توك",
    "Tandem - تاندم",
    "Lingvist - لينغفيست",
    "Drops - دروبس",
    "Mondly - موندلي",
    "Pimsleur - بيمسلور",
    "Assimil - أسيميل",
    "Berlitz - بيرلتز",
    "EF Education - إي إف",
    "British Council - المجلس الثقافي البريطاني",
    "Alliance Française - الأليانس الفرنسية",
    "GitHub Learning - جيت هاب",
    "Stack Overflow - ستاك أوفرفلو",
    "LeetCode - ليت كود",
    "HackerRank - هاكر رانك",
    "Codeforces - كود فورسز",
    "TopCoder - توب كودر",
    "Codewars - كود وورز",
    "Exercism - إكسيرسيزم",
    "Project Euler - بروجكت أويلر",
    "FreeCodeCamp - فري كود كامب",
    "The Odin Project - مشروع أودين",
    "Scrimba - سكريمبا",
    "Frontend Masters - فرونت إند ماسترز",
    "Egghead.io - إيغ هيد",
    "Laracasts - لاراكاستس",
    "Vue School - فيو سكول",
    "React Training - رياكت ترينينغ",
    "Node School - نود سكول",
    "Python.org - بايثون",
    "W3Schools - دبليو ثري سكولز",
    "MDN Web Docs - إم دي إن",
    "GeeksforGeeks - جيكس فور جيكس",
    "TutorialsPoint - توتوريالز بوينت",
    "JavaTpoint - جافا تي بوينت",
    "Harvard Business School Online - هارفارد للأعمال",
    "Wharton Online - وارتون",
    "Stanford GSB - ستانفورد للأعمال",
    "INSEAD Online - إنسياد",
    "London Business School - لندن للأعمال",
    "MIT Sloan - إم آي تي سلون",
    "Kellogg School - كيلوغ",
    "Columbia Business School - كولومبيا للأعمال",
    "Wharton Executive Education - وارتون التنفيذي",
    "IMD Business School - آي إم دي",
    "HEC Paris - إتش إي سي",
    "IE Business School - آي إي",
    "IESE Business School - إيسي",
    "ESADE - إيساد",
    "Bocconi University - بوكوني",
    "Adobe Creative Cloud - أدوبي",
    "Canva - كانفا",
    "Figma - فيغما",
    "Sketch - سكيتش",
    "InVision - إن فيجن",
    "Behance - بيهانس",
    "Dribbble - دريبل",
    "99designs - 99 ديزاينز",
    "Designlab - ديزاين لاب",
    "Interaction Design Foundation - مؤسسة التصميم التفاعلي",

    # ===== 3. الموسوعات العلمية (100) =====
    "Wikipedia - ويكيبيديا",
    "Encyclopaedia Britannica - بريتانيكا",
    "World Book Encyclopedia - ورلد بوك",
    "Encyclopedia.com - موسوعة دوت كوم",
    "Columbia Encyclopedia - موسوعة كولومبيا",
    "Encyclopedia Americana - الموسوعة الأمريكية",
    "Larousse Encyclopedia - موسوعة لاروس",
    "Brockhaus Enzyklopädie - موسوعة بروكهاوس",
    "Great Soviet Encyclopedia - الموسوعة السوفيتية",
    "Canadian Encyclopedia - الموسوعة الكندية",
    "Australian Encyclopedia - الموسوعة الأسترالية",
    "New World Encyclopedia - موسوعة العالم الجديد",
    "Citizendium - سيتيزنديوم",
    "Scholarpedia - سكولاربيديا",
    "Everything2 - إيفريثينغ 2",
    "Infoplease - إنفو بليز",
    "FactMonster - فاكت مونستر",
    "Encyclopedia of Life - موسوعة الحياة",
    "Encyclopedia of Earth - موسوعة الأرض",
    "Encyclopedia of Science - موسوعة العلوم",
    "Encyclopedia of Physics - موسوعة الفيزياء",
    "Encyclopedia of Chemistry - موسوعة الكيمياء",
    "Encyclopedia of Biology - موسوعة الأحياء",
    "Encyclopedia of Mathematics - موسوعة الرياضيات",
    "Encyclopedia of Astronomy - موسوعة الفلك",
    "Encyclopedia of Medicine - موسوعة الطب",
    "Encyclopedia of Engineering - موسوعة الهندسة",
    "Encyclopedia of Computer Science - موسوعة علوم الحاسوب",
    "Encyclopedia of Neuroscience - موسوعة العلوم العصبية",
    "Encyclopedia of Genetics - موسوعة الوراثة",
    "Encyclopedia of Ecology - موسوعة البيئة",
    "Encyclopedia of Geology - موسوعة الجيولوجيا",
    "Encyclopedia of Oceanography - موسوعة المحيطات",
    "Encyclopedia of Meteorology - موسوعة الأرصاد",
    "Encyclopedia of Psychology - موسوعة علم النفس",
    "Encyclopedia of Sociology - موسوعة علم الاجتماع",
    "Encyclopedia of Philosophy - موسوعة الفلسفة",
    "Encyclopedia of Religion - موسوعة الأديان",
    "Encyclopedia of History - موسوعة التاريخ",
    "Encyclopedia of Economics - موسوعة الاقتصاد",
    "MedlinePlus Medical Encyclopedia - موسوعة ميدلاين",
    "Gale Encyclopedia of Medicine - موسوعة غيل الطبية",
    "Merck Manual - دليل ميرك",
    "Harrison's Principles of Medicine - مبادئ هاريسون",
    "Gray's Anatomy - تشريح غراي",
    "Encyclopedia of Surgery - موسوعة الجراحة",
    "Encyclopedia of Pediatrics - موسوعة طب الأطفال",
    "Encyclopedia of Cardiology - موسوعة طب القلب",
    "Encyclopedia of Neurology - موسوعة طب الأعصاب",
    "Encyclopedia of Oncology - موسوعة الأورام",
    "Encyclopedia of Psychiatry - موسوعة الطب النفسي",
    "Encyclopedia of Dermatology - موسوعة الجلدية",
    "Encyclopedia of Radiology - موسوعة الأشعة",
    "Encyclopedia of Pathology - موسوعة الأمراض",
    "Encyclopedia of Immunology - موسوعة المناعة",
    "Encyclopedia of Pharmacology - موسوعة الأدوية",
    "Encyclopedia of Nutrition - موسوعة التغذية",
    "Encyclopedia of Sports Medicine - موسوعة الطب الرياضي",
    "Encyclopedia of Alternative Medicine - موسوعة الطب البديل",
    "Encyclopedia of Nursing - موسوعة التمريض",
    "Encyclopedia of Artificial Intelligence - موسوعة الذكاء الاصطناعي",
    "Encyclopedia of Machine Learning - موسوعة التعلم الآلي",
    "Encyclopedia of Data Science - موسوعة علوم البيانات",
    "Encyclopedia of Software Engineering - موسوعة هندسة البرمجيات",
    "Encyclopedia of Computer Graphics - موسوعة رسومات الحاسوب",
    "Encyclopedia of Robotics - موسوعة الروبوتات",
    "Encyclopedia of Cybersecurity - موسوعة الأمن السيبراني",
    "Encyclopedia of Blockchain - موسوعة البلوكشين",
    "Encyclopedia of Internet - موسوعة الإنترنت",
    "Encyclopedia of Networks - موسوعة الشبكات",
    "Encyclopedia of Databases - موسوعة قواعد البيانات",
    "Encyclopedia of Algorithms - موسوعة الخوارزميات",
    "Encyclopedia of Programming - موسوعة البرمجة",
    "Encyclopedia of Web Development - موسوعة تطوير الويب",
    "Encyclopedia of Mobile Apps - موسوعة تطبيقات الهاتف",
    "Encyclopedia of Cloud Computing - موسوعة الحوسبة السحابية",
    "Encyclopedia of IoT - موسوعة إنترنت الأشياء",
    "Encyclopedia of Virtual Reality - موسوعة الواقع الافتراضي",
    "Encyclopedia of Augmented Reality - موسوعة الواقع المعزز",
    "Encyclopedia of Quantum Computing - موسوعة الحوسبة الكمومية",
    "Encyclopedia of Philosophy - موسوعة الفلسفة",
    "Encyclopedia of Ethics - موسوعة الأخلاق",
    "Encyclopedia of Religion - موسوعة الأديان",
    "Encyclopedia of History - موسوعة التاريخ",
    "Encyclopedia of Archaeology - موسوعة الآثار",
    "Encyclopedia of Anthropology - موسوعة الأنثروبولوجيا",
    "Encyclopedia of Sociology - موسوعة علم الاجتماع",
    "Encyclopedia of Psychology - موسوعة علم النفس",
    "Encyclopedia of Political Science - موسوعة العلوم السياسية",
    "Encyclopedia of Economics - موسوعة الاقتصاد",
    "Encyclopedia of Law - موسوعة القانون",
    "Encyclopedia of Education - موسوعة التعليم",
    "Encyclopedia of Literature - موسوعة الأدب",
    "Encyclopedia of Art - موسوعة الفن",
    "Encyclopedia of Music - موسوعة الموسيقى",
    "Encyclopedia of Theater - موسوعة المسرح",
    "Encyclopedia of Film - موسوعة السينما",
    "Encyclopedia of Architecture - موسوعة العمارة",
    "Encyclopedia of Design - موسوعة التصميم",
    "Encyclopedia of Fashion - موسوعة الموضة"
]

def display_educational_part1():
    print("=" * 80)
    print(f"📚  المؤسسات التعليمية - الدفعة الأولى ({len(educational_institutions_part1)} مؤسسة)  📚")
    print("=" * 80)
    for i, institution in enumerate(educational_institutions_part1, 1):
        print(f"    {i:3d}. {institution}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(educational_institutions_part1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_educational_part1()
