#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# educational_institutions.py - 800+ مؤسسة تعليمية وبحثية وموسوعات

educational_institutions = [
    # ===== 1. الجامعات العالمية (100) =====
    "Harvard University - هارفارد",
    "MIT - معهد ماساتشوستس للتكنولوجيا",
    "Stanford University - ستانفورد",
    "Yale University - ييل",
    "Princeton University - برينستون",
    "Columbia University - كولومبيا",
    "University of Chicago - شيكاغو",
    "University of Pennsylvania - بنسلفانيا",
    "Caltech - معهد كاليفورنيا للتكنولوجيا",
    "Duke University - ديوك",
    "Johns Hopkins University - جونز هوبكنز",
    "Northwestern University - نورث وسترن",
    "Cornell University - كورنيل",
    "Brown University - براون",
    "Rice University - رايس",
    "Dartmouth College - دارتموث",
    "Vanderbilt University - فاندربيلت",
    "Notre Dame University - نوتردام",
    "Georgetown University - جورجتاون",
    "Carnegie Mellon University - كارنيجي ميلون",
    "University of Michigan - ميشيغان",
    "UC Berkeley - بيركلي",
    "UCLA - لوس أنجلوس",
    "NYU - نيويورك",
    "University of Washington - واشنطن",
    "University of Oxford - أكسفورد",
    "University of Cambridge - كامبريدج",
    "Imperial College London - إمبريال كوليدج",
    "LSE - لندن للاقتصاد",
    "UCL - كلية لندن الجامعية",
    "King's College London - كينجز كوليدج",
    "University of Edinburgh - إدنبرة",
    "University of Manchester - مانشستر",
    "University of Bristol - بريستول",
    "University of Warwick - وارويك",
    "University of Glasgow - غلاسكو",
    "University of Birmingham - برمنغهام",
    "University of Leeds - ليدز",
    "University of Nottingham - نوتنغهام",
    "University of Southampton - ساوثهامبتون",
    "University of Sheffield - شيفيلد",
    "University of Liverpool - ليفربول",
    "Queen Mary University - كوين ماري",
    "Durham University - دورهام",
    "University of St Andrews - سانت أندروز",
    "ETH Zurich - زيورخ السويسرية",
    "EPFL - لوزان السويسرية",
    "Sorbonne University - السوربون",
    "Technical University of Munich - ميونخ",
    "LMU Munich - ميونخ",
    "Heidelberg University - هايدلبرغ",
    "Humboldt University - هومبولت",
    "University of Amsterdam - أمستردام",
    "Delft University - دلفت",
    "KU Leuven - لوفين",
    "University of Copenhagen - كوبنهاغن",
    "University of Helsinki - هلسنكي",
    "University of Oslo - أوسلو",
    "Stockholm University - ستوكهولم",
    "Karolinska Institute - كارولينسكا",
    "University of Vienna - فيينا",
    "Sapienza University - سابينزا روما",
    "University of Barcelona - برشلونة",
    "University of Madrid - مدريد",
    "University of Lisbon - لشبونة",
    "University of Tokyo - طوكيو",
    "Kyoto University - كيوتو",
    "Osaka University - أوساكا",
    "Tohoku University - توهوكو",
    "Seoul National University - سيول",
    "KAIST - كوريا للتكنولوجيا",
    "Tsinghua University - تسينغهوا",
    "Peking University - بكين",
    "Fudan University - فودان",
    "Shanghai Jiao Tong - شنغهاي",
    "National University of Singapore - سنغافورة",
    "Nanyang Technological University - نانيانغ",
    "University of Hong Kong - هونغ كونغ",
    "HKUST - هونغ كونغ للعلوم",
    "Chinese University of Hong Kong - الصينية",
    "University of Melbourne - ملبورن",
    "University of Sydney - سيدني",
    "ANU - الوطنية الأسترالية",
    "University of Queensland - كوينزلاند",
    "IIT Bombay - الهندية للتكنولوجيا",
    "جامعة الملك عبدالعزيز - السعودية",
    "جامعة الملك سعود - السعودية",
    "جامعة الملك فهد - السعودية",
    "جامعة القاهرة - مصر",
    "جامعة عين شمس - مصر",
    "جامعة الإسكندرية - مصر",
    "الجامعة الأمريكية بالقاهرة - مصر",
    "الجامعة الأمريكية ببيروت - لبنان",
    "الجامعة اللبنانية - لبنان",
    "جامعة بغداد - العراق",
    "جامعة دمشق - سوريا",
    "جامعة حلب - سوريا",
    "الجامعة الأردنية - الأردن",
    "جامعة اليرموك - الأردن",
    "جامعة الكويت - الكويت",

    # ===== 2. منصات التعلم الإلكتروني (100) =====
    "Coursera - كورسيرا",
    "edX - إيديكس",
    "Udemy - يوديمي",
    "Udacity - يوداسيتي",
    "FutureLearn - فيوتشرليرن",
    "Khan Academy - خان أكاديمي",
    "Codecademy - كودكاديمي",
    "Pluralsight - بلورالسايت",
    "LinkedIn Learning - لينكدإن ليرنينغ",
    "Skillshare - سكيلشير",
    "DataCamp - داتاكامب",
    "Treehouse - تريهاوس",
    "General Assembly - جنرال أسيمبلي",
    "Springboard - سبرينغبورد",
    "Lambda School - لامبدا سكول",
    "Ironhack - أيرونهاك",
    "Le Wagon - لو واجون",
    "App Academy - أب أكاديمي",
    "Hack Reactor - هاك رياكتور",
    "Flatiron School - فلاتيرون سكول",
    "Thinkful - ثينكفول",
    "CareerFoundry - كاريير فاوندري",
    "BrainStation - برين ستيشن",
    "Galvanize - جالفانايز",
    "Makers Academy - ميكرز أكاديمي",
    "Code Institute - كود إنستيتيوت",
    "Wild Code School - وايلد كود سكول",
    "42 School - سكول 42",
    "Holberton School - هولبرتون سكول",
    "Microverse - ميكروفيرس",
    "Duolingo - دوولينغو",
    "Babbel - بابل",
    "Rosetta Stone - روزيتا ستون",
    "Busuu - بوسوو",
    "Memrise - ممرايز",
    "Lingoda - لينغودا",
    "Italki - إيتالكي",
    "Preply - بريبلي",
    "Verbling - فيربلينغ",
    "HelloTalk - هيلو توك",
    "Tandem - تاندم",
    "Lingvist - لينغفيست",
    "Drops - دروبس",
    "Mondly - موندلي",
    "Pimsleur - بيمسلور",
    "Assimil - أسيميل",
    "Berlitz - بيرلتز",
    "EF Education - إي إف",
    "British Council - المجلس الثقافي البريطاني",
    "Alliance Française - الأليانس الفرنسية",
    "GitHub Learning - جيت هاب",
    "Stack Overflow - ستاك أوفرفلو",
    "LeetCode - ليت كود",
    "HackerRank - هاكر رانك",
    "Codeforces - كود فورسز",
    "TopCoder - توب كودر",
    "Codewars - كود وورز",
    "Exercism - إكسيرسيزم",
    "Project Euler - بروجكت أويلر",
    "FreeCodeCamp - فري كود كامب",
    "The Odin Project - مشروع أودين",
    "Scrimba - سكريمبا",
    "Frontend Masters - فرونت إند ماسترز",
    "Egghead.io - إيغ هيد",
    "Laracasts - لاراكاستس",
    "Vue School - فيو سكول",
    "React Training - رياكت ترينينغ",
    "Node School - نود سكول",
    "Python.org - بايثون",
    "W3Schools - دبليو ثري سكولز",
    "MDN Web Docs - إم دي إن",
    "GeeksforGeeks - جيكس فور جيكس",
    "TutorialsPoint - توتوريالز بوينت",
    "JavaTpoint - جافا تي بوينت",
    "Harvard Business School Online - هارفارد للأعمال",
    "Wharton Online - وارتون",
    "Stanford GSB - ستانفورد للأعمال",
    "INSEAD Online - إنسياد",
    "London Business School - لندن للأعمال",
    "MIT Sloan - إم آي تي سلون",
    "Kellogg School - كيلوغ",
    "Columbia Business School - كولومبيا للأعمال",
    "Wharton Executive Education - وارتون التنفيذي",
    "IMD Business School - آي إم دي",
    "HEC Paris - إتش إي سي",
    "IE Business School - آي إي",
    "IESE Business School - إيسي",
    "ESADE - إيساد",
    "Bocconi University - بوكوني",
    "Adobe Creative Cloud - أدوبي",
    "Canva - كانفا",
    "Figma - فيغما",
    "Sketch - سكيتش",
    "InVision - إن فيجن",
    "Behance - بيهانس",
    "Dribbble - دريبل",
    "99designs - 99 ديزاينز",
    "Designlab - ديزاين لاب",
    "Interaction Design Foundation - مؤسسة التصميم التفاعلي",

    # ===== 3. الموسوعات العلمية (100) =====
    "Wikipedia - ويكيبيديا",
    "Encyclopaedia Britannica - بريتانيكا",
    "World Book Encyclopedia - ورلد بوك",
    "Encyclopedia.com - موسوعة دوت كوم",
    "Columbia Encyclopedia - موسوعة كولومبيا",
    "Encyclopedia Americana - الموسوعة الأمريكية",
    "Larousse Encyclopedia - موسوعة لاروس",
    "Brockhaus Enzyklopädie - موسوعة بروكهاوس",
    "Great Soviet Encyclopedia - الموسوعة السوفيتية",
    "Canadian Encyclopedia - الموسوعة الكندية",
    "Australian Encyclopedia - الموسوعة الأسترالية",
    "New World Encyclopedia - موسوعة العالم الجديد",
    "Citizendium - سيتيزنديوم",
    "Scholarpedia - سكولاربيديا",
    "Everything2 - إيفريثينغ 2",
    "Infoplease - إنفو بليز",
    "FactMonster - فاكت مونستر",
    "Encyclopedia of Life - موسوعة الحياة",
    "Encyclopedia of Earth - موسوعة الأرض",
    "Encyclopedia of Science - موسوعة العلوم",
    "Encyclopedia of Physics - موسوعة الفيزياء",
    "Encyclopedia of Chemistry - موسوعة الكيمياء",
    "Encyclopedia of Biology - موسوعة الأحياء",
    "Encyclopedia of Mathematics - موسوعة الرياضيات",
    "Encyclopedia of Astronomy - موسوعة الفلك",
    "Encyclopedia of Medicine - موسوعة الطب",
    "Encyclopedia of Engineering - موسوعة الهندسة",
    "Encyclopedia of Computer Science - موسوعة علوم الحاسوب",
    "Encyclopedia of Neuroscience - موسوعة العلوم العصبية",
    "Encyclopedia of Genetics - موسوعة الوراثة",
    "Encyclopedia of Ecology - موسوعة البيئة",
    "Encyclopedia of Geology - موسوعة الجيولوجيا",
    "Encyclopedia of Oceanography - موسوعة المحيطات",
    "Encyclopedia of Meteorology - موسوعة الأرصاد",
    "Encyclopedia of Psychology - موسوعة علم النفس",
    "Encyclopedia of Sociology - موسوعة علم الاجتماع",
    "Encyclopedia of Philosophy - موسوعة الفلسفة",
    "Encyclopedia of Religion - موسوعة الأديان",
    "Encyclopedia of History - موسوعة التاريخ",
    "Encyclopedia of Economics - موسوعة الاقتصاد",
    "MedlinePlus Medical Encyclopedia - موسوعة ميدلاين",
    "Gale Encyclopedia of Medicine - موسوعة غيل الطبية",
    "Merck Manual - دليل ميرك",
    "Harrison's Principles of Medicine - مبادئ هاريسون",
    "Gray's Anatomy - تشريح غراي",
    "Encyclopedia of Surgery - موسوعة الجراحة",
    "Encyclopedia of Pediatrics - موسوعة طب الأطفال",
    "Encyclopedia of Cardiology - موسوعة طب القلب",
    "Encyclopedia of Neurology - موسوعة طب الأعصاب",
    "Encyclopedia of Oncology - موسوعة الأورام",
    "Encyclopedia of Psychiatry - موسوعة الطب النفسي",
    "Encyclopedia of Dermatology - موسوعة الجلدية",
    "Encyclopedia of Radiology - موسوعة الأشعة",
    "Encyclopedia of Pathology - موسوعة الأمراض",
    "Encyclopedia of Immunology - موسوعة المناعة",
    "Encyclopedia of Pharmacology - موسوعة الأدوية",
    "Encyclopedia of Nutrition - موسوعة التغذية",
    "Encyclopedia of Sports Medicine - موسوعة الطب الرياضي",
    "Encyclopedia of Alternative Medicine - موسوعة الطب البديل",
    "Encyclopedia of Nursing - موسوعة التمريض",
    "Encyclopedia of Artificial Intelligence - موسوعة الذكاء الاصطناعي",
    "Encyclopedia of Machine Learning - موسوعة التعلم الآلي",
    "Encyclopedia of Data Science - موسوعة علوم البيانات",
    "Encyclopedia of Software Engineering - موسوعة هندسة البرمجيات",
    "Encyclopedia of Computer Graphics - موسوعة رسومات الحاسوب",
    "Encyclopedia of Robotics - موسوعة الروبوتات",
    "Encyclopedia of Cybersecurity - موسوعة الأمن السيبراني",
    "Encyclopedia of Blockchain - موسوعة البلوكشين",
    "Encyclopedia of Internet - موسوعة الإنترنت",
    "Encyclopedia of Networks - موسوعة الشبكات",
    "Encyclopedia of Databases - موسوعة قواعد البيانات",
    "Encyclopedia of Algorithms - موسوعة الخوارزميات",
    "Encyclopedia of Programming - موسوعة البرمجة",
    "Encyclopedia of Web Development - موسوعة تطوير الويب",
    "Encyclopedia of Mobile Apps - موسوعة تطبيقات الهاتف",
    "Encyclopedia of Cloud Computing - موسوعة الحوسبة السحابية",
    "Encyclopedia of IoT - موسوعة إنترنت الأشياء",
    "Encyclopedia of Virtual Reality - موسوعة الواقع الافتراضي",
    "Encyclopedia of Augmented Reality - موسوعة الواقع المعزز",
    "Encyclopedia of Quantum Computing - موسوعة الحوسبة الكمومية",
    "Encyclopedia of Philosophy - موسوعة الفلسفة",
    "Encyclopedia of Ethics - موسوعة الأخلاق",
    "Encyclopedia of Religion - موسوعة الأديان",
    "Encyclopedia of History - موسوعة التاريخ",
    "Encyclopedia of Archaeology - موسوعة الآثار",
    "Encyclopedia of Anthropology - موسوعة الأنثروبولوجيا",
    "Encyclopedia of Sociology - موسوعة علم الاجتماع",
    "Encyclopedia of Psychology - موسوعة علم النفس",
    "Encyclopedia of Political Science - موسوعة العلوم السياسية",
    "Encyclopedia of Economics - موسوعة الاقتصاد",
    "Encyclopedia of Law - موسوعة القانون",
    "Encyclopedia of Education - موسوعة التعليم",
    "Encyclopedia of Literature - موسوعة الأدب",
    "Encyclopedia of Art - موسوعة الفن",
    "Encyclopedia of Music - موسوعة الموسيقى",
    "Encyclopedia of Theater - موسوعة المسرح",
    "Encyclopedia of Film - موسوعة السينما",
    "Encyclopedia of Architecture - موسوعة العمارة",
    "Encyclopedia of Design - موسوعة التصميم",
    "Encyclopedia of Fashion - موسوعة الموضة",

    # ===== 4. المكتبات الرقمية (100) =====
    "Library of Congress - مكتبة الكونغرس",
    "British Library - المكتبة البريطانية",
    "Bibliothèque Nationale de France - المكتبة الوطنية الفرنسية",
    "Deutsche Nationalbibliothek - المكتبة الوطنية الألمانية",
    "Biblioteca Nacional de España - المكتبة الوطنية الإسبانية",
    "Russian State Library - المكتبة الروسية",
    "National Library of China - المكتبة الصينية",
    "National Diet Library - المكتبة اليابانية",
    "National Library of India - المكتبة الهندية",
    "Biblioteca Apostolica Vaticana - مكتبة الفاتيكان",
    "Internet Archive - الأرشيف الرقمي",
    "HathiTrust - هاثي تراست",
    "Project Gutenberg - مشروع غوتنبرغ",
    "Google Books - كتب جوجل",
    "Open Library - المكتبة المفتوحة",
    "Europeana - يوروبيانا",
    "World Digital Library - المكتبة الرقمية العالمية",
    "Digital Public Library of America - المكتبة العامة الرقمية",
    "Biodiversity Heritage Library - مكتبة التنوع الحيوي",
    "Medical Heritage Library - المكتبة الطبية التراثية",
    "Smithsonian Libraries - مكتبات سميثسونيان",
    "Harvard Library - مكتبة هارفارد",
    "Yale Library - مكتبة ييل",
    "Oxford Library - مكتبة أكسفورد",
    "Cambridge Library - مكتبة كامبريدج",
    "MIT Library - مكتبة MIT",
    "Stanford Library - مكتبة ستانفورد",
    "Princeton Library - مكتبة برينستون",
    "Columbia Library - مكتبة كولومبيا",
    "University of Chicago Library - مكتبة شيكاغو",
    "Cornell Library - مكتبة كورنيل",
    "Duke Library - مكتبة ديوك",
    "Northwestern Library - مكتبة نورث وسترن",
    "Berkeley Library - مكتبة بيركلي",
    "UCLA Library - مكتبة لوس أنجلوس",
    "NYU Library - مكتبة نيويورك",
    "University of Michigan Library - مكتبة ميشيغان",
    "University of Toronto Library - مكتبة تورنتو",
    "McGill Library - مكتبة ماكغيل",
    "University of Tokyo Library - مكتبة طوكيو",
    "National Library of Singapore - مكتبة سنغافورة",
    "Bibliotheca Alexandrina - مكتبة الإسكندرية",
    "Qatar National Library - مكتبة قطر الوطنية",
    "King Fahd Library - مكتبة الملك فهد",
    "Al-Azhar Library - مكتبة الأزهر",
    "Zaytuna Library - مكتبة الزيتونة",
    "Al-Qarawiyyin Library - مكتبة القرويين",
    "Escorial Library - مكتبة الإسكوريال",
    "Bodleian Library - مكتبة بودليان",
    "Vatican Library - مكتبة الفاتيكان",
    "Bibliotheca Alexandrina Digital - مكتبة الإسكندرية الرقمية",
    "Digital Bodleian - بودليان الرقمية",
    "Cambridge Digital Library - كامبريدج الرقمية",
    "Oxford Digital Library - أكسفورد الرقمية",
    "Harvard Digital Collection - هارفارد الرقمية",
    "Yale Digital Collection - ييل الرقمية",
    "Stanford Digital Repository - ستانفورد الرقمية",
    "MIT Digital Collections - MIT الرقمية",
    "Princeton Digital Library - برينستون الرقمية",
    "Columbia Digital Collections - كولومبيا الرقمية",
    "Cornell Digital Collections - كورنيل الرقمية",
    "Duke Digital Collections - ديوك الرقمية",
    "Northwestern Digital - نورث وسترن الرقمية",
    "Berkeley Digital Collections - بيركلي الرقمية",
    "UCLA Digital Collections - لوس أنجلوس الرقمية",
    "NYU Digital Library - نيويورك الرقمية",
    "Michigan Digital Collections - ميشيغان الرقمية",
    "Toronto Digital Collections - تورنتو الرقمية",
    "McGill Digital Collections - ماكغيل الرقمية",
    "Tokyo Digital Collections - طوكيو الرقمية",
    "Singapore Digital Library - سنغافورة الرقمية",
    "Qatar Digital Library - قطر الرقمية",
    "King Fahd Digital Library - الملك فهد الرقمية",
    "Al-Azhar Digital Library - الأزهر الرقمية",
    "Zaytuna Digital Library - الزيتونة الرقمية",
    "Qarawiyyin Digital Library - القرويين الرقمية",
    "Escorial Digital Library - الإسكوريال الرقمية",
    "Vatican Digital Library - الفاتيكان الرقمية",
    "WorldCat - الفهرس العالمي",
    "OpenCat - الفهرس المفتوح",
    "LibraryThing - لايبراري ثينغ",
    "Goodreads - غود ريدز",
    "Shelfari - شيلفاري",
    "BookLikes - بوك لايكس",
    "Bookish - بوكيش",
    "Readernaut - ريدر نوت",
    "Revish - ريفيش",
    "aNobii - أنوبي",
    "BookRabbit - بوك رابيت",
    "BookArmy - بوك أرمي",
    "BookJetty - بوك جيتي",
    "Libib - ليبب",
    "BookDigits - بوك ديجيتس",
    "Riffle - ريفل",
    "BookLamp - بوك لامب",
    "BookTagger - بوك تاغر",
    "BookSprout - بوك سبراوت",

    # ===== 5. المنصات البحثية (100) =====
    "Google Scholar - جوجل سكولار",
    "ResearchGate - ريسيرش غيت",
    "Academia.edu - أكاديميا",
    "Semantic Scholar - سيمانتيك سكولار",
    "Web of Science - ويب أوف ساينس",
    "Scopus - سكوبس",
    "PubMed - بب ميد",
    "arXiv - أركايف",
    "JSTOR - جستور",
    "ScienceDirect - ساينس دايركت",
    "SpringerLink - سبرينغر لينك",
    "Wiley Online Library - وايلي",
    "Taylor & Francis - تايلور وفرانسيس",
    "SAGE Journals - سيج",
    "Oxford Academic - أكسفورد أكاديميك",
    "Cambridge Core - كامبريدج كور",
    "Nature.com - نيتشر",
    "Science.org - ساينس",
    "PLOS - بلوس",
    "MDPI - إم دي بي آي",
    "IEEE Xplore - آي تريبل إي",
    "ACM Digital Library - إيه سي إم",
    "SSRN - إس إس آر إن",
    "SocArXiv - سوك أركايف",
    "PhilPapers - فيل بيبرز",
    "RePEc - ريبيك",
    "IDEAS - آيديز",
    "NBER - إن بي إي آر",
    "CEPR - سي إي بي آر",
    "OpenAlex - أوبن أليكس",
    "Crossref - كروس ريف",
    "DataCite - داتا سايت",
    "ORCID - أوركيد",
    "figshare - فيغ شير",
    "Zenodo - زينودو",
    "Dryad - درياد",
    "Dataverse - داتافيرس",
    "Mendeley - مندلي",
    "Zotero - زوتيرو",
    "EndNote - إند نوت",
    "RefWorks - ريف وركس",
    "Papers - بيبرز",
    "ReadCube - ريد كيوب",
    "Kopernio - كوبرنيو",
    "Unpaywall - أنباي وول",
    "CORE - كور",
    "BASE - باز",
    "Dimensions - دايمنشنز",
    "Lens.org - لينز",
    "Scilit - سيليت",
    "OpenAIRE - أوبن إير",
    "Europe PMC - يوروب بي إم سي",
    "Cochrane Library - كوكرين",
    "Embase - إمبيس",
    "CINAHL - سيناهل",
    "PsycINFO - سايك إنفو",
    "ERIC - إريك",
    "ProQuest - بروكويست",
    "EBSCO - إبسكو",
    "Gale - غيل",
    "J-Gate - جي غيت",
    "DOAJ - دوج",
    "OpenDOAR - أوبن دوج",
    "SHERPA/RoMEO - شيربا",
    "BASE - باز",
    "CORE - كور",
    "ScienceOpen - ساينس أوبن",
    "F1000Research - إف 1000",
    "PeerJ - بير جي",
    "eLife - إي لايف",
    "BioMed Central - بيو ميد سنترال",
    "Hindawi - هنداوي",
    "Frontiers - فرونتيرز",
    "Bentham Science - بنثام",
    "Thieme - ثيم",
    "Karger - كارغر",
    "De Gruyter - دي غرويتر",
    "Brill - بريل",
    "Emerald - إميرالد",
    "Inderscience - إندرساينس",
    "IGI Global - آي جي آي",
    "World Scientific - ورلد ساينتيفيك",
    "Now Publishers - ناو",
    "Annual Reviews - أنيوال ريفيوز",
    "Portland Press - بورتلاند",
    "Royal Society - الجمعية الملكية",
    "National Academies - الأكاديميات الوطنية",
    "AAAS - الجمعية الأمريكية",
    "Royal Society of Chemistry - الجمعية الملكية للكيمياء",
    "American Chemical Society - الجمعية الكيميائية الأمريكية",
    "American Physical Society - الجمعية الفيزيائية الأمريكية",
    "Institute of Physics - معهد الفيزياء",
    "American Mathematical Society - الجمعية الرياضية الأمريكية",
    "Society for Industrial Mathematics - جمعية الرياضيات الصناعية",
    "American Statistical Association - الجمعية الإحصائية الأمريكية",
    "American Psychological Association - الجمعية النفسية الأمريكية",
    "American Sociological Association - الجمعية الاجتماعية الأمريكية",
    "American Economic Association - الجمعية الاقتصادية الأمريكية",

    # ===== 6. منصات إضافية متخصصة (100) =====
    "TED - تيد",
    "TED-Ed - تيد إد",
    "TEDx - تيد إكس",
    "Big Think - بيغ ثينك",
    "Crash Course - كراش كورس",
    "Vsauce - في سوس",
    "Veritasium - فيريتاسيوم",
    "MinutePhysics - مينيت فيزكس",
    "MinuteEarth - مينيت إيرث",
    "SciShow - ساي شو",
    "AsapSCIENCE - أساب ساين
