#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# islamic_part2.py - الدفعة الثانية: 200+ مرجع شرعي

islamic_references_part2 = [
    # ===== 1. المكتبات الإسلامية (50) =====
    "AlMaktabaShamela.com - المكتبة الشاملة",
    "AlMaktabaWaqfeya.com - المكتبة الوقفية",
    "AlMaktabaIslamiyya.com - المكتبة الإسلامية",
    "AlMaktabaQuran.com - مكتبة القرآن",
    "AlMaktabaHadith.com - مكتبة الحديث",
    "AlMaktabaFiqh.com - مكتبة الفقه",
    "AlMaktabaAqidah.com - مكتبة العقيدة",
    "AlMaktabaSeerah.com - مكتبة السيرة",
    "AlMaktabaTarajim.com - مكتبة التراجم",
    "AlMaktabaTafsir.com - مكتبة التفسير",
    "AlMaktabaUlum.com - مكتبة العلوم",
    "AlMaktabaLugha.com - مكتبة اللغة",
    "AlMaktabaAdab.com - مكتبة الأدب",
    "AlMaktabaTarikh.com - مكتبة التاريخ",
    "AlMaktabaFikr.com - مكتبة الفكر",
    "AlMaktabaDawah.com - مكتبة الدعوة",
    "AlMaktabaTarbiya.com - مكتبة التربية",
    "AlMaktabaAkhlaq.com - مكتبة الأخلاق",
    "AlMaktabaSuluk.com - مكتبة السلوك",
    "AlMaktabaRaqaiq.com - مكتبة الرقائق",
    "AlMaktabaZuhd.com - مكتبة الزهد",
    "AlMaktabaWara.com - مكتبة الورع",
    "AlMaktabaTawbah.com - مكتبة التوبة",
    "AlMaktabaDhikr.com - مكتبة الذكر",
    "AlMaktabaDua.com - مكتبة الدعاء",
    "AlMaktabaAdhkar.com - مكتبة الأذكار",
    "AlMaktabaHajj.com - مكتبة الحج",
    "AlMaktabaUmrah.com - مكتبة العمرة",
    "AlMaktabaSawm.com - مكتبة الصوم",
    "AlMaktabaZakat.com - مكتبة الزكاة",
    "AlMaktabaSalah.com - مكتبة الصلاة",
    "AlMaktabaTahara.com - مكتبة الطهارة",
    "AlMaktabaNikah.com - مكتبة النكاح",
    "AlMaktabaTalaq.com - مكتبة الطلاق",
    "AlMaktabaBuyu.com - مكتبة البيوع",
    "AlMaktabaMawarith.com - مكتبة المواريث",
    "AlMaktabaHudud.com - مكتبة الحدود",
    "AlMaktabaQada.com - مكتبة القضاء",
    "AlMaktabaShahadat.com - مكتبة الشهادات",
    "AlMaktabaAyman.com - مكتبة الأيمان",
    "AlMaktabaNudhur.com - مكتبة النذور",
    "AlMaktabaAtima.com - مكتبة الأطعمة",
    "AlMaktabaAshriba.com - مكتبة الأشربة",
    "AlMaktabaLibas.com - مكتبة اللباس",
    "AlMaktabaZina.com - مكتبة الزينة",
    "AlMaktabaTib.com - مكتبة الطب النبوي",
    "AlMaktabaRuqya.com - مكتبة الرقية",
    "AlMaktabaManamat.com - مكتبة المنامات",
    "AlMaktabaFitan.com - مكتبة الفتن",
    "AlMaktabaMalahim.com - مكتبة الملاحم",

    # ===== 2. المواقع الشرعية (50) =====
    "IslamQA.info - الإسلام سؤال وجواب",
    "IslamWeb.net - إسلام ويب",
    "IslamWay.net - طريق الإسلام",
    "Alukah.net - الألوكة",
    "Saaid.net - صيد الفوائد",
    "Dorar.net - الدرر السنية",
    "Almanhaj.com - المنهج",
    "Albaidha.net - البيضاء",
    "Alifta.net - الإفتاء",
    "AlAzhar.edu.eg - الأزهر الشريف",
    "DarAlifta.org - دار الإفتاء المصرية",
    "Aliftaa.jo - الإفتاء الأردنية",
    "Alifta.gov.sa - الإفتاء السعودية",
    "Awqaf.gov.kw - الأوقاف الكويتية",
    "Awqaf.gov.qa - الأوقاف القطرية",
    "Awqaf.gov.ae - الأوقاف الإماراتية",
    "Awqaf.gov.bh - الأوقاف البحرينية",
    "Awqaf.gov.om - الأوقاف العمانية",
    "Mora.gov.ye - الأوقاف اليمنية",
    "Awqaf.gov.ly - الأوقاف الليبية",
    "Awqaf.gov.tn - الأوقاف التونسية",
    "Awqaf.gov.dz - الأوقاف الجزائرية",
    "Awqaf.gov.ma - الأوقاف المغربية",
    "Awqaf.gov.sd - الأوقاف السودانية",
    "Awqaf.gov.so - الأوقاف الصومالية",
    "Awqaf.gov.mr - الأوقاف الموريتانية",
    "Awqaf.gov.dj - الأوقاف الجيبوتية",
    "Awqaf.gov.km - الأوقاف القمرية",
    "Awqaf.gov.ps - الأوقاف الفلسطينية",
    "Awqaf.gov.sy - الأوقاف السورية",
    "Awqaf.gov.lb - الأوقاف اللبنانية",
    "Awqaf.gov.iq - الأوقاف العراقية",
    "Awqaf.gov.tr - الأوقاف التركية",
    "Awqaf.gov.pk - الأوقاف الباكستانية",
    "Awqaf.gov.af - الأوقاف الأفغانية",
    "Awqaf.gov.ir - الأوقاف الإيرانية",
    "Awqaf.gov.id - الأوقاف الإندونيسية",
    "Awqaf.gov.my - الأوقاف الماليزية",
    "Awqaf.gov.bn - الأوقاف البروناوية",
    "Awqaf.gov.ng - الأوقاف النيجيرية",
    "Awqaf.gov.eg - الأوقاف المصرية",
    "Awqaf.gov.ru - الأوقاف الروسية",
    "Awqaf.gov.cn - الأوقاف الصينية",
    "Awqaf.gov.in - الأوقاف الهندية",
    "Awqaf.gov.bd - الأوقاف البنغالية",
    "Awqaf.gov.lk - الأوقاف السريلانكية",
    "Awqaf.gov.np - الأوقاف النيبالية",
    "Awqaf.gov.mv - الأوقاف المالديفية",
    "Awqaf.gov.uz - الأوقاف الأوزبكية",
    "Awqaf.gov.kz - الأوقاف الكازاخية",

    # ===== 3. الموسوعات الشرعية (50) =====
    "MawsuatHadith.com - موسوعة الحديث",
    "MawsuatFiqh.com - موسوعة الفقه",
    "MawsuatAqidah.com - موسوعة العقيدة",
    "MawsuatTafsir.com - موسوعة التفسير",
    "MawsuatSeerah.com - موسوعة السيرة",
    "MawsuatTarajim.com - موسوعة التراجم",
    "MawsuatUlum.com - موسوعة العلوم",
    "MawsuatLugha.com - موسوعة اللغة",
    "MawsuatAdab.com - موسوعة الأدب",
    "MawsuatTarikh.com - موسوعة التاريخ",
    "MawsuatFikr.com - موسوعة الفكر",
    "MawsuatDawah.com - موسوعة الدعوة",
    "MawsuatTarbiya.com - موسوعة التربية",
    "MawsuatAkhlaq.com - موسوعة الأخلاق",
    "MawsuatSuluk.com - موسوعة السلوك",
    "MawsuatRaqaiq.com - موسوعة الرقائق",
    "MawsuatZuhd.com - موسوعة الزهد",
    "MawsuatWara.com - موسوعة الورع",
    "MawsuatTawbah.com - موسوعة التوبة",
    "MawsuatDhikr.com - موسوعة الذكر",
    "MawsuatDua.com - موسوعة الدعاء",
    "MawsuatAdhkar.com - موسوعة الأذكار",
    "MawsuatHajj.com - موسوعة الحج",
    "MawsuatUmrah.com - موسوعة العمرة",
    "MawsuatSawm.com - موسوعة الصوم",
    "MawsuatZakat.com - موسوعة الزكاة",
    "MawsuatSalah.com - موسوعة الصلاة",
    "MawsuatTahara.com - موسوعة الطهارة",
    "MawsuatNikah.com - موسوعة النكاح",
    "MawsuatTalaq.com - موسوعة الطلاق",
    "MawsuatBuyu.com - موسوعة البيوع",
    "MawsuatMawarith.com - موسوعة المواريث",
    "MawsuatHudud.com - موسوعة الحدود",
    "MawsuatQada.com - موسوعة القضاء",
    "MawsuatShahadat.com - موسوعة الشهادات",
    "MawsuatAyman.com - موسوعة الأيمان",
    "MawsuatNudhur.com - موسوعة النذور",
    "MawsuatAtima.com - موسوعة الأطعمة",
    "MawsuatAshriba.com - موسوعة الأشربة",
    "MawsuatLibas.com - موسوعة اللباس",
    "MawsuatZina.com - موسوعة الزينة",
    "MawsuatTib.com - موسوعة الطب النبوي",
    "MawsuatRuqya.com - موسوعة الرقية",
    "MawsuatManamat.com - موسوعة المنامات",
    "MawsuatFitan.com - موسوعة الفتن",
    "MawsuatMalahim.com - موسوعة الملاحم",
    "MawsuatQiyamah.com - موسوعة القيامة",
    "MawsuatJannah.com - موسوعة الجنة",
    "MawsuatNar.com - موسوعة النار",
    "MawsuatMalaika.com - موسوعة الملائكة",

    # ===== 4. التطبيقات الشرعية (50) =====
    "QuranApp.com - تطبيق القرآن",
    "HadithApp.com - تطبيق الحديث",
    "FiqhApp.com - تطبيق الفقه",
    "AqidahApp.com - تطبيق العقيدة",
    "SeerahApp.com - تطبيق السيرة",
    "TarajimApp.com - تطبيق التراجم",
    "TafsirApp.com - تطبيق التفسير",
    "FatwaApp.com - تطبيق الفتاوى",
    "DhikrApp.com - تطبيق الذكر",
    "DuaApp.com - تطبيق الدعاء",
    "AdhkarApp.com - تطبيق الأذكار",
    "HajjApp.com - تطبيق الحج",
    "UmrahApp.com - تطبيق العمرة",
    "SawmApp.com - تطبيق الصوم",
    "ZakatApp.com - تطبيق الزكاة",
    "SalahApp.com - تطبيق الصلاة",
    "QiblaApp.com - تطبيق القبلة",
    "TasbihApp.com - تطبيق التسبيح",
    "QuranAudioApp.com - تطبيق القرآن الصوتي",
    "HadithAudioApp.com - تطبيق الحديث الصوتي",
    "SeerahAudioApp.com - تطبيق السيرة الصوتية",
    "TafsirAudioApp.com - تطبيق التفسير الصوتي",
    "FiqhAudioApp.com - تطبيق الفقه الصوتي",
    "AqidahAudioApp.com - تطبيق العقيدة الصوتية",
    "FatwaAudioApp.com - تطبيق الفتاوى الصوتية",
    "DhikrAudioApp.com - تطبيق الذكر الصوتي",
    "DuaAudioApp.com - تطبيق الدعاء الصوتي",
    "AdhkarAudioApp.com - تطبيق الأذكار الصوتية",
    "HajjAudioApp.com - تطبيق الحج الصوتي",
    "UmrahAudioApp.com - تطبيق العمرة الصوتية",
    "QuranVideoApp.com - تطبيق القرآن المرئي",
    "HadithVideoApp.com - تطبيق الحديث المرئي",
    "SeerahVideoApp.com - تطبيق السيرة المرئية",
    "TafsirVideoApp.com - تطبيق التفسير المرئي",
    "FiqhVideoApp.com - تطبيق الفقه المرئي",
    "AqidahVideoApp.com - تطبيق العقيدة المرئية",
    "FatwaVideoApp.com - تطبيق الفتاوى المرئية",
    "DhikrVideoApp.com - تطبيق الذكر المرئي",
    "DuaVideoApp.com - تطبيق الدعاء المرئي",
    "AdhkarVideoApp.com - تطبيق الأذكار المرئية",
    "QuranKidsApp.com - تطبيق القرآن للأطفال",
    "HadithKidsApp.com - تطبيق الحديث للأطفال",
    "SeerahKidsApp.com - تطبيق السيرة للأطفال",
    "FiqhKidsApp.com - تطبيق الفقه للأطفال",
    "AqidahKidsApp.com - تطبيق العقيدة للأطفال",
    "AdabKidsApp.com - تطبيق الآداب للأطفال",
    "AkhlaqKidsApp.com - تطبيق الأخلاق للأطفال",
    "DuaKidsApp.com - تطبيق الدعاء للأطفال",
    "DhikrKidsApp.com - تطبيق الذكر للأطفال",
    "AdhkarKidsApp.com - تطبيق الأذكار للأطفال"
]

def display_islamic_part2():
    print("=" * 80)
    print(f"📚  المراجع الشرعية - الدفعة الثانية ({len(islamic_references_part2)} مرجع)  📚")
    print("=" * 80)
    for i, ref in enumerate(islamic_references_part2, 1):
        print(f"    {i:3d}. {ref}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_references_part2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_part2()
