#!/usr/bin/env python3
# -*- coding: utf-8 -*-
islamic_extra_references2 = [
    "QuranApp.com - تطبيق القرآن",
    "HadithApp.com - تطبيق الحديث",
    "FiqhApp.com - تطبيق الفقه",
    "AqidahApp.com - تطبيق العقيدة",
    "SeerahApp.com - تطبيق السيرة",
    "TarajimApp.com - تطبيق التراجم",
    "TafsirApp.com - تطبيق التفسير",
    "FatwaApp.com - تطبيق الفتاوى",
    "DhikrApp.com - تطبيق الذكر",
    "DuaApp.com - تطبيق الدعاء",
    "AdhkarApp.com - تطبيق الأذكار",
    "HajjApp.com - تطبيق الحج",
    "UmrahApp.com - تطبيق العمرة",
    "SawmApp.com - تطبيق الصوم",
    "ZakatApp.com - تطبيق الزكاة",
    "SalahApp.com - تطبيق الصلاة",
    "QiblaApp.com - تطبيق القبلة",
    "TasbihApp.com - تطبيق التسبيح",
    "QuranAudioApp.com - تطبيق القرآن الصوتي",
    "HadithAudioApp.com - تطبيق الحديث الصوتي",
    "SeerahAudioApp.com - تطبيق السيرة الصوتية",
    "TafsirAudioApp.com - تطبيق التفسير الصوتي",
    "FiqhAudioApp.com - تطبيق الفقه الصوتي",
    "AqidahAudioApp.com - تطبيق العقيدة الصوتية",
    "FatwaAudioApp.com - تطبيق الفتاوى الصوتية",
    "DhikrAudioApp.com - تطبيق الذكر الصوتي",
    "DuaAudioApp.com - تطبيق الدعاء الصوتي",
    "AdhkarAudioApp.com - تطبيق الأذكار الصوتية",
    "HajjAudioApp.com - تطبيق الحج الصوتي",
    "UmrahAudioApp.com - تطبيق العمرة الصوتية",
    "QuranVideoApp.com - تطبيق القرآن المرئي",
    "HadithVideoApp.com - تطبيق الحديث المرئي",
    "SeerahVideoApp.com - تطبيق السيرة المرئية",
    "TafsirVideoApp.com - تطبيق التفسير المرئي",
    "FiqhVideoApp.com - تطبيق الفقه المرئي",
    "AqidahVideoApp.com - تطبيق العقيدة المرئية",
    "FatwaVideoApp.com - تطبيق الفتاوى المرئية",
    "DhikrVideoApp.com - تطبيق الذكر المرئي",
    "DuaVideoApp.com - تطبيق الدعاء المرئي",
    "AdhkarVideoApp.com - تطبيق الأذكار المرئية",
    "QuranKidsApp.com - تطبيق القرآن للأطفال",
    "HadithKidsApp.com - تطبيق الحديث للأطفال",
    "SeerahKidsApp.com - تطبيق السيرة للأطفال",
    "FiqhKidsApp.com - تطبيق الفقه للأطفال",
    "AqidahKidsApp.com - تطبيق العقيدة للأطفال",
    "AdabKidsApp.com - تطبيق الآداب للأطفال",
    "AkhlaqKidsApp.com - تطبيق الأخلاق للأطفال",
    "DuaKidsApp.com - تطبيق الدعاء للأطفال",
    "DhikrKidsApp.com - تطبيق الذكر للأطفال",
    "AdhkarKidsApp.com - تطبيق الأذكار للأطفال",
    "QuranAcademy.com - أكاديمية القرآن",
    "HadithAcademy.com - أكاديمية الحديث",
    "FiqhAcademy.com - أكاديمية الفقه",
    "AqidahAcademy.com - أكاديمية العقيدة",
    "SeerahAcademy.com - أكاديمية السيرة",
    "TarajimAcademy.com - أكاديمية التراجم",
    "TafsirAcademy.com - أكاديمية التفسير",
    "FatwaAcademy.com - أكاديمية الفتاوى",
    "DhikrAcademy.com - أكاديمية الذكر",
    "DuaAcademy.com - أكاديمية الدعاء",
    "AdhkarAcademy.com - أكاديمية الأذكار",
    "HajjAcademy.com - أكاديمية الحج",
    "UmrahAcademy.com - أكاديمية العمرة",
    "SawmAcademy.com - أكاديمية الصوم",
    "ZakatAcademy.com - أكاديمية الزكاة",
    "SalahAcademy.com - أكاديمية الصلاة",
    "TaharaAcademy.com - أكاديمية الطهارة",
    "NikahAcademy.com - أكاديمية النكاح",
    "TalaqAcademy.com - أكاديمية الطلاق",
    "BuyuAcademy.com - أكاديمية البيوع",
    "MawarithAcademy.com - أكاديمية المواريث",
    "HududAcademy.com - أكاديمية الحدود",
    "QadaAcademy.com - أكاديمية القضاء",
    "ShahadatAcademy.com - أكاديمية الشهادات",
    "AymanAcademy.com - أكاديمية الأيمان",
    "NudhurAcademy.com - أكاديمية النذور",
    "AtimaAcademy.com - أكاديمية الأطعمة",
    "AshribaAcademy.com - أكاديمية الأشربة",
    "LibasAcademy.com - أكاديمية اللباس",
    "ZinaAcademy.com - أكاديمية الزينة",
    "TibAcademy.com - أكاديمية الطب",
    "RuqyaAcademy.com - أكاديمية الرقية",
    "ManamatAcademy.com - أكاديمية المنامات",
    "FitanAcademy.com - أكاديمية الفتن",
    "MalahimAcademy.com - أكاديمية الملاحم",
    "QiyamahAcademy.com - أكاديمية القيامة",
    "JannahAcademy.com - أكاديمية الجنة",
    "NarAcademy.com - أكاديمية النار",
    "MalaikaAcademy.com - أكاديمية الملائكة",
    "JinnAcademy.com - أكاديمية الجن",
    "QuranInstitute.com - معهد القرآن",
    "HadithInstitute.com - معهد الحديث",
    "FiqhInstitute.com - معهد الفقه",
    "AqidahInstitute.com - معهد العقيدة",
    "SeerahInstitute.com - معهد السيرة",
    "TarajimInstitute.com - معهد التراجم",
    "TafsirInstitute.com - معهد التفسير",
    "FatwaInstitute.com - معهد الفتاوى",
    "DhikrInstitute.com - معهد الذكر",
    "DuaInstitute.com - معهد الدعاء",
    "AdhkarInstitute.com - معهد الأذكار",
    "HajjInstitute.com - معهد الحج",
    "UmrahInstitute.com - معهد العمرة",
    "SawmInstitute.com - معهد الصوم",
    "ZakatInstitute.com - معهد الزكاة",
    "SalahInstitute.com - معهد الصلاة",
    "TaharaInstitute.com - معهد الطهارة",
    "NikahInstitute.com - معهد النكاح",
    "TalaqInstitute.com - معهد الطلاق",
    "BuyuInstitute.com - معهد البيوع",
    "MawarithInstitute.com - معهد المواريث",
    "HududInstitute.com - معهد الحدود",
    "QadaInstitute.com - معهد القضاء",
    "ShahadatInstitute.com - معهد الشهادات",
    "AymanInstitute.com - معهد الأيمان",
    "NudhurInstitute.com - معهد النذور",
    "AtimaInstitute.com - معهد الأطعمة",
    "AshribaInstitute.com - معهد الأشربة",
    "LibasInstitute.com - معهد اللباس",
    "ZinaInstitute.com - معهد الزينة",
    "TibInstitute.com - معهد الطب",
    "RuqyaInstitute.com - معهد الرقية",
    "ManamatInstitute.com - معهد المنامات",
    "FitanInstitute.com - معهد الفتن",
    "MalahimInstitute.com - معهد الملاحم",
    "QiyamahInstitute.com - معهد القيامة",
    "JannahInstitute.com - معهد الجنة",
    "NarInstitute.com - معهد النار",
    "MalaikaInstitute.com - معهد الملائكة",
    "JinnInstitute.com - معهد الجن",
    "QuranUniversity.com - جامعة القرآن",
    "HadithUniversity.com - جامعة الحديث",
    "FiqhUniversity.com - جامعة الفقه",
    "AqidahUniversity.com - جامعة العقيدة",
    "SeerahUniversity.com - جامعة السيرة",
    "TarajimUniversity.com - جامعة التراجم",
    "TafsirUniversity.com - جامعة التفسير",
    "FatwaUniversity.com - جامعة الفتاوى",
    "DhikrUniversity.com - جامعة الذكر",
    "DuaUniversity.com - جامعة الدعاء",
    "AdhkarUniversity.com - جامعة الأذكار",
    "HajjUniversity.com - جامعة الحج",
    "UmrahUniversity.com - جامعة العمرة",
    "SawmUniversity.com - جامعة الصوم",
    "ZakatUniversity.com - جامعة الزكاة",
    "SalahUniversity.com - جامعة الصلاة",
    "TaharaUniversity.com - جامعة الطهارة",
    "NikahUniversity.com - جامعة النكاح",
    "TalaqUniversity.com - جامعة الطلاق",
    "BuyuUniversity.com - جامعة البيوع",
    "MawarithUniversity.com - جامعة المواريث",
    "HududUniversity.com - جامعة الحدود",
    "QadaUniversity.com - جامعة القضاء",
    "ShahadatUniversity.com - جامعة الشهادات",
    "AymanUniversity.com - جامعة الأيمان",
    "NudhurUniversity.com - جامعة النذور",
    "AtimaUniversity.com - جامعة الأطعمة",
    "AshribaUniversity.com - جامعة الأشربة",
    "LibasUniversity.com - جامعة اللباس",
    "ZinaUniversity.com - جامعة الزينة",
    "TibUniversity.com - جامعة الطب",
    "RuqyaUniversity.com - جامعة الرقية",
    "ManamatUniversity.com - جامعة المنامات",
    "FitanUniversity.com - جامعة الفتن",
    "MalahimUniversity.com - جامعة الملاحم",
    "QiyamahUniversity.com - جامعة القيامة",
    "JannahUniversity.com - جامعة الجنة",
    "NarUniversity.com - جامعة النار",
    "MalaikaUniversity.com - جامعة الملائكة",
    "JinnUniversity.com - جامعة الجن"
]

def display_islamic_extra2():
    print("=" * 80)
    print(f"📚  المراجع الشرعية الإضافية - الدفعة الثانية ({len(islamic_extra_references2)} مرجع)  📚")
    print("=" * 80)
    for i, ref in enumerate(islamic_extra_references2, 1):
        print(f"    {i:3d}. {ref}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_extra_references2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_extra2()
