#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# islamic_complete1.py - الدفعة الأولى: 250 مكوّن شرعي شامل

islamic_complete1 = [
    # ===== 1. علوم القرآن (30) =====
    "IlmQiraat.com - علم القراءات",
    "IlmTajwid.com - علم التجويد",
    "IlmTafsir.com - علم التفسير",
    "IlmAsbabNuzul.com - أسباب النزول",
    "IlmNasikhMansukh.com - الناسخ والمنسوخ",
    "IlmMuhkamMutashabih.com - المحكم والمتشابه",
    "IlmAmthalQuran.com - أمثال القرآن",
    "IlmAqsamQuran.com - أقسام القرآن",
    "IlmJadalQuran.com - جدل القرآن",
    "IlmQasasQuran.com - قصص القرآن",
    "IlmIjazQuran.com - إعجاز القرآن",
    "IlmBalaghaQuran.com - بلاغة القرآن",
    "IlmNahwQuran.com - نحو القرآن",
    "IlmSarfQuran.com - صرف القرآن",
    "IlmLughaQuran.com - لغة القرآن",
    "IlmGharibQuran.com - غريب القرآن",
    "IlmWujuhNazair.com - الوجوه والنظائر",
    "IlmMunasabat.com - علم المناسبات",
    "IlmMakkiMadani.com - المكي والمدني",
    "IlmTartibNuzul.com - ترتيب النزول",
    "IlmJamQuran.com - جمع القرآن",
    "IlmRasmQuran.com - رسم القرآن",
    "IlmDabtQuran.com - ضبط القرآن",
    "IlmFawatihSuwar.com - فواتح السور",
    "IlmKhawatimSuwar.com - خواتم السور",
    "IlmAdadAyat.com - عدد الآيات",
    "IlmAdadKalimat.com - عدد الكلمات",
    "IlmAdadHuruf.com - عدد الحروف",
    "IlmAhrufSab'a.com - الأحرف السبعة",
    "IlmWaqfIbtida.com - الوقف والابتداء",

    # ===== 2. علوم الحديث (30) =====
    "IlmRiwaya.com - علم الرواية",
    "IlmDiraya.com - علم الدراية",
    "IlmJarhTa'dil.com - الجرح والتعديل",
    "IlmMustalah.com - علم المصطلح",
    "IlmAsanid.com - علم الأسانيد",
    "IlmMatn.com - علم المتون",
    "IlmRijal.com - علم الرجال",
    "IlmTabaqat.com - علم الطبقات",
    "IlmTarikhRuwwat.com - تاريخ الرواة",
    "IlmIlal.com - علم العلل",
    "IlmTakhrij.com - علم التخريج",
    "IlmSharh.com - علم الشرح",
    "IlmGharibHadith.com - غريب الحديث",
    "IlmMukhtalifHadith.com - مختلف الحديث",
    "IlmNasikhMansukhHadith.com - ناسخ الحديث",
    "IlmTashif.com - علم التصحيف",
    "IlmTahrif.com - علم التحريف",
    "IlmMudraj.com - علم المدرج",
    "IlmMudtarib.com - علم المضطرب",
    "IlmMaqlub.com - علم المقلوب",
    "IlmMudallas.com - علم المدلس",
    "IlmMursal.com - علم المرسل",
    "IlmMunqati.com - علم المنقطع",
    "IlmMu'dal.com - علم المعضل",
    "IlmShadhdh.com - علم الشاذ",
    "IlmMunkar.com - علم المنكر",
    "IlmMatruk.com - علم المتروك",
    "IlmMawdu.com - علم الموضوع",
    "IlmSahih.com - علم الصحيح",
    "IlmHasan.com - علم الحسن",

    # ===== 3. أصول الفقه (30) =====
    "UsulFiqh.com - أصول الفقه",
    "UsulAdilla.com - الأدلة الشرعية",
    "UsulKitab.com - الكتاب",
    "UsulSunnah.com - السنة",
    "UsulIjma.com - الإجماع",
    "UsulQiyas.com - القياس",
    "UsulIstihsan.com - الاستحسان",
    "UsulMaslaha.com - المصالح المرسلة",
    "UsulSaddDharai.com - سد الذرائع",
    "UsulUrf.com - العرف",
    "UsulIstishab.com - الاستصحاب",
    "UsulSharaManQablana.com - شرع من قبلنا",
    "UsulQawlSahabi.com - قول الصحابي",
    "UsulAmr.com - الأمر",
    "UsulNahi.com - النهي",
    "UsulAm.com - العام",
    "UsulKhas.com - الخاص",
    "UsulMutlaq.com - المطلق",
    "UsulMuqayyad.com - المقيد",
    "UsulMujmal.com - المجمل",
    "UsulMubayyan.com - المبين",
    "UsulMantuq.com - المنطوق",
    "UsulMafhum.com - المفهوم",
    "UsulHaqiqa.com - الحقيقة",
    "UsulMajaz.com - المجاز",
    "UsulSarih.com - الصريح",
    "UsulKinaya.com - الكناية",
    "UsulTa'arud.com - التعارض",
    "UsulTarjih.com - الترجيح",
    "UsulIjtihad.com - الاجتهاد",

    # ===== 4. الفقه المقارن (30) =====
    "FiqhMuqaran.com - الفقه المقارن",
    "FiqhMadhahib.com - المذاهب الفقهية",
    "FiqhHanafi.com - المذهب الحنفي",
    "FiqhMaliki.com - المذهب المالكي",
    "FiqhShafii.com - المذهب الشافعي",
    "FiqhHanbali.com - المذهب الحنبلي",
    "FiqhZahiri.com - المذهب الظاهري",
    "FiqhJafari.com - المذهب الجعفري",
    "FiqhZaydi.com - المذهب الزيدي",
    "FiqhIbadi.com - المذهب الإباضي",
    "FiqhSalafi.com - المنهج السلفي",
    "FiqhAsh'ari.com - المنهج الأشعري",
    "FiqhMaturidi.com - المنهج الماتريدي",
    "FiqhSufi.com - المنهج الصوفي",
    "FiqhAthari.com - المنهج الأثري",
    "FiqhMu'tazili.com - المنهج المعتزلي",
    "FiqhJahmi.com - المنهج الجهمي",
    "FiqhMurji'a.com - المنهج المرجئي",
    "FiqhQadari.com - المنهج القدري",
    "FiqhJabri.com - المنهج الجبري",
    "FiqhKhawarij.com - المنهج الخارجي",
    "FiqhShi'i.com - المنهج الشيعي",
    "FiqhSunni.com - المنهج السني",
    "FiqhTashayyu.com - التشيع",
    "FiqhTasawwuf.com - التصوف",
    "FiqhSalafiyya.com - السلفية",
    "FiqhAsh'ariyya.com - الأشعرية",
    "FiqhMaturidiyya.com - الماتريدية",
    "FiqhAthariyya.com - الأثرية",
    "FiqhWasatiyya.com - الوسطية",

    # ===== 5. القواعد الفقهية (30) =====
    "QawaidFiqhiyya.com - القواعد الفقهية",
    "QawaidKubra.com - القواعد الكبرى",
    "QawaidSughra.com - القواعد الصغرى",
    "QawaidKhamsa.com - القواعد الخمس",
    "QawaidUmum.com - القواعد العامة",
    "QawaidKhas.com - القواعد الخاصة",
    "QawaidAsasiyya.com - القواعد الأساسية",
    "QawaidFar'iyya.com - القواعد الفرعية",
    "QawaidKulliyya.com - القواعد الكلية",
    "QawaidJuz'iyya.com - القواعد الجزئية",
    "QawaidFiqhiyyaKubra.com - القواعد الفقهية الكبرى",
    "QawaidFiqhiyyaSughra.com - القواعد الفقهية الصغرى",
    "QawaidUsuliyya.com - القواعد الأصولية",
    "QawaidMaqasidiyya.com - القواعد المقاصدية",
    "QawaidDhawabit.com - الضوابط الفقهية",
    "QawaidFuruq.com - الفروق الفقهية",
    "QawaidNazair.com - النظائر الفقهية",
    "QawaidAshbah.com - الأشباه والنظائر",
    "QawaidTatbiq.com - تطبيقات القواعد",
    "QawaidIstithna.com - استثناءات القواعد",
    "QawaidTa'arud.com - تعارض القواعد",
    "QawaidTarjih.com - ترجيح القواعد",
    "QawaidTakhsis.com - تخصيص القواعد",
    "QawaidTaqyid.com - تقييد القواعد",
    "QawaidNaskh.com - نسخ القواعد",
    "QawaidTanzil.com - تنزيل القواعد",
    "QawaidTakyif.com - تكييف القواعد",
    "QawaidTanzir.com - تنظير القواعد",
    "QawaidTafri.com - تفريع القواعد",
    "QawaidTa'sil.com - تأصيل القواعد",

    # ===== 6. مقاصد الشريعة (25) =====
    "MaqasidSharia.com - مقاصد الشريعة",
    "MaqasidDaruriyyat.com - الضروريات",
    "MaqasidHajiyyat.com - الحاجيات",
    "MaqasidTahsiniyyat.com - التحسينيات",
    "MaqasidDin.com - حفظ الدين",
    "MaqasidNafs.com - حفظ النفس",
    "MaqasidAql.com - حفظ العقل",
    "MaqasidNasl.com - حفظ النسل",
    "MaqasidMal.com - حفظ المال",
    "MaqasidIrda.com - حفظ العرض",
    "MaqasidUmma.com - مقاصد الأمة",
    "MaqasidFard.com - مقاصد الفرد",
    "MaqasidUsra.com - مقاصد الأسرة",
    "MaqasidMujtama.com - مقاصد المجتمع",
    "MaqasidDawla.com - مقاصد الدولة",
    "MaqasidUmmatan.com - مقاصد الأمة",
    "MaqasidInsaniyya.com - المقاصد الإنسانية",
    "MaqasidKawniyya.com - المقاصد الكونية",
    "MaqasidTashri.com - مقاصد التشريع",
    "MaqasidTanzil.com - مقاصد التنزيل",
    "MaqasidTakyif.com - مقاصد التكييف",
    "MaqasidTa'lil.com - مقاصد التعليل",
    "MaqasidTafri.com - مقاصد التفريع",
    "MaqasidTa'sil.com - مقاصد التأصيل",
    "MaqasidTatbiq.com - مقاصد التطبيق",

    # ===== 7. علوم اللغة العربية (25) =====
    "IlmNahw.com - علم النحو",
    "IlmSarf.com - علم الصرف",
    "IlmBalagha.com - علم البلاغة",
    "IlmMa'ani.com - علم المعاني",
    "IlmBayan.com - علم البيان",
    "IlmBadi.com - علم البديع",
    "IlmLugha.com - علم اللغة",
    "IlmFighLugha.com - فقه اللغة",
    "IlmIshtiqaq.com - علم الاشتقاق",
    "IlmTasrif.com - علم التصريف",
    "IlmI'rab.com - علم الإعراب",
    "IlmBina.com - علم البناء",
    "IlmKhat.com - علم الخط",
    "IlmImla.com - علم الإملاء",
    "IlmArud.com - علم العروض",
    "IlmQawafi.com - علم القوافي",
    "IlmAdab.com - علم الأدب",
    "IlmNaqd.com - علم النقد",
    "IlmBalaghaQuran.com - بلاغة القرآن",
    "IlmBalaghaHadith.com - بلاغة الحديث",
    "IlmBalaghaShi'r.com - بلاغة الشعر",
    "IlmBalaghaNathr.com - بلاغة النثر",
    "IlmMa'ajim.com - علم المعاجم",
    "IlmTawlid.com - علم التوليد",
    "IlmDilala.com - علم الدلالة",

    # ===== 8. علوم التاريخ الإسلامي (25) =====
    "TarikhIslam.com - التاريخ الإسلامي",
    "TarikhNabawi.com - التاريخ النبوي",
    "TarikhKhulafa.com - تاريخ الخلفاء",
    "TarikhUmayyad.com - التاريخ الأموي",
    "TarikhAbbasid.com - التاريخ العباسي",
    "TarikhAndalusi.com - التاريخ الأندلسي",
    "TarikhUthmani.com - التاريخ العثماني",
    "TarikhMamluki.com - التاريخ المملوكي",
    "TarikhFatimi.com - التاريخ الفاطمي",
    "TarikhAyyubi.com - التاريخ الأيوبي",
    "TarikhMughul.com - تاريخ المغول",
    "TarikhSaljuqi.com - التاريخ السلجوقي",
    "TarikhSafawi.com - التاريخ الصفوي",
    "TarikhQajari.com - التاريخ القاجاري",
    "TarikhMurabitun.com - تاريخ المرابطين",
    "TarikhMuwahhidun.com - تاريخ الموحدين",
    "TarikhMarini.com - تاريخ المرينيين",
    "TarikhHafsi.com - تاريخ الحفصيين",
    "TarikhZayyani.com - تاريخ الزيانيين",
    "TarikhRustami.com - تاريخ الرستميين",
    "TarikhAghlabi.com - تاريخ الأغالبة",
    "TarikhTuluni.com - تاريخ الطولونيين",
    "TarikhIkhshidi.com - تاريخ الإخشيديين",
    "TarikhHamdani.com - تاريخ الحمدانيين",
    "TarikhBuwayhi.com - تاريخ البويهيين",

    # ===== 9. علوم التربية الإسلامية (25) =====
    "TarbiyaIslamiyya.com - التربية الإسلامية",
    "TarbiyaImaniyya.com - التربية الإيمانية",
    "TarbiyaAkhlaqiyya.com - التربية الأخلاقية",
    "TarbiyaIjtimaiyya.com - التربية الاجتماعية",
    "TarbiyaNafsiyya.com - التربية النفسية",
    "TarbiyaJismiyya.com - التربية الجسدية",
    "TarbiyaAqliyya.com - التربية العقلية",
    "TarbiyaRuhiyya.com - التربية الروحية",
    "TarbiyaUsriyya.com - التربية الأسرية",
    "TarbiyaMadrasiyya.com - التربية المدرسية",
    "TarbiyaMasjidiyya.com - التربية المسجدية",
    "TarbiyaMujtamaiyya.com - التربية المجتمعية",
    "TarbiyaDa'wiyya.com - التربية الدعوية",
    "TarbiyaQur'aniyya.com - التربية القرآنية",
    "TarbiyaNabawiyya.com - التربية النبوية",
    "TarbiyaSalafiyya.com - التربية السلفية",
    "TarbiyaWasatiyya.com - التربية الوسطية",
    "TarbiyaMutawazina.com - التربية المتوازنة",
    "TarbiyaShamila.com - التربية الشاملة",
    "TarbiyaMutakamila.com - التربية المتكاملة",
    "TarbiyaTadarrujiyya.com - التربية التدرجية",
    "TarbiyaFardiyya.com - التربية الفردية",
    "TarbiyaJamaiyya.com - التربية الجماعية",
    "TarbiyaTatbiqiyya.com - التربية التطبيقية",
    "TarbiyaNazariyya.com - التربية النظرية",

    # ===== 10. علوم الدعوة (25) =====
    "DawahIslamiyya.com - الدعوة الإسلامية",
    "DawahFardiyya.com - الدعوة الفردية",
    "DawahJamaiyya.com - الدعوة الجماعية",
    "DawahQur'aniyya.com - الدعوة القرآنية",
    "DawahNabawiyya.com - الدعوة النبوية",
    "DawahSalafiyya.com - الدعوة السلفية",
    "DawahWasatiyya.com - الدعوة الوسطية",
    "DawahHikma.com - الدعوة بالحكمة",
    "DawahMaw'iza.com - الدعوة بالموعظة",
    "DawahJidal.com - الدعوة بالجدال",
    "DawahQudwa.com - الدعوة بالقدوة",
    "DawahUslub.com - أساليب الدعوة",
    "DawahWasail.com - وسائل الدعوة",
    "DawahFi'at.com - فئات المدعوين",
    "DawahGharb.com - الدعوة في الغرب",
    "DawahSharq.com - الدعوة في الشرق",
    "DawahInternet.com - الدعوة عبر الإنترنت",
    "DawahMedia.com - الدعوة الإعلامية",
    "DawahTatbiq.com - الدعوة التطبيقية",
    "DawahNazari.com - الدعوة النظرية",
    "DawahTakhtit.com - تخطيط الدعوة",
    "DawahTanfidh.com - تنفيذ الدعوة",
    "DawahTaqyim.com - تقييم الدعوة",
    "DawahTatwir.com - تطوير الدعوة",
    "DawahShumul.com - شمولية الدعوة"
]

def display_islamic_complete1():
    print("=" * 80)
    print(f"📚  المكونات الشرعية الشاملة - الدفعة الأولى ({len(islamic_complete1)} مكوّن)  📚")
    print("=" * 80)
    for i, item in enumerate(islamic_complete1, 1):
        print(f"    {i:3d}. {item}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_complete1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_complete1()
