#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# islamic_complete2.py - الدفعة الثانية: 250 مكوّن شرعي شامل

islamic_complete2 = [
    # ===== 11. علوم الفتوى (25) =====
    "IlmFatwa.com - علم الفتوى",
    "IlmIfta.com - علم الإفتاء",
    "IlmMufti.com - علم المفتي",
    "IlmMustafti.com - علم المستفتي",
    "IlmFatwaShurut.com - شروط الفتوى",
    "IlmFatwaAdab.com - آداب الفتوى",
    "IlmFatwaUsul.com - أصول الفتوى",
    "IlmFatwaTatbiq.com - تطبيقات الفتوى",
    "IlmFatwaNawazil.com - فتاوى النوازل",
    "IlmFatwaAqalliyat.com - فتاوى الأقليات",
    "IlmFatwaTibbiyya.com - الفتاوى الطبية",
    "IlmFatwaMaliyya.com - الفتاوى المالية",
    "IlmFatwaIjtimaiyya.com - الفتاوى الاجتماعية",
    "IlmFatwaUsriyya.com - الفتاوى الأسرية",
    "IlmFatwaTa'limiyya.com - الفتاوى التعليمية",
    "IlmFatwaQada'iyya.com - الفتاوى القضائية",
    "IlmFatwaJinayiyya.com - الفتاوى الجنائية",
    "IlmFatwaTijariyya.com - الفتاوى التجارية",
    "IlmFatwaSina'iyya.com - الفتاوى الصناعية",
    "IlmFatwaZira'iyya.com - الفتاوى الزراعية",
    "IlmFatwaBunuk.com - فتاوى البنوك",
    "IlmFatwaTamin.com - فتاوى التأمين",
    "IlmFatwaBurssa.com - فتاوى البورصة",
    "IlmFatwaInternet.com - فتاوى الإنترنت",
    "IlmFatwaFada'iyya.com - الفتاوى الفضائية",

    # ===== 12. علوم القضاء (25) =====
    "IlmQada.com - علم القضاء",
    "IlmQadi.com - علم القاضي",
    "IlmMahkama.com - علم المحكمة",
    "IlmDawa.com - علم الدعوى",
    "IlmBayyina.com - علم البينة",
    "IlmShahada.com - علم الشهادة",
    "IlmYamin.com - علم اليمين",
    "IlmNukul.com - علم النكول",
    "IlmHukm.com - علم الحكم",
    "IlmTanfidh.com - علم التنفيذ",
    "IlmIsti'naf.com - علم الاستئناف",
    "IlmTamayyuz.com - علم التمييز",
    "IlmNaqd.com - علم النقض",
    "IlmTaswiya.com - علم التسوية",
    "IlmSulh.com - علم الصلح",
    "IlmTahkim.com - علم التحكيم",
    "IlmWakala.com - علم الوكالة",
    "IlmKhusuma.com - علم الخصومة",
    "IlmMurafa'a.com - علم المرافعة",
    "IlmHujja.com - علم الحجة",
    "IlmDalil.com - علم الدليل",
    "IlmBurhan.com - علم البرهان",
    "IlmQarina.com - علم القرينة",
    "IlmQasama.com - علم القسامة",
    "IlmLi'an.com - علم اللعان",

    # ===== 13. علوم المعاملات (25) =====
    "IlmMu'amalat.com - علم المعاملات",
    "IlmBuyu.com - علم البيوع",
    "IlmIjarah.com - علم الإجارة",
    "IlmRahn.com - علم الرهن",
    "IlmKafala.com - علم الكفالة",
    "IlmHawala.com - علم الحوالة",
    "IlmWakala.com - علم الوكالة",
    "IlmShirka.com - علم الشركة",
    "IlmMudaraba.com - علم المضاربة",
    "IlmMurabaha.com - علم المرابحة",
    "IlmMusharaka.com - علم المشاركة",
    "IlmSalam.com - علم السلم",
    "IlmIstisna.com - علم الاستصناع",
    "IlmQard.com - علم القرض",
    "IlmHiba.com - علم الهبة",
    "IlmWaqf.com - علم الوقف",
    "IlmWasiyya.com - علم الوصية",
    "IlmMirath.com - علم الميراث",
    "IlmZakat.com - علم الزكاة",
    "IlmSadaqa.com - علم الصدقة",
    "IlmKaffara.com - علم الكفارة",
    "IlmNadhr.com - علم النذر",
    "IlmAriyya.com - علم العارية",
    "IlmWadi'a.com - علم الوديعة",
    "IlmLuqata.com - علم اللقطة",

    # ===== 14. علوم الأسرة (25) =====
    "IlmUsra.com - علم الأسرة",
    "IlmNikah.com - علم النكاح",
    "IlmTalaq.com - علم الطلاق",
    "IlmKhul.com - علم الخلع",
    "IlmFaskh.com - علم الفسخ",
    "IlmZihar.com - علم الظهار",
    "IlmIla.com - علم الإيلاء",
    "IlmLi'an.com - علم اللعان",
    "IlmIdda.com - علم العدة",
    "IlmRada'a.com - علم الرضاعة",
    "IlmHidana.com - علم الحضانة",
    "IlmNafaqa.com - علم النفقة",
    "IlmMahr.com - علم المهر",
    "IlmWilaya.com - علم الولاية",
    "IlmWasiyyaUsra.com - وصاية الأسرة",
    "IlmTarbiyaAwlad.com - تربية الأولاد",
    "IlmAdabUsra.com - آداب الأسرة",
    "IlmHuquqZawj.com - حقوق الزوج",
    "IlmHuquqZawja.com - حقوق الزوجة",
    "IlmHuquqAbawayn.com - حقوق الوالدين",
    "IlmHuquqAwlad.com - حقوق الأولاد",
    "IlmSilatRahim.com - صلة الرحم",
    "IlmBirWalidayn.com - بر الوالدين",
    "IlmUsulTasmia.com - أصول التسمية",
    "IlmAqiqa.com - العقيقة",

    # ===== 15. علوم العبادات (25) =====
    "IlmIbadat.com - علم العبادات",
    "IlmTahara.com - علم الطهارة",
    "IlmWudu.com - علم الوضوء",
    "IlmGhusl.com - علم الغسل",
    "IlmTayammum.com - علم التيمم",
    "IlmSalah.com - علم الصلاة",
    "IlmJumu'a.com - علم الجمعة",
    "IlmJama'a.com - علم الجماعة",
    "IlmQasr.com - علم القصر",
    "IlmJam.com - علم الجمع",
    "IlmSawm.com - علم الصوم",
    "IlmZakat.com - علم الزكاة",
    "IlmSadaqaFitr.com - زكاة الفطر",
    "IlmHajj.com - علم الحج",
    "IlmUmrah.com - علم العمرة",
    "IlmTawaf.com - علم الطواف",
    "IlmSa'i.com - علم السعي",
    "IlmWuquf.com - علم الوقوف",
    "IlmRamy.com - علم الرمي",
    "IlmDhabh.com - علم الذبح",
    "IlmAqiqa.com - علم العقيقة",
    "IlmUdhiya.com - علم الأضحية",
    "IlmNadhr.com - علم النذر",
    "IlmKaffara.com - علم الكفارة",
    "IlmDua.com - علم الدعاء",

    # ===== 16. علوم الأخلاق (25) =====
    "IlmAkhlaq.com - علم الأخلاق",
    "IlmAdab.com - علم الآداب",
    "IlmSuluk.com - علم السلوك",
    "IlmTazkiya.com - علم التزكية",
    "IlmTahdhib.com - علم التهذيب",
    "IlmTarbiyaNafs.com - تربية النفس",
    "IlmMujahada.com - علم المجاهدة",
    "IlmMuraqaba.com - علم المراقبة",
    "IlmMuhasaba.com - علم المحاسبة",
    "IlmTawba.com - علم التوبة",
    "IlmInaba.com - علم الإنابة",
    "IlmIstighfar.com - علم الاستغفار",
    "IlmDhikr.com - علم الذكر",
    "IlmDua.com - علم الدعاء",
    "IlmTawakkul.com - علم التوكل",
    "IlmSabr.com - علم الصبر",
    "IlmShukr.com - علم الشكر",
    "IlmRida.com - علم الرضا",
    "IlmZuhd.com - علم الزهد",
    "IlmWara.com - علم الورع",
    "IlmTaqwa.com - علم التقوى",
    "IlmIhsan.com - علم الإحسان",
    "IlmIkhlas.com - علم الإخلاص",
    "IlmSidq.com - علم الصدق",
    "IlmAmana.com - علم الأمانة",

    # ===== 17. علوم العقيدة الموسعة (25) =====
    "IlmIman.com - علم الإيمان",
    "IlmTawhid.com - علم التوحيد",
    "IlmAsmaSifat.com - الأسماء والصفات",
    "IlmQadar.com - علم القدر",
    "IlmQada.com - علم القضاء",
    "IlmSam'iyyat.com - السمعيات",
    "IlmGhaybiyyat.com - الغيبيات",
    "IlmMalaika.com - علم الملائكة",
    "IlmKutub.com - علم الكتب",
    "IlmRusul.com - علم الرسل",
    "IlmYawmAkhar.com - علم اليوم الآخر",
    "IlmQiyamah.com - علم القيامة",
    "IlmJannah.com - علم الجنة",
    "IlmNar.com - علم النار",
    "IlmBarzakh.com - علم البرزخ",
    "IlmHisab.com - علم الحساب",
    "IlmMizan.com - علم الميزان",
    "IlmSirat.com - علم الصراط",
    "IlmHawd.com - علم الحوض",
    "IlmShafa'a.com - علم الشفاعة",
    "IlmAhwalQiyama.com - أحوال القيامة",
    "IlmFitan.com - علم الفتن",
    "IlmMalahim.com - علم الملاحم",
    "IlmAshraat.com - علم الأشراط",
    "IlmMahdi.com - علم المهدي",

    # ===== 18. علوم السيرة الموسعة (25) =====
    "IlmShamail.com - علم الشمائل",
    "IlmDala'il.com - علم الدلائل",
    "IlmKhasais.com - علم الخصائص",
    "IlmFada'il.com - علم الفضائل",
    "IlmManaqib.com - علم المناقب",
    "IlmMaghazi.com - علم المغازي",
    "IlmSaraya.com - علم السرايا",
    "IlmGhazawat.com - علم الغزوات",
    "IlmBi'tha.com - علم البعثة",
    "IlmHijra.com - علم الهجرة",
    "IlmMu'akhat.com - علم المؤاخاة",
    "IlmMithaq.com - علم الميثاق",
    "IlmSahifa.com - علم الصحيفة",
    "IlmWathiq.com - علم الوثيقة",
    "IlmDustur.com - علم الدستور",
    "IlmMujtama.com - علم المجتمع",
    "IlmDawla.com - علم الدولة",
    "IlmJaysh.com - علم الجيش",
    "IlmQadaNabawi.com - القضاء النبوي",
    "IlmIqtisadNabawi.com - الاقتصاد النبوي",
    "IlmSiyasaNabawiyya.com - السياسة النبوية",
    "IlmIjtimaNabawi.com - الاجتماع النبوي",
    "IlmTarbiyaNabawiyya.com - التربية النبوية",
    "IlmDa'waNabawiyya.com - الدعوة النبوية",
    "IlmJihadNabawi.com - الجهاد النبوي",

    # ===== 19. علوم التراجم الموسعة (25) =====
    "IlmSahaba.com - علم الصحابة",
    "IlmTabi'in.com - علم التابعين",
    "IlmAtbaTabi'in.com - أتباع التابعين",
    "IlmMuhaddithin.com - علم المحدثين",
    "IlmFuqaha.com - علم الفقهاء",
    "IlmMufassirin.com - علم المفسرين",
    "IlmUsuliyyin.com - علم الأصوليين",
    "IlmNahwiyyin.com - علم النحويين",
    "IlmLughawiyyin.com - علم اللغويين",
    "IlmUdaba.com - علم الأدباء",
    "IlmShu'ara.com - علم الشعراء",
    "IlmKuttab.com - علم الكتاب",
    "IlmMuarrikhin.com - علم المؤرخين",
    "IlmJughrafiyyin.com - علم الجغرافيين",
    "IlmAtibba.com - علم الأطباء",
    "IlmFalasifa.com - علم الفلاسفة",
    "IlmMutakallimin.com - علم المتكلمين",
    "IlmSufiyya.com - علم الصوفية",
    "IlmZuhhad.com - علم الزهاد",
    "IlmUbbad.com - علم العباد",
    "IlmNussak.com - علم النساك",
    "IlmQussas.com - علم القصاص",
    "IlmWu'az.com - علم الوعاظ",
    "IlmDu'at.com - علم الدعاة",
    "IlmMujahidin.com - علم المجاهدين",

    # ===== 20. علوم المكتبات الشرعية (25) =====
    "IlmFahrasa.com - علم الفهرسة",
    "IlmTasnif.com - علم التصنيف",
    "IlmTartib.com - علم الترتيب",
    "IlmTahqiq.com - علم التحقيق",
    "IlmTakhrij.com - علم التخريج",
    "IlmTawthiq.com - علم التوثيق",
    "IlmNashr.com - علم النشر",
    "IlmTahqiqMakhtutat.com - تحقيق المخطوطات",
    "IlmFihrist.com - علم الفهارس",
    "IlmKashshaf.com - علم الكشافات",
    "IlmAdillah.com - علم الأدلة",
    "IlmMaraji.com - علم المراجع",
    "IlmMasadir.com - علم المصادر",
    "IlmMakhtutat.com - علم المخطوطات",
    "IlmTuraath.com - علم التراث",
    "IlmTahqiqTurath.com - تحقيق التراث",
    "IlmNashrTurath.com - نشر التراث",
    "IlmHifzTurath.com - حفظ التراث",
    "IlmTawthiqTurath.com - توثيق التراث",
    "IlmFahrasaTurath.com - فهرسة التراث",
    "IlmTasnifTurath.com - تصنيف التراث",
    "IlmTartibTurath.com - ترتيب التراث",
    "IlmTahqiqNusus.com - تحقيق النصوص",
    "IlmMuqabala.com - علم المقابلة",
    "IlmTashih.com - علم التصحيح"
]

def display_islamic_complete2():
    print("=" * 80)
    print(f"📚  المكونات الشرعية الشاملة - الدفعة الثانية ({len(islamic_complete2)} مكوّن)  📚")
    print("=" * 80)
    for i, item in enumerate(islamic_complete2, 1):
        print(f"    {i:3d}. {item}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_complete2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_complete2()
