#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# islamic_extra1.py - الدفعة الإضافية الأولى: 200 مرجع شرعي

islamic_extra_references1 = [
    # ===== 1. المكتبات المتخصصة (50) =====
    "MaktabatTafsir.com - مكتبة التفسير المتخصصة",
    "MaktabatHadith.com - مكتبة الحديث المتخصصة",
    "MaktabatFiqh.com - مكتبة الفقه المتخصصة",
    "MaktabatAqidah.com - مكتبة العقيدة المتخصصة",
    "MaktabatSeerah.com - مكتبة السيرة المتخصصة",
    "MaktabatTarajim.com - مكتبة التراجم المتخصصة",
    "MaktabatLugha.com - مكتبة اللغة المتخصصة",
    "MaktabatAdab.com - مكتبة الأدب المتخصصة",
    "MaktabatTarikh.com - مكتبة التاريخ المتخصصة",
    "MaktabatFikr.com - مكتبة الفكر المتخصصة",
    "MaktabatDawah.com - مكتبة الدعوة المتخصصة",
    "MaktabatTarbiya.com - مكتبة التربية المتخصصة",
    "MaktabatAkhlaq.com - مكتبة الأخلاق المتخصصة",
    "MaktabatSuluk.com - مكتبة السلوك المتخصصة",
    "MaktabatRaqaiq.com - مكتبة الرقائق المتخصصة",
    "MaktabatZuhd.com - مكتبة الزهد المتخصصة",
    "MaktabatWara.com - مكتبة الورع المتخصصة",
    "MaktabatTawbah.com - مكتبة التوبة المتخصصة",
    "MaktabatDhikr.com - مكتبة الذكر المتخصصة",
    "MaktabatDua.com - مكتبة الدعاء المتخصصة",
    "MaktabatAdhkar.com - مكتبة الأذكار المتخصصة",
    "MaktabatHajj.com - مكتبة الحج المتخصصة",
    "MaktabatUmrah.com - مكتبة العمرة المتخصصة",
    "MaktabatSawm.com - مكتبة الصوم المتخصصة",
    "MaktabatZakat.com - مكتبة الزكاة المتخصصة",
    "MaktabatSalah.com - مكتبة الصلاة المتخصصة",
    "MaktabatTahara.com - مكتبة الطهارة المتخصصة",
    "MaktabatNikah.com - مكتبة النكاح المتخصصة",
    "MaktabatTalaq.com - مكتبة الطلاق المتخصصة",
    "MaktabatBuyu.com - مكتبة البيوع المتخصصة",
    "MaktabatMawarith.com - مكتبة المواريث المتخصصة",
    "MaktabatHudud.com - مكتبة الحدود المتخصصة",
    "MaktabatQada.com - مكتبة القضاء المتخصصة",
    "MaktabatShahadat.com - مكتبة الشهادات المتخصصة",
    "MaktabatAyman.com - مكتبة الأيمان المتخصصة",
    "MaktabatNudhur.com - مكتبة النذور المتخصصة",
    "MaktabatAtima.com - مكتبة الأطعمة المتخصصة",
    "MaktabatAshriba.com - مكتبة الأشربة المتخصصة",
    "MaktabatLibas.com - مكتبة اللباس المتخصصة",
    "MaktabatZina.com - مكتبة الزينة المتخصصة",
    "MaktabatTib.com - مكتبة الطب المتخصصة",
    "MaktabatRuqya.com - مكتبة الرقية المتخصصة",
    "MaktabatManamat.com - مكتبة المنامات المتخصصة",
    "MaktabatFitan.com - مكتبة الفتن المتخصصة",
    "MaktabatMalahim.com - مكتبة الملاحم المتخصصة",
    "MaktabatQiyamah.com - مكتبة القيامة المتخصصة",
    "MaktabatJannah.com - مكتبة الجنة المتخصصة",
    "MaktabatNar.com - مكتبة النار المتخصصة",
    "MaktabatMalaika.com - مكتبة الملائكة المتخصصة",
    "MaktabatJinn.com - مكتبة الجن المتخصصة",

    # ===== 2. الموسوعات المتخصصة (50) =====
    "MawsuatUlumQuran.com - موسوعة علوم القرآن",
    "MawsuatUlumHadith.com - موسوعة علوم الحديث",
    "MawsuatUlumFiqh.com - موسوعة علوم الفقه",
    "MawsuatUlumAqidah.com - موسوعة علوم العقيدة",
    "MawsuatUlumSeerah.com - موسوعة علوم السيرة",
    "MawsuatUlumTarajim.com - موسوعة علوم التراجم",
    "MawsuatUlumLugha.com - موسوعة علوم اللغة",
    "MawsuatUlumAdab.com - موسوعة علوم الأدب",
    "MawsuatUlwsuatUlumTarajim.com - موسوعة علوم التراجم",
    "MawsuatUlumLugha.com - موسوعة علوم اللغة",
    "MawsuatUlumAdab.com - موسوعة  الدعوة",
    "MawsuatUlumTarbiya.com - موسوعة علوم التربية",
    "MawsuatUlumAkhlaq.com - موسوعة علوم الأخلاق",
    "MawsuatUlumSuluk.com - موسوعة علوم السلوك",
    "MawsuatUlumRaqaiq.com - موسوعة علوم الرقائق",
    "MawsuatUlumZuhd.com - موسوعة علوم الزهد",
    "MawsuatUlumWara.com - موسوعة علوم الورع",
    "MawsuatUlumTawbah.com - موسوعة علوم التوبة",
    "MawsuatUlumDhikr.com - موسوعة علوم الذكر",
    "MawsuatUlumDua.com - موسوعة علوم الدعاء",
    "MawsuatUlumAdhkar.com - موسوعة علوم الأذكار",
    "MawsuatUlumHajj.com - موسوعة علوم الحج",
    "MawsuatUlumUmrah.com - موسوعة علوم العمرة",
    "MawsuatUlumSawm.com - موسوعة علوم الصوم",
    "MawsuatUlumZakat.com - موسوعة علوم الزكاة",
    "MawsuatUlumSalah.com - موسوعة علوم الصلاة",
    "MawsuatUlumTahara.com - موسوعة علوم الطهارة",
    "MawsuatUlumNikah.com - موسوعة علوم النكاح",
    "MawsuatUlumTalaq.com - موسوعة علوم الطلاق",
    "MawsuatUlumBuyu.com - موسوعة علوم البيوع",
    "MawsuatUlumMawarith.com - موسوعة علوم المواريث",
    "MawsuatUlumHudud.com - موسوعة علوم الحدود",
    "MawsuatUlumQada.com - موسوعة علوم القضاء",
    "MawsuatUlumShahadat.com - موسوعة علوم الشهادات",
    "MawsuatUlumAyman.com - موسوعة علوم الأيمان",
    "MawsuatUlumNudhur.com - موسوعة علوم النذور",
    "MawsuatUlumAtima.com - موسوعة علوم الأطعمة",
    "MawsuatUlumAshriba.com - موسوعة علوم الأشربة",
    "MawsuatUlumLibas.com - موسوعة علوم اللباس",
    "MawsuatUlumZina.com - موسوعة علوم الزينة",
    "MawsuatUlumTib.com - موسوعة علوم الطب",
    "MawsuatUlumRuqya.com - موسوعة علوم الرقية",
    "MawsuatUlumManamat.com - موسوعة علوم المنامات",
    "MawsuatUlumFitan.com - موسوعة علوم الفتن",
    "MawsuatUlumMalahim.com - موسوعة علوم الملاحم",
    "MawsuatUlumQiyamah.com - موسوعة علوم القيامة",
    "MawsuatUlumJannah.com - موسوعة علوم الجنة",
    "MawsuatUlumNar.com - موسوعة علوم النار",
    "MawsuatUlumMalaika.com - موسوعة علوم الملائكة",
    "MawsuatUlumJinn.com - موسوعة علوم الجن",

    # ===== 3. المراكز البحثية الشرعية (50) =====
    "MarkazTafsir.com - مركز التفسير",
    "MarkazHadith.com - مركز الحديث",
    "MarkazFiqh.com - مركز الفقه",
    "MarkazAqidah.com - مركز العقيدة",
    "MarkazSeerah.com - مركز السيرة",
    "MarkazTarajim.com - مركز التراجم",
    "MarkazLugha.com - مركز اللغة",
    "MarkazAdab.com - مركز الأدب",
    "MarkazTarikh.com - مركز التاريخ",
    "MarkazFikr.com - مركز الفكر",
    "MarkazDawah.com - مركز الدعوة",
    "MarkazTarbiya.com - مركز التربية",
    "MarkazAkhlaq.com - مركز الأخلاق",
    "MarkazSuluk.com - مركز السلوك",
    "MarkazRaqaiq.com - مركز الرقائق",
    "MarkazZuhd.com - مركز الزهد",
    "MarkazWara.com - مركز الورع",
    "MarkazTawbah.com - مركز التوبة",
    "MarkazDhikr.com - مركز الذكر",
    "MarkazDua.com - مركز الدعاء",
    "MarkazAdhkar.com - مركز الأذكار",
    "MarkazHajj.com - مركز الحج",
    "MarkazUmrah.com - مركز العمرة",
    "MarkazSawm.com - مركز الصوم",
    "MarkazZakat.com - مركز الزكاة",
    "MarkazSalah.com - مركز الصلاة",
    "MarkazTahara.com - مركز الطهارة",
    "MarkazNikah.com - مركز النكاح",
    "MarkazTalaq.com - مركز الطلاق",
    "MarkazBuyu.com - مركز البيوع",
    "MarkazMawarith.com - مركز المواريث",
    "MarkazHudud.com - مركز الحدود",
    "MarkazQada.com - مركز القضاء",
    "MarkazShahadat.com - مركز الشهادات",
    "MarkazAyman.com - مركز الأيمان",
    "MarkazNudhur.com - مركز النذور",
    "MarkazAtima.com - مركز الأطعمة",
    "MarkazAshriba.com - مركز الأشربة",
    "MarkazLibas.com - مركز اللباس",
    "MarkazZina.com - مركز الزينة",
    "MarkazTib.com - مركز الطب",
    "MarkazRuqya.com - مركز الرقية",
    "MarkazManamat.com - مركز المنامات",
    "MarkazFitan.com - مركز الفتن",
    "MarkazMalahim.com - مركز الملاحم",
    "MarkazQiyamah.com - مركز القيامة",
    "MarkazJannah.com - مركز الجنة",
    "MarkazNar.com - مركز النار",
    "MarkazMalaika.com - مركز الملائكة",
    "MarkazJinn.com - مركز الجن",

    # ===== 4. المنتديات والمجتمعات الشرعية (50) =====
    "MultaqaAhlHadith.com - ملتقى أهل الحديث",
    "MultaqaAhlTafsir.com - ملتقى أهل التفسير",
    "MultaqaAhlFiqh.com - ملتقى أهل الفقه",
    "MultaqaAhlAqidah.com - ملتقى أهل العقيدة",
    "MultaqaAhlSeerah.com - ملتقى أهل السيرة",
    "MultaqaAhlTarajim.com - ملتقى أهل التراجم",
    "MultaqaAhlLugha.com - ملتقى أهل اللغة",
    "MultaqaAhlAdab.com - ملتقى أهل الأدب",
    "MultaqaAhlTarikh.com - ملتقى أهل التاريخ",
    "MultaqaAhlFikr.com - ملتقى أهل الفكر",
    "MultaqaAhlDawah.com - ملتقى أهل الدعوة",
    "MultaqaAhlTarbiya.com - ملتقى أهل التربية",
    "MultaqaAhlAkhlaq.com - ملتقى أهل الأخلاق",
    "MultaqaAhlSuluk.com - ملتقى أهل السلوك",
    "MultaqaAhlRaqaiq.com - ملتقى أهل الرقائق",
    "MultaqaAhlZuhd.com - ملتقى أهل الزهد",
    "MultaqaAhlWara.com - ملتقى أهل الورع",
    "MultaqaAhlTawbah.com - ملتقى أهل التوبة",
    "MultaqaAhlDhikr.com - ملتقى أهل الذكر",
    "MultaqaAhlDua.com - ملتقى أهل الدعاء",
    "MultaqaAhlAdhkar.com - ملتقى أهل الأذكار",
    "MultaqaAhlHajj.com - ملتقى أهل الحج",
    "MultaqaAhlUmrah.com - ملتقى أهل العمرة",
    "MultaqaAhlSawm.com - ملتقى أهل الصوم",
    "MultaqaAhlZakat.com - ملتقى أهل الزكاة",
    "MultaqaAhlSalah.com - ملتقى أهل الصلاة",
    "MultaqaAhlTahara.com - ملتقى أهل الطهارة",
    "MultaqaAhlNikah.com - ملتقى أهل النكاح",
    "MultaqaAhlTalaq.com - ملتقى أهل الطلاق",
    "MultaqaAhlBuyu.com - ملتقى أهل البيوع",
    "MultaqaAhlMawarith.com - ملتقى أهل المواريث",
    "MultaqaAhlHudud.com - ملتقى أهل الحدود",
    "MultaqaAhlQada.com - ملتقى أهل القضاء",
    "MultaqaAhlShahadat.com - ملتقى أهل الشهادات",
    "MultaqaAhlAyman.com - ملتقى أهل الأيمان",
    "MultaqaAhlNudhur.com - ملتقى أهل النذور",
    "MultaqaAhlAtima.com - ملتقى أهل الأطعمة",
    "MultaqaAhlAshriba.com - ملتقى أهل الأشربة",
    "MultaqaAhlLibas.com - ملتقى أهل اللباس",
    "MultaqaAhlZina.com - ملتقى أهل الزينة",
    "MultaqaAhlTib.com - ملتقى أهل الطب",
    "MultaqaAhlRuqya.com - ملتقى أهل الرقية",
    "MultaqaAhlManamat.com - ملتقى أهل المنامات",
    "MultaqaAhlFitan.com - ملتقى أهل الفتن",
    "MultaqaAhlMalahim.com - ملتقى أهل الملاحم",
    "MultaqaAhlQiyamah.com - ملتقى أهل القيامة",
    "MultaqaAhlJannah.com - ملتقى أهل الجنة",
    "MultaqaAhlNar.com - ملتقى أهل النار",
    "MultaqaAhlMalaika.com - ملتقى أهل الملائكة",
    "MultaqaAhlJinn.com - ملتقى أهل الجن"
]

def display_islamic_extra1():
    print("=" * 80)
    print(f"📚  المراجع الشرعية الإضافية - الدفعة الأولى ({len(islamic_extra_references1)} مرجع)  📚")
    print("=" * 80)
    for i, ref in enumerate(islamic_extra_references1, 1):
        print(f"    {i:3d}. {ref}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_extra_references1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_extra1()
