#!/usr/bin/env python3
# -*- coding: utf-8 -*-
islamic_extra_references3 = [
    "QuranPlatform.com - منصة القرآن الشاملة",
    "HadithPlatform.com - منصة الحديث الشاملة",
    "FiqhPlatform.com - منصة الفقه الشاملة",
    "AqidahPlatform.com - منصة العقيدة الشاملة",
    "SeerahPlatform.com - منصة السيرة الشاملة",
    "TarajimPlatform.com - منصة التراجم الشاملة",
    "TafsirPlatform.com - منصة التفسير الشاملة",
    "FatwaPlatform.com - منصة الفتاوى الشاملة",
    "DhikrPlatform.com - منصة الذكر الشاملة",
    "DuaPlatform.com - منصة الدعاء الشاملة",
    "AdhkarPlatform.com - منصة الأذكار الشاملة",
    "HajjPlatform.com - منصة الحج الشاملة",
    "UmrahPlatform.com - منصة العمرة الشاملة",
    "SawmPlatform.com - منصة الصوم الشاملة",
    "ZakatPlatform.com - منصة الزكاة الشاملة",
    "SalahPlatform.com - منصة الصلاة الشاملة",
    "TaharaPlatform.com - منصة الطهارة الشاملة",
    "NikahPlatform.com - منصة النكاح الشاملة",
    "TalaqPlatform.com - منصة الطلاق الشاملة",
    "BuyuPlatform.com - منصة البيوع الشاملة",
    "MawarithPlatform.com - منصة المواريث الشاملة",
    "HududPlatform.com - منصة الحدود الشاملة",
    "QadaPlatform.com - منصة القضاء الشاملة",
    "ShahadatPlatform.com - منصة الشهادات الشاملة",
    "AymanPlatform.com - منصة الأيمان الشاملة",
    "NudhurPlatform.com - منصة النذور الشاملة",
    "AtimaPlatform.com - منصة الأطعمة الشاملة",
    "AshribaPlatform.com - منصة الأشربة الشاملة",
    "LibasPlatform.com - منصة اللباس الشاملة",
    "ZinaPlatform.com - منصة الزينة الشاملة",
    "TibPlatform.com - منصة الطب الشاملة",
    "RuqyaPlatform.com - منصة الرقية الشاملة",
    "ManamatPlatform.com - منصة المنامات الشاملة",
    "FitanPlatform.com - منصة الفتن الشاملة",
    "MalahimPlatform.com - منصة الملاحم الشاملة",
    "QiyamahPlatform.com - منصة القيامة الشاملة",
    "JannahPlatform.com - منصة الجنة الشاملة",
    "NarPlatform.com - منصة النار الشاملة",
    "MalaikaPlatform.com - منصة الملائكة الشاملة",
    "JinnPlatform.com - منصة الجن الشاملة",
    "QuranNetwork.com - شبكة القرآن",
    "HadithNetwork.com - شبكة الحديث",
    "FiqhNetwork.com - شبكة الفقه",
    "AqidahNetwork.com - شبكة العقيدة",
    "SeerahNetwork.com - شبكة السيرة",
    "TarajimNetwork.com - شبكة التراجم",
    "TafsirNetwork.com - شبكة التفسير",
    "FatwaNetwork.com - شبكة الفتاوى",
    "DhikrNetwork.com - شبكة الذكر",
    "DuaNetwork.com - شبكة الدعاء",
    "AdhkarNetwork.com - شبكة الأذكار",
    "HajjNetwork.com - شبكة الحج",
    "UmrahNetwork.com - شبكة العمرة",
    "SawmNetwork.com - شبكة الصوم",
    "ZakatNetwork.com - شبكة الزكاة",
    "SalahNetwork.com - شبكة الصلاة",
    "TaharaNetwork.com - شبكة الطهارة",
    "NikahNetwork.com - شبكة النكاح",
    "TalaqNetwork.com - شبكة الطلاق",
    "BuyuNetwork.com - شبكة البيوع",
    "MawarithNetwork.com - شبكة المواريث",
    "HududNetwork.com - شبكة الحدود",
    "QadaNetwork.com - شبكة القضاء",
    "ShahadatNetwork.com - شبكة الشهادات",
    "AymanNetwork.com - شبكة الأيمان",
    "NudhurNetwork.com - شبكة النذور",
    "AtimaNetwork.com - شبكة الأطعمة",
    "AshribaNetwork.com - شبكة الأشربة",
    "LibasNetwork.com - شبكة اللباس",
    "ZinaNetwork.com - شبكة الزينة",
    "TibNetwork.com - شبكة الطب",
    "RuqyaNetwork.com - شبكة الرقية",
    "ManamatNetwork.com - شبكة المنامات",
    "FitanNetwork.com - شبكة الفتن",
    "MalahimNetwork.com - شبكة الملاحم",
    "QiyamahNetwork.com - شبكة القيامة",
    "JannahNetwork.com - شبكة الجنة",
    "NarNetwork.com - شبكة النار",
    "MalaikaNetwork.com - شبكة الملائكة",
    "JinnNetwork.com - شبكة الجن",
    "QuranPortal.com - بوابة القرآن",
    "HadithPortal.com - بوابة الحديث",
    "FiqhPortal.com - بوابة الفقه",
    "AqidahPortal.com - بوابة العقيدة",
    "SeerahPortal.com - بوابة السيرة",
    "TarajimPortal.com - بوابة التراجم",
    "TafsirPortal.com - بوابة التفسير",
    "FatwaPortal.com - بوابة الفتاوى",
    "DhikrPortal.com - بوابة الذكر",
    "DuaPortal.com - بوابة الدعاء",
    "AdhkarPortal.com - بوابة الأذكار",
    "HajjPortal.com - بوابة الحج",
    "UmrahPortal.com - بوابة العمرة",
    "SawmPortal.com - بوابة الصوم",
    "ZakatPortal.com - بوابة الزكاة",
    "SalahPortal.com - بوابة الصلاة",
    "TaharaPortal.com - بوابة الطهارة",
    "NikahPortal.com - بوابة النكاح",
    "TalaqPortal.com - بوابة الطلاق",
    "BuyuPortal.com - بوابة البيوع",
    "MawarithPortal.com - بوابة المواريث",
    "HududPortal.com - بوابة الحدود",
    "QadaPortal.com - بوابة القضاء",
    "ShahadatPortal.com - بوابة الشهادات",
    "AymanPortal.com - بوابة الأيمان",
    "NudhurPortal.com - بوابة النذور",
    "AtimaPortal.com - بوابة الأطعمة",
    "AshribaPortal.com - بوابة الأشربة",
    "LibasPortal.com - بوابة اللباس",
    "ZinaPortal.com - بوابة الزينة",
    "TibPortal.com - بوابة الطب",
    "RuqyaPortal.com - بوابة الرقية",
    "ManamatPortal.com - بوابة المنامات",
    "FitanPortal.com - بوابة الفتن",
    "MalahimPortal.com - بوابة الملاحم",
    "QiyamahPortal.com - بوابة القيامة",
    "JannahPortal.com - بوابة الجنة",
    "NarPortal.com - بوابة النار",
    "MalaikaPortal.com - بوابة الملائكة",
    "JinnPortal.com - بوابة الجن",
    "QuranCenter.com - مركز القرآن",
    "HadithCenter.com - مركز الحديث",
    "FiqhCenter.com - مركز الفقه",
    "AqidahCenter.com - مركز العقيدة",
    "SeerahCenter.com - مركز السيرة",
    "TarajimCenter.com - مركز التراجم",
    "TafsirCenter.com - مركز التفسير",
    "FatwaCenter.com - مركز الفتاوى",
    "DhikrCenter.com - مركز الذكر",
    "DuaCenter.com - مركز الدعاء",
    "AdhkarCenter.com - مركز الأذكار",
    "HajjCenter.com - مركز الحج",
    "UmrahCenter.com - مركز العمرة",
    "SawmCenter.com - مركز الصوم",
    "ZakatCenter.com - مركز الزكاة",
    "SalahCenter.com - مركز الصلاة",
    "TaharaCenter.com - مركز الطهارة",
    "NikahCenter.com - مركز النكاح",
    "TalaqCenter.com - مركز الطلاق",
    "BuyuCenter.com - مركز البيوع",
    "MawarithCenter.com - مركز المواريث",
    "HududCenter.com - مركز الحدود",
    "QadaCenter.com - مركز القضاء",
    "ShahadatCenter.com - مركز الشهادات",
    "AymanCenter.com - مركز الأيمان",
    "NudhurCenter.com - مركز النذور",
    "AtimaCenter.com - مركز الأطعمة",
    "AshribaCenter.com - مركز الأشربة",
    "LibasCenter.com - مركز اللباس",
    "ZinaCenter.com - مركز الزينة",
    "TibCenter.com - مركز الطب",
    "RuqyaCenter.com - مركز الرقية",
    "ManamatCenter.com - مركز المنامات",
    "FitanCenter.com - مركز الفتن",
    "MalahimCenter.com - مركز الملاحم",
    "QiyamahCenter.com - مركز القيامة",
    "JannahCenter.com - مركز الجنة",
    "NarCenter.com - مركز النار",
    "MalaikaCenter.com - مركز الملائكة",
    "JinnCenter.com - مركز الجن"
]

def display_islamic_extra3():
    print("=" * 80)
    print(f"📚  المراجع الشرعية الإضافية - الدفعة الثالثة ({len(islamic_extra_references3)} مرجع)  📚")
    print("=" * 80)
    for i, ref in enumerate(islamic_extra_references3, 1):
        print(f"    {i:3d}. {ref}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_extra_references3)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_extra3()
