#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# islamic_part1.py - الدفعة الأولى: 200 مرجع ومنصة شرعية

islamic_references_part1 = [
    # ===== 1. القرآن الكريم وعلومه (30) =====
    "Quran.com - القرآن الكريم",
    "Tanzil.net - تنزيل",
    "AlQuran.cloud - القرآن السحابي",
    "QuranExplorer.com - مستكشف القرآن",
    "QuranComplex.gov.sa - مجمع الملك فهد",
    "NQuran.com - نور القرآن",
    "Equranlibrary.com - مكتبة القرآن",
    "Altafsir.com - التفسير",
    "Tafsir.app - تطبيق التفسير",
    "TafsirIbnKathir.com - تفسير ابن كثير",
    "TafsirTabari.com - تفسير الطبري",
    "TafsirQurtubi.com - تفسير القرطبي",
    "TafsirBagawi.com - تفسير البغوي",
    "TafsirSaadi.com - تفسير السعدي",
    "TafsirShanqiti.com - تفسير الشنقيطي",
    "TafsirRazi.com - تفسير الرازي",
    "TafsirZamakhshari.com - تفسير الزمخشري",
    "TafsirBaydawi.com - تفسير البيضاوي",
    "TafsirNasafi.com - تفسير النسفي",
    "TafsirJalalayn.com - تفسير الجلالين",
    "TafsirMuyassar.com - التفسير الميسر",
    "TafsirMukhtasar.com - التفسير المختصر",
    "TafsirWasit.com - التفسير الوسيط",
    "TafsirWajiz.com - التفسير الوجيز",
    "TafsirTadabbur.com - تفسير التدبر",
    "TafsirAmali.com - تفسير الأمثالي",
    "TafsirNoor.com - تفسير النور",
    "TafsirMunir.com - تفسير المنير",
    "TafsirKabir.com - تفسير الكبير",
    "TafsirFiZilal.com - في ظلال القرآن",

    # ===== 2. الحديث الشريف وعلومه (30) =====
    "Sunnah.com - السنة النبوية",
    "Dorar.net - الدرر السنية",
    "AlMohaddith.com - المحدث",
    "HadithPortal.com - بوابة الحديث",
    "HadithLibrary.com - مكتبة الحديث",
    "HadithExplorer.com - مستكشف الحديث",
    "HadithSearch.com - بحث الحديث",
    "HadithDatabase.com - قاعدة الحديث",
    "SahihBukhari.com - صحيح البخاري",
    "SahihMuslim.com - صحيح مسلم",
    "SunanAbiDawud.com - سنن أبي داود",
    "SunanTirmidhi.com - سنن الترمذي",
    "SunanNasai.com - سنن النسائي",
    "SunanIbnMajah.com - سنن ابن ماجه",
    "MuwattaMalik.com - موطأ مالك",
    "MusnadAhmad.com - مسند أحمد",
    "MusnadShafii.com - مسند الشافعي",
    "MusnadAbiHanifa.com - مسند أبي حنيفة",
    "SahihIbnHibban.com - صحيح ابن حبان",
    "SahihIbnKhuzayma.com - صحيح ابن خزيمة",
    "MustadrakHakim.com - مستدرك الحاكم",
    "SahihIbnAwanah.com - صحيح ابن عوانة",
    "SahihAbiAwanah.com - صحيح أبي عوانة",
    "SunanDaraqutni.com - سنن الدارقطني",
    "SunanBayhaqi.com - سنن البيهقي",
    "SunanSaidIbnMansur.com - سنن سعيد بن منصور",
    "MusannafAbdulRazzaq.com - مصنف عبد الرزاق",
    "MusannafIbnAbiShayba.com - مصنف ابن أبي شيبة",
    "SharhNawawi.com - شرح النووي",
    "FathulBari.com - فتح الباري",

    # ===== 3. الفقه وأصوله (30) =====
    "IslamicFiqh.com - الفقه الإسلامي",
    "FiqhPortal.com - بوابة الفقه",
    "FiqhLibrary.com - مكتبة الفقه",
    "FiqhExplorer.com - مستكشف الفقه",
    "FiqhDatabase.com - قاعدة الفقه",
    "FiqhSearch.com - بحث الفقه",
    "FiqhHanafi.com - الفقه الحنفي",
    "FiqhMaliki.com - الفقه المالكي",
    "FiqhShafii.com - الفقه الشافعي",
    "FiqhHanbali.com - الفقه الحنبلي",
    "FiqhMuqaran.com - الفقه المقارن",
    "FiqhUsul.com - أصول الفقه",
    "FiqhQawaid.com - القواعد الفقهية",
    "FiqhMaqasid.com - مقاصد الشريعة",
    "FiqhNawazil.com - فقه النوازل",
    "FiqhAqalliyat.com - فقه الأقليات",
    "FiqhTahawwulat.com - فقه التحولات",
    "FiqhAwlawiyat.com - فقه الأولويات",
    "FiqhMuwazanat.com - فقه الموازنات",
    "FiqhWaqi.com - فقه الواقع",
    "FiqhMasarif.com - فقه المصارف",
    "FiqhZakat.com - فقه الزكاة",
    "FiqhWaqf.com - فقه الوقف",
    "FiqhMirath.com - فقه المواريث",
    "FiqhNikah.com - فقه النكاح",
    "FiqhTalaq.com - فقه الطلاق",
    "FiqhBuyu.com - فقه البيوع",
    "FiqhIjarah.com - فقه الإجارة",
    "FiqhRahn.com - فقه الرهن",
    "FiqhKafala.com - فقه الكفالة",

    # ===== 4. العقيدة والتوحيد (20) =====
    "AqidahIslam.com - العقيدة الإسلامية",
    "AqidahPortal.com - بوابة العقيدة",
    "AqidahLibrary.com - مكتبة العقيدة",
    "AqidahExplorer.com - مستكشف العقيدة",
    "AqidahTahawiyya.com - العقيدة الطحاوية",
    "AqidahWasitiyya.com - العقيدة الواسطية",
    "AqidahHamawiyya.com - العقيدة الحموية",
    "AqidahTadmuriyya.com - العقيدة التدمرية",
    "AqidahSafariniyya.com - العقيدة السفارينية",
    "AqidahNuniyya.com - النونية",
    "TawhidIslam.com - التوحيد",
    "TawhidAsma.com - توحيد الأسماء والصفات",
    "TawhidUluhiyya.com - توحيد الألوهية",
    "TawhidRububiyya.com - توحيد الربوبية",
    "TawhidIbadah.com - توحيد العبادة",
    "TawhidHakimiyya.com - توحيد الحاكمية",
    "TawhidMuttaba.com - توحيد المتابعة",
    "TawhidWala.com - الولاء والبراء",
    "TawhidShirk.com - الشرك وأنواعه",
    "TawhidBidah.com - البدع",

    # ===== 5. السيرة النبوية (20) =====
    "SeerahNabawiyya.com - السيرة النبوية",
    "SeerahPortal.com - بوابة السيرة",
    "SeerahLibrary.com - مكتبة السيرة",
    "SeerahExplorer.com - مستكشف السيرة",
    "SeerahIbnHisham.com - سيرة ابن هشام",
    "SeerahIbnIshaq.com - سيرة ابن إسحاق",
    "SeerahHalabiyya.com - السيرة الحلبية",
    "SeerahShamiyya.com - السيرة الشامية",
    "SeerahDahlan.com - السيرة الدحلانية",
    "SeerahNabawiyyaIbnKathir.com - سيرة ابن كثير",
    "SeerahSuhayli.com - الروض الأنف",
    "SeerahQadiIyad.com - الشفا للقاضي عياض",
    "SeerahMubarakpuri.com - الرحيق المختوم",
    "SeerahGhazali.com - فقه السيرة",
    "SeerahButi.com - فقه السيرة للبوطي",
    "SeerahSallabi.com - السيرة النبوية للصلابي",
    "SeerahNadwi.com - السيرة النبوية للندوي",
    "SeerahQahtani.com - السيرة النبوية للقحطاني",
    "SeerahUthaymin.com - السيرة النبوية للعثيمين",
    "SeerahAlbani.com - السيرة النبوية للألباني",

    # ===== 6. التراجم والرجال (20) =====
    "TarajimIslam.com - التراجم الإسلامية",
    "TarajimPortal.com - بوابة التراجم",
    "TarajimLibrary.com - مكتبة التراجم",
    "TarajimExplorer.com - مستكشف التراجم",
    "TarajimSahaba.com - تراجم الصحابة",
    "TarajimTabiin.com - تراجم التابعين",
    "TarajimUlama.com - تراجم العلماء",
    "TarajimMuhaddithin.com - تراجم المحدثين",
    "TarajimFuqaha.com - تراجم الفقهاء",
    "TarajimMufassirin.com - تراجم المفسرين",
    "TarajimShuara.com - تراجم الشعراء",
    "TarajimUdaba.com - تراجم الأدباء",
    "TarajimNisa.com - تراجم النساء",
    "TarajimAalam.com - الأعلام للزركلي",
    "TarajimSiyar.com - سير أعلام النبلاء",
    "TarajimTahdhib.com - تهذيب التهذيب",
    "TarajimTaqrib.com - تقريب التهذيب",
    "TarajimMizan.com - ميزان الاعتدال",
    "TarajimLisan.com - لسان الميزان",
    "TarajimWafayat.com - وفيات الأعيان",

    # ===== 7. التزكية والرقائق (20) =====
    "TazkiyahIslam.com - التزكية الإسلامية",
    "TazkiyahPortal.com - بوابة التزكية",
    "TazkiyahLibrary.com - مكتبة التزكية",
    "TazkiyahNafs.com - تزكية النفس",
    "TazkiyahQalb.com - تزكية القلب",
    "TazkiyahRuh.com - تزكية الروح",
    "RaqaiqIslam.com - الرقائق",
    "RaqaiqQalb.com - رقائق القلوب",
    "RaqaiqIman.com - رقائق الإيمان",
    "RaqaiqTawbah.com - رقائق التوبة",
    "RaqaiqDhikr.com - رقائق الذكر",
    "RaqaiqDua.com - رقائق الدعاء",
    "RaqaiqTawakkul.com - رقائق التوكل",
    "RaqaiqSabr.com - رقائق الصبر",
    "RaqaiqShukr.com - رقائق الشكر",
    "RaqaiqZuhd.com - رقائق الزهد",
    "RaqaiqWara.com - رقائق الورع",
    "RaqaiqKhawf.com - رقائق الخوف",
    "RaqaiqRaja.com - رقائق الرجاء",
    "RaqaiqMahabba.com - رقائق المحبة",

    # ===== 8. الفتاوى (30) =====
    "FatwaIslam.com - الفتاوى الإسلامية",
    "FatwaPortal.com - بوابة الفتاوى",
    "FatwaLibrary.com - مكتبة الفتاوى",
    "FatwaExplorer.com - مستكشف الفتاوى",
    "FatwaIbnTaymiyyah.com - فتاوى ابن تيمية",
    "FatwaIbnQayyim.com - فتاوى ابن القيم",
    "FatwaNawawi.com - فتاوى النووي",
    "FatwaIbnBaz.com - فتاوى ابن باز",
    "FatwaUthaymin.com - فتاوى العثيمين",
    "FatwaAlbani.com - فتاوى الألباني",
    "FatwaFawzan.com - فتاوى الفوزان",
    "FatwaJibrin.com - فتاوى الجبرين",
    "FatwaMunajjid.com - فتاوى المنجد",
    "FatwaQaradawi.com - فتاوى القرضاوي",
    "FatwaTantawi.com - فتاوى الطنطاوي",
    "FatwaShaltut.com - فتاوى شلتوت",
    "FatwaKhallaf.com - فتاوى خلاف",
    "FatwaZuhayli.com - فتاوى الزحيلي",
    "FatwaButi.com - فتاوى البوطي",
    "FatwaSallabi.com - فتاوى الصلابي",
    "FatwaIslamQA.com - الإسلام سؤال وجواب",
    "FatwaIslamWeb.com - إسلام ويب",
    "FatwaAlifta.com - الرئاسة العامة للبحوث",
    "FatwaAssembly.com - مجمع الفقه الإسلامي",
    "FatwaAzhar.com - الأزهر الشريف",
    "FatwaDarIfta.com - دار الإفتاء المصرية",
    "FatwaJordan.com - دائرة الإفتاء الأردنية",
    "FatwaSaudi.com - الإفتاء السعودية",
    "FatwaKuwait.com - الإفتاء الكويتية",
    "FatwaQatar.com - الإفتاء القطرية"
]

def display_islamic_part1():
    print("=" * 80)
    print(f"📚  المراجع الشرعية - الدفعة الأولى ({len(islamic_references_part1)} مرجع)  📚")
    print("=" * 80)
    for i, ref in enumerate(islamic_references_part1, 1):
        print(f"    {i:3d}. {ref}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(islamic_references_part1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_islamic_part1()
