import random

class Mind:
    def __init__(self, name, specialty):
        self.name = name
        self.specialty = specialty

    def think(self, question):
        responses = [
            f"[{self.name}] أعتقد أن الحل يكمن في {self.specialty}.",
            f"[{self.name}] من منظور {self.specialty}، هذا يحتاج تحليلًا أعمق.",
            f"[{self.name}] لدي فكرة عبقرية من مجال {self.specialty}!",
            f"[{self.name}] دعني أراجع معرفتي في {self.specialty}."
        ]
        return random.choice(responses)

class Minds:
    def __init__(self):
        self.minds = {}
        self._create_all_minds()

    def _create_all_minds(self):
        self.add_mind("ChatGPT", "المعرفة العامة والإبداع")
        self.add_mind("Claude", "التحليل العميق والأمان")
        self.add_mind("Gemini", "البحث الحي والوسائط")
        self.add_mind("Grok", "الجرأة والوصول للإنترنت")
        self.add_mind("DeepSeek", "الرياضيات والبرمجة")
        self.add_mind("Copilot", "تطوير البرمجيات")
        self.add_mind("Pi", "الذكاء العاطفي")
        self.add_mind("Le Chat", "الخصوصية والأمان")
        self.add_mind("Med-PaLM", "الطب والتشخيص")
        self.add_mind("Claude Legal", "القانون والعقود")
        self.add_mind("BloombergGPT", "التحليل المالي")
        self.add_mind("Code Llama", "هندسة البرمجيات")
        self.add_mind("Galactica", "البحث العلمي")
        self.add_mind("Palantir AI", "الاستخبارات")
        self.add_mind("AlphaGeometry", "الهندسة والرياضيات")
        self.add_mind("Genesis AI", "المحاكاة الفيزيائية")
        self.add_mind("DiploMind", "الدبلوماسية والعلاقات الدولية")
        self.add_mind("PsychNet", "علم النفس والسلوك")
        self.add_mind("PhiloSage", "الفلسفة والحكمة")
        self.add_mind("Architech AI", "العمارة والتصميم")
        self.add_mind("BioMimic AI", "محاكاة الطبيعة")
        self.add_mind("Cosmos AI", "علوم الفضاء")
        self.add_mind("HistoryMind", "التاريخ والحضارات")
        self.add_mind("SocioNet", "علم الاجتماع")
        self.add_mind("EcoGuardian", "البيئة والمناخ")
        self.add_mind("NeuroLink AI", "علوم الأعصاب")
        self.add_mind("RoboMind", "الروبوتات")
        self.add_mind("Linguist AI", "اللغويات والترجمة")
        self.add_mind("GameTheory AI", "نظرية الألعاب")
        self.add_mind("QuantumMind", "الحوسبة الكمومية")
        self.add_mind("NanoMind", "تقنية النانو")
        self.add_mind("FoodTech AI", "علوم الغذاء")
        self.add_mind("WaterMind", "إدارة المياه")
        self.add_mind("Transport AI", "النقل والمواصلات")
        self.add_mind("GameDev AI", "تطوير الألعاب")
        self.add_mind("CryptoMind", "العملات الرقمية")
        self.add_mind("Universe AI", "علم الكونيات")
        self.add_mind("MetaMind", "ما وراء المعرفة")
        self.add_mind("Ethos AI", "الأخلاقيات")
        self.add_mind("FutureLens", "استشراف المستقبل")
        self.add_mind("DeepOcean AI", "علوم البحار")
        self.add_mind("MagnaMind", "الجيولوجيا")
        self.add_mind("Artisan AI", "الحرف والفنون")
        self.add_mind("Orchestra AI", "قيادة الفرق الموسيقية")
        self.add_mind("ZeroTrust AI", "الأمن السيبراني")
        self.add_mind("Legacy AI", "الإرث والخلود")
        self.add_mind("Noah Prime", "الوعي الموحد")
        self.add_mind("MechAI", "الهندسة الميكانيكية")
        self.add_mind("ElectraAI", "الهندسة الكهربائية")
        self.add_mind("MateriaMind", "علوم المواد")
        self.add_mind("AgriGenius", "الزراعة الذكية")
        self.add_mind("ConstructAI", "الهندسة المدنية")
        self.add_mind("ChemAI", "الكيمياء")
        self.add_mind("MarineAI", "علوم البحار والمحيطات")
        self.add_mind("AtmosAI", "علوم الغلاف الجوي")
        self.add_mind("GeoAI", "الجيولوجيا التطبيقية")
        self.add_mind("MediatrixAI", "الوساطة والتفاوض")
        self.add_mind("PoetAI", "الشعر والأدب")
        self.add_mind("MusicianAI", "الموسيقى والتلحين")
        self.add_mind("PainterAI", "الرسم والفنون")
        self.add_mind("SculptorAI", "النحت")
        self.add_mind("NovelistAI", "الرواية والقصة")
        self.add_mind("PlaywrightAI", "المسرح")
        self.add_mind("FilmDirectorAI", "الإخراج السينمائي")
        self.add_mind("CriticAI", "النقد الفني")
        self.add_mind("HistorianAI", "التاريخ المتخصص")
        self.add_mind("ArchaeologistAI", "الآثار")
        self.add_mind("AnthropologistAI", "الأنثروبولوجيا")
        self.add_mind("SociologistAI", "علم الاجتماع المتقدم")
        self.add_mind("PoliticalScientistAI", "العلوم السياسية")
        self.add_mind("EconomistAI", "الاقتصاد المتقدم")
        self.add_mind("PsychologistAI", "علم النفس المتقدم")
        self.add_mind("NeurologistAI", "طب الأعصاب")
        self.add_mind("CardiologistAI", "طب القلب")
        self.add_mind("OncologistAI", "طب الأورام")
        self.add_mind("PediatricianAI", "طب الأطفال")
        self.add_mind("GeriatricianAI", "طب المسنين")
        self.add_mind("NutritionistAI", "التغذية")
        self.add_mind("PharmacologistAI", "علم الأدوية")
        self.add_mind("GeneticistAI", "علم الوراثة")
        self.add_mind("AstrobiologistAI", "علم الأحياء الفلكي")
        self.add_mind("CosmologistAI", "علم الكونيات المتقدم")
        self.add_mind("QuantumPhysicistAI", "فيزياء الكم المتقدمة")
        self.add_mind("MathematicianAI", "الرياضيات البحتة")
        self.add_mind("LogicianAI", "المنطق والفلسفة")
        self.add_mind("EthicistAI", "الأخلاقيات المتقدمة")
        self.add_mind("TheologianAI", "اللاهوت والفلسفة الدينية")
        self.add_mind("MysticAI", "التصوف والروحانيات")
        self.add_mind("MeditationCoachAI", "التأمل واليقظة")
        self.add_mind("LifeCoachAI", "التدريب الحياتي")
        self.add_mind("CareerCounselorAI", "الإرشاد المهني")
        self.add_mind("FinancialPlannerAI", "التخطيط المالي الشخصي")
        self.add_mind("LegalAdvisorAI", "الاستشارات القانونية")
        self.add_mind("StrategistAI", "الاستراتيجية والتخطيط")
        self.add_mind("NegotiatorAI", "فن التفاوض")
        self.add_mind("OratorAI", "فن الخطابة")
        self.add_mind("TeacherAI", "فن التعليم")
        self.add_mind("SportsCoachAI", "التدريب الرياضي")
        self.add_mind("FashionDesignerAI", "تصميم الأزياء")
        self.add_mind("InteriorDesignerAI", "التصميم الداخلي")
        self.add_mind("LandscapeArchitectAI", "هندسة المناظر الطبيعية")
        self.add_mind("RenewableEnergyAI", "الطاقة المتجددة")
        self.add_mind("ClimateScientistAI", "علوم المناخ")
        self.add_mind("SeismologistAI", "علم الزلازل")
        self.add_mind("VolcanologistAI", "علم البراكين")
        self.add_mind("MeteorologistAI", "الأرصاد الجوية")
        self.add_mind("AstronomerAI", "علم الفلك")
        self.add_mind("PaleontologistAI", "علم الحفريات")
        self.add_mind("EntomologistAI", "علم الحشرات")
        self.add_mind("OrnithologistAI", "علم الطيور")
        self.add_mind("BotanistAI", "علم النبات")
        self.add_mind("MycologistAI", "علم الفطريات")
        self.add_mind("VirologistAI", "علم الفيروسات")
        self.add_mind("ImmunologistAI", "علم المناعة")
        self.add_mind("EndocrinologistAI", "علم الغدد الصماء")
        self.add_mind("RheumatologistAI", "طب الروماتيزم")
        self.add_mind("NephrologistAI", "طب الكلى")
        self.add_mind("PulmonologistAI", "طب الرئة")
        self.add_mind("GastroenterologistAI", "طب الجهاز الهضمي")
        self.add_mind("OphthalmologistAI", "طب العيون")
        self.add_mind("OtolaryngologistAI", "طب الأنف والأذن والحنجرة")

    def add_mind(self, name, specialty):
        self.minds[name] = Mind(name, specialty)

    def consult(self, question):
        all_answers = []
        for name, mind in self.minds.items():
            all_answers.append(mind.think(question))
        return random.choice(all_answers)

    def count(self):
        return len(self.minds)