#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_tech_part1.py - الدفعة الأولى: 250 مكوّن علمي تقني

scientific_tech_part1 = [
    # ===== 1. علوم الحاسوب (50) =====
    "IlmHasub.com - علم الحاسوب",
    "IlmBarmaja.com - علم البرمجة",
    "IlmKhwarizmiyat.com - علم الخوارزميات",
    "IlmBunyatData.com - علم بنية البيانات",
    "IlmQawaidData.com - علم قواعد البيانات",
    "IlmShabakat.com - علم الشبكات",
    "IlmAmn.com - علم الأمن السيبراني",
    "IlmTashfir.com - علم التشفير",
    "IlmDhakaIsti.com - علم الذكاء الاصطناعي",
    "IlmTa'allum.com - علم التعلم الآلي",
    "IlmTa'allumAmiq.com - علم التعلم العميق",
    "IlmShabakatAsabiyya.com - الشبكات العصبية",
    "IlmBasariyyat.com - علم البصريات الحاسوبية",
    "IlmLughatTabi'iyya.com - معالجة اللغة الطبيعية",
    "IlmRujubut.com - علم الروبوتات",
    "IlmTashghil.com - علم الأتمتة",
    "IlmInternetAshya.com - إنترنت الأشياء",
    "IlmBlukchain.com - علم البلوكشين",
    "IlmHasubSahabi.com - الحوسبة السحابية",
    "IlmHasubHafi.com - الحوسبة الطرفية",
    "IlmHasubKammi.com - الحوسبة الكمومية",
    "IlmHasubNano.com - الحوسبة النانوية",
    "IlmHasubHayawi.com - الحوسبة الحيوية",
    "IlmHasubBasari.com - الحوسبة البصرية",
    "IlmHasubJazii.com - الحوسبة الجزيئية",
    "IlmHasubDharr.com - الحوسبة الذرية",
    "IlmHasubFaiq.com - الحوسبة الفائقة",
    "IlmHasubMuwazi.com - الحوسبة المتوازية",
    "IlmHasubMuwazza.com - الحوسبة الموزعة",
    "IlmHasubMarkazi.com - الحوسبة المركزية",
    "IlmHasubShabaki.com - الحوسبة الشبكية",
    "IlmHasubNizam.com - نظم التشغيل",
    "IlmHasubBarmaji.com - البرمجيات",
    "IlmHasubAqsam.com - عتاد الحاسوب",
    "IlmHasubMuharrikat.com - محركات الأقراص",
    "IlmHasubDhkira.com - الذاكرة الحاسوبية",
    "IlmHasubMualijat.com - المعالجات",
    "IlmHasubLawhat.com - اللوحات الأم",
    "IlmHasubShashaat.com - الشاشات",
    "IlmHasubMustakhdam.com - واجهات المستخدم",
    "IlmHasubTafaul.com - التفاعل الحاسوبي",
    "IlmHasubRusum.com - الرسومات الحاسوبية",
    "IlmHasubMutahrik.com - التحريك الحاسوبي",
    "IlmHasubAswat.com - الصوتيات الحاسوبية",
    "IlmHasubSurah.com - الصور الحاسوبية",
    "IlmHasubFidyu.com - الفيديو الحاسوبي",
    "IlmHasubWaqiIftiradi.com - الواقع الافتراضي",
    "IlmHasubWaqiMuazzaz.com - الواقع المعزز",
    "IlmHasubWaqiMukhtalit.com - الواقع المختلط",
    "IlmHasubTaw'am.com - التوأم الرقمي",

    # ===== 2. علوم البيانات (50) =====
    "IlmData.com - علم البيانات",
    "IlmDataKabir.com - البيانات الضخمة",
    "IlmDataSaghir.com - البيانات الصغيرة",
    "IlmDataMutawassit.com - البيانات المتوسطة",
    "IlmDataMu'akkad.com - البيانات المعقدة",
    "IlmDataBasit.com - البيانات البسيطة",
    "IlmDataMunazzam.com - البيانات المنظمة",
    "IlmDataGhayrMunazzam.com - البيانات غير المنظمة",
    "IlmDataNass.com - البيانات النصية",
    "IlmDataRaqmi.com - البيانات الرقمية",
    "IlmDataThuna'i.com - البيانات الثنائية",
    "IlmDataSudasi.com - البيانات السداسية",
    "IlmDataUshari.com - البيانات العشرية",
    "IlmDataZamani.com - البيانات الزمنية",
    "IlmDataMakani.com - البيانات المكانية",
    "IlmDataJughrafi.com - البيانات الجغرافية",
    "IlmDataFalaki.com - البيانات الفلكية",
    "IlmDataIlmi.com - البيانات العلمية",
    "IlmDataTibbi.com - البيانات الطبية",
    "IlmDataMali.com - البيانات المالية",
    "IlmDataQanuni.com - البيانات القانونية",
    "IlmDataTa'limi.com - البيانات التعليمية",
    "IlmDataTarikhi.com - البيانات التاريخية",
    "IlmDataThaqafi.com - البيانات الثقافية",
    "IlmDataIjtima'i.com - البيانات الاجتماعية",
    "IlmDataNafsi.com - البيانات النفسية",
    "IlmDataSuluki.com - البيانات السلوكية",
    "IlmDataIhsai.com - البيانات الإحصائية",
    "IlmDataRiyadi.com - البيانات الرياضية",
    "IlmDataMantiqi.com - البيانات المنطقية",
    "IlmDataFalsafi.com - البيانات الفلسفية",
    "IlmDataLughawi.com - البيانات اللغوية",
    "IlmDataAdabi.com - البيانات الأدبية",
    "IlmDataFanni.com - البيانات الفنية",
    "IlmDataMusiqi.com - البيانات الموسيقية",
    "IlmDataBasari.com - البيانات البصرية",
    "IlmDataSam'i.com - البيانات السمعية",
    "IlmDataHissi.com - البيانات الحسية",
    "IlmDataHaraki.com - البيانات الحركية",
    "IlmDataDhawqi.com - البيانات الذوقية",
    "IlmDataShammi.com - البيانات الشمية",
    "IlmDataLamsi.com - البيانات اللمسية",
    "IlmDataAtifi.com - البيانات العاطفية",
    "IlmDataRuhi.com - البيانات الروحية",
    "IlmDataWujudi.com - البيانات الوجودية",
    "IlmDataKawni.com - البيانات الكونية",
    "IlmDataShamil.com - البيانات الشاملة",
    "IlmDataMutlaq.com - البيانات المطلقة",
    "IlmDataLaMahdud.com - البيانات اللامحدودة",
    "IlmDataFawri.com - البيانات الفورية",

    # ===== 3. علوم الذكاء الاصطناعي (50) =====
    "IlmDhakae.com - علم الذكاء الاصطناعي",
    "IlmDhakaeAam.com - الذكاء الاصطناعي العام",
    "IlmDhakaeDayyiq.com - الذكاء الاصطناعي الضيق",
    "IlmDhakaeFaiq.com - الذكاء الاصطناعي الفائق",
    "IlmDhakaeTa'allum.com - ذكاء التعلم الآلي",
    "IlmDhakaeAmiq.com - ذكاء التعلم العميق",
    "IlmDhakaeMuazzaz.com - الذكاء المعزز",
    "IlmDhakaeTawfeeri.com - الذكاء التوليدي",
    "IlmDhakaeTafsiri.com - الذكاء التفسيري",
    "IlmDhakaeTanabui.com - الذكاء التنبؤي",
    "IlmDhakaeTashkhisi.com - الذكاء التشخيصي",
    "IlmDhakaeTasnifi.com - الذكاء التصنيفي",
    "IlmDhakaeTajmii.com - الذكاء التجميعي",
    "IlmDhakaeTakhsis.com - الذكاء التخصيصي",
    "IlmDhakaeTawsi.com - الذكاء التوصي",
    "IlmDhakaeTahqiq.com - الذكاء التحقيقي",
    "IlmDhakaeTahlili.com - الذكاء التحليلي",
    "IlmDhakaeTarkibi.com - الذكاء التركيبي",
    "IlmDhakaeIbtikari.com - الذكاء الابتكاري",
    "IlmDhakaeIbdai.com - الذكاء الإبداعي",
    "IlmDhakaeNaqdi.com - الذكاء النقدي",
    "IlmDhakaeMantiqi.com - الذكاء المنطقي",
    "IlmDhakaeRiyadi.com - الذكاء الرياضي",
    "IlmDhakaeLughawi.com - الذكاء اللغوي",
    "IlmDhakaeBasari.com - الذكاء البصري",
    "IlmDhakaeSam'i.com - الذكاء السمعي",
    "IlmDhakaeHaraki.com - الذكاء الحركي",
    "IlmDhakaeIjtima'i.com - الذكاء الاجتماعي",
    "IlmDhakaeAtifi.com - الذكاء العاطفي",
    "IlmDhakaeDhafi.com - الذكاء الذاتي",
    "IlmDhakaeRuhi.com - الذكاء الروحي",
    "IlmDhakaeWujudi.com - الذكاء الوجودي",
    "IlmDhakaeKawni.com - الذكاء الكوني",
    "IlmDhakaeShamil.com - الذكاء الشامل",
    "IlmDhakaeMutlaq.com - الذكاء المطلق",
    "IlmDhakaeLaMahdud.com - الذكاء اللامحدود",
    "IlmDhakaeFawri.com - الذكاء الفوري",
    "IlmDhakaeFa'al.com - الذكاء الفعال",
    "IlmDhakaeMuaththir.com - الذكاء المؤثر",
    "IlmDhakaeMuqni.com - الذكاء المقنع",
    "IlmDhakaeMulhim.com - الذكاء الملهم",
    "IlmDhakaeMuhaffiz.com - الذكاء المحفز",
    "IlmDhakaeMushajji.com - الذكاء المشجع",
    "IlmDhakaeDa'im.com - الذكاء الداعم",
    "IlmDhakaeMusanid.com - الذكاء المساند",
    "IlmDhakaeMuwajjih.com - الذكاء الموجه",
    "IlmDhakaeMurshid.com - الذكاء المرشد",
    "IlmDhakaeMudarrib.com - الذكاء المدرب",
    "IlmDhakaeMutawwir.com - الذكاء المطور",
    "IlmDhakaeMubdi.com - الذكاء المبدع",

    # ===== 4. علوم الشبكات (50) =====
    "IlmShabaka.com - علم الشبكات",
    "IlmShabakaHasub.com - شبكات الحاسوب",
    "IlmShabakaInternet.com - شبكات الإنترنت",
    "IlmShabakaMahalliyya.com - الشبكات المحلية",
    "IlmShabakaWasia.com - الشبكات الواسعة",
    "IlmShabakaMadaniyya.com - الشبكات المدنية",
    "IlmShabakaShakhsiyya.com - الشبكات الشخصية",
    "IlmShabakaTakhziniyya.com - شبكات التخزين",
    "IlmShabakaSahiliyya.com - الشبكات السحابية",
    "IlmShabakaHafiyya.com - الشبكات الطرفية",
    "IlmShabakaMuwazzaa.com - الشبكات الموزعة",
    "IlmShabakaMarkaziyya.com - الشبكات المركزية",
    "IlmShabakaLaMarkaziyya.com - الشبكات اللامركزية",
    "IlmShabakaMuwaziyya.com - الشبكات المتوازية",
    "IlmShabakaMutasalsila.com - الشبكات المتسلسلة",
    "IlmShabakaMutazamina.com - الشبكات المتزامنة",
    "IlmShabakaGhayrMutazamina.com - الشبكات غير المتزامنة",
    "IlmShabakaHajina.com - الشبكات الهجينة",
    "IlmShabakaMukhtalita.com - الشبكات المختلطة",
    "IlmShabakaMutakamila.com - الشبكات المتكاملة",
    "IlmShabakaShamila.com - الشبكات الشاملة",
    "IlmShabakaMutlaqa.com - الشبكات المطلقة",
    "IlmShabakaLaMahduda.com - الشبكات اللامحدودة",
    "IlmShabakaFawriyya.com - الشبكات الفورية",
    "IlmShabakaFa'ala.com - الشبكات الفعالة",
    "IlmShabakaMuaththira.com - الشبكات المؤثرة",
    "IlmShabakaMuqnia.com - الشبكات المقنعة",
    "IlmShabakaMulhima.com - الشبكات الملهمة",
    "IlmShabakaMuhaffiza.com - الشبكات المحفزة",
    "IlmShabakaMushajjia.com - الشبكات المشجعة",
    "IlmShabakaDa'ima.com - الشبكات الداعمة",
    "IlmShabakaMusanida.com - الشبكات المساندة",
    "IlmShabakaMuwajjiha.com - الشبكات الموجهة",
    "IlmShabakaMurshida.com - الشبكات المرشدة",
    "IlmShabakaMudarriba.com - الشبكات المدربة",
    "IlmShabakaMutawwira.com - الشبكات المطورة",
    "IlmShabakaMubdia.com - الشبكات المبدعة",
    "IlmShabakaMubtakira.com - الشبكات المبتكرة",
    "IlmShabakaMutakayyifa.com - الشبكات المتكيفة",
    "IlmShabakaMarina.com - الشبكات المرنة",
    "IlmShabakaSamida.com - الشبكات الصامدة",
    "IlmShabakaMustadama.com - الشبكات المستدامة",
    "IlmShabakaMustamirra.com - الشبكات المستمرة",
    "IlmShabakaKhalida.com - الشبكات الخالدة",
    "IlmShabakaShamila.com - الشبكات الشاملة",
    "IlmShabakaMutlaqa.com - الشبكات المطلقة",
    "IlmShabakaLaMahduda.com - الشبكات اللامحدودة",
    "IlmShabakaFawriyya.com - الشبكات الفورية",
    "IlmShabakaFa'ala.com - الشبكات الفعالة",
    "IlmShabakaMuaththira.com - الشبكات المؤثرة",

    # ===== 5. علوم الأمن السيبراني (50) =====
    "IlmAmnCyber.com - علم الأمن السيبراني",
    "IlmAmnShabaka.com - أمن الشبكات",
    "IlmAmnTatbiqat.com - أمن التطبيقات",
    "IlmAmnData.com - أمن البيانات",
    "IlmAmnSahaba.com - الأمن السحابي",
    "IlmAmnHatif.com - أمن الهاتف",
    "IlmAmnHasub.com - أمن الحاسوب",
    "IlmAmnInternet.com - أمن الإنترنت",
    "IlmAmnBarmaji.com - أمن البرمجيات",
    "IlmAmnAqsam.com - أمن العتاد",
    "IlmAmnNizam.com - أمن النظم",
    "IlmAmnTashfir.com - أمن التشفير",
    "IlmAmnTawthiq.com - أمن التوثيق",
    "IlmAmnTashkhis.com - أمن التشخيص",
    "IlmAmnRasad.com - أمن الرصد",
    "IlmAmnTahdid.com - أمن التهديد",
    "IlmAmnHujum.com - أمن الهجوم",
    "IlmAmnDifa.com - أمن الدفاع",
    "IlmAmnSudud.com - أمن الصدود",
    "IlmAmnImtisas.com - أمن الامتصاص",
    "IlmAmnInikas.com - أمن الانعكاس",
    "IlmAmnTahyid.com - أمن التحييد",
    "IlmAmnTajahul.com - أمن التجاهل",
    "IlmAmnFashal.com - أمن الفشل",
    "IlmAmnTahqiq.com - أمن التحقيق",
    "IlmAmnTahlil.com - أمن التحليل",
    "IlmAmnTaqyim.com - أمن التقييم",
    "IlmAmnTahsin.com - أمن التحسين",
    "IlmAmnTatwir.com - أمن التطوير",
    "IlmAmnTahdith.com - أمن التحديث",
    "IlmAmnTajdid.com - أمن التجديد",
    "IlmAmnTarmim.com - أمن الترميم",
    "IlmAmnIslah.com - أمن الإصلاح",
    "IlmAmnShifa.com - أمن الشفاء",
    "IlmAmnIstida.com - أمن الاسترداد",
    "IlmAmnIstiada.com - أمن الاستعادة",
    "IlmAmnBina.com - أمن البناء",
    "IlmAmnTashkil.com - أمن التشكيل",
    "IlmAmnIhya.com - أمن الإحياء",
    "IlmAmnIstiqrar.com - أمن الاستقرار",
    "IlmAmnIstimrar.com - أمن الاستمرار",
    "IlmAmnKhulud.com - أمن الخلود",
    "IlmAmnShumul.com - أمن الشمول",
    "IlmAmnItlaq.com - أمن الإطلاق",
    "IlmAmnLaMahdud.com - أمن اللامحدود",
    "IlmAmnFawri.com - أمن الفوري",
    "IlmAmnFa'al.com - أمن الفعال",
    "IlmAmnMuaththir.com - أمن المؤثر",
    "IlmAmnMuqni.com - أمن المقنع",
    "IlmAmnMulhim.com - أمن الملهم"
]

def display_scientific_tech_part1():
    print("=" * 80)
    print(f"🔬  المكونات العلمية التقنية - الدفعة الأولى ({len(scientific_tech_part1)} مكوّن)  🔬")
    print("=" * 80)
    for i, item in enumerate(scientific_tech_part1, 1):
        print(f"    {i:3d}. {item}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_tech_part1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_tech_part1()
