#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_tech_part2.py - الدفعة الثانية: 250 مكوّن علمي تقني

scientific_tech_part2 = [
    # ===== 6. علوم الروبوتات (50) =====
    "IlmRobot.com - علم الروبوتات",
    "IlmRobotSina'i.com - الروبوتات الصناعية",
    "IlmRobotTibbi.com - الروبوتات الطبية",
    "IlmRobotAskari.com - الروبوتات العسكرية",
    "IlmRobotFada'i.com - الروبوتات الفضائية",
    "IlmRobotBahri.com - الروبوتات البحرية",
    "IlmRobotJawwi.com - الروبوتات الجوية",
    "IlmRobotBarri.com - الروبوتات البرية",
    "IlmRobotManzili.com - الروبوتات المنزلية",
    "IlmRobotTa'limi.com - الروبوتات التعليمية",
    "IlmRobotTarfihi.com - الروبوتات الترفيهية",
    "IlmRobotKhidmi.com - الروبوتات الخدمية",
    "IlmRobotShakhsi.com - الروبوتات الشخصية",
    "IlmRobotIjtima'i.com - الروبوتات الاجتماعية",
    "IlmRobotMutahrik.com - الروبوتات المتحركة",
    "IlmRobotThabit.com - الروبوتات الثابتة",
    "IlmRobotMutaghayyir.com - الروبوتات المتغيرة",
    "IlmRobotMutakayyif.com - الروبوتات المتكيفة",
    "IlmRobotMarin.com - الروبوتات المرنة",
    "IlmRobotSamid.com - الروبوتات الصامدة",
    "IlmRobotMustadam.com - الروبوتات المستدامة",
    "IlmRobotMustamir.com - الروبوتات المستمرة",
    "IlmRobotKhalid.com - الروبوتات الخالدة",
    "IlmRobotShamil.com - الروبوتات الشاملة",
    "IlmRobotMutlaq.com - الروبوتات المطلقة",
    "IlmRobotLaMahdud.com - الروبوتات اللامحدودة",
    "IlmRobotFawri.com - الروبوتات الفورية",
    "IlmRobotFa'al.com - الروبوتات الفعالة",
    "IlmRobotMuaththir.com - الروبوتات المؤثرة",
    "IlmRobotMuqni.com - الروبوتات المقنعة",
    "IlmRobotMulhim.com - الروبوتات الملهمة",
    "IlmRobotMuhaffiz.com - الروبوتات المحفزة",
    "IlmRobotMushajji.com - الروبوتات المشجعة",
    "IlmRobotDa'im.com - الروبوتات الداعمة",
    "IlmRobotMusanid.com - الروبوتات المساندة",
    "IlmRobotMuwajjih.com - الروبوتات الموجهة",
    "IlmRobotMurshid.com - الروبوتات المرشدة",
    "IlmRobotMudarrib.com - الروبوتات المدربة",
    "IlmRobotMutawwir.com - الروبوتات المطورة",
    "IlmRobotMubdi.com - الروبوتات المبدعة",
    "IlmRobotMubtakir.com - الروبوتات المبتكرة",
    "IlmRobotMutakayyif.com - الروبوتات المتكيفة",
    "IlmRobotMarin.com - الروبوتات المرنة",
    "IlmRobotSamid.com - الروبوتات الصامدة",
    "IlmRobotMustadam.com - الروبوتات المستدامة",
    "IlmRobotMustamir.com - الروبوتات المستمرة",
    "IlmRobotKhalid.com - الروبوتات الخالدة",
    "IlmRobotShamil.com - الروبوتات الشاملة",
    "IlmRobotMutlaq.com - الروبوتات المطلقة",
    "IlmRobotLaMahdud.com - الروبوتات اللامحدودة",

    # ===== 7. علوم التكنولوجيا الحيوية (50) =====
    "IlmBiotec.com - علم التقنية الحيوية",
    "IlmHindasaWarathiyya.com - الهندسة الوراثية",
    "IlmJunum.com - علم الجينوم",
    "IlmBrutin.com - علم البروتين",
    "IlmMetabolom.com - علم الميتابولوم",
    "IlmKhalayaJith'iyya.com - الخلايا الجذعية",
    "IlmTibTajdidi.com - الطب التجديدي",
    "IlmTibShakhsi.com - الطب الشخصي",
    "IlmTibDaqiq.com - الطب الدقيق",
    "IlmTibJini.com - الطب الجيني",
    "IlmTibNanawi.com - الطب النانوي",
    "IlmTibHayawi.com - الطب الحيوي",
    "IlmTibJuzii.com - الطب الجزيئي",
    "IlmTibKhalawi.com - الطب الخلوي",
    "IlmTibManai.com - الطب المناعي",
    "IlmTibTajdidi.com - الطب التجديدي",
    "IlmTibWiqai.com - الطب الوقائي",
    "IlmTibTashkhisi.com - الطب التشخيصي",
    "IlmTibIlaji.com - الطب العلاجي",
    "IlmTibTaahhuli.com - الطب التأهيلي",
    "IlmTibMulatif.com - الطب الملطف",
    "IlmTibShifa'i.com - الطب الشفائي",
    "IlmTibTajribi.com - الطب التجريبي",
    "IlmTibSiriri.com - الطب السريري",
    "IlmTibMukhtabari.com - الطب المختبري",
    "IlmTibAsh'aa'i.com - الطب الإشعاعي",
    "IlmTibSam'i.com - الطب السمعي",
    "IlmTibBasari.com - الطب البصري",
    "IlmTibHaraki.com - الطب الحركي",
    "IlmTibNafsi.com - الطب النفسي",
    "IlmTibIjtima'i.com - الطب الاجتماعي",
    "IlmTibTashghili.com - الطب التشغيلي",
    "IlmTibFada'i.com - الطب الفضائي",
    "IlmTibBahri.com - الطب البحري",
    "IlmTibJawwi.com - الطب الجوي",
    "IlmTibBarri.com - الطب البري",
    "IlmTibSahrawi.com - الطب الصحراوي",
    "IlmTibJabali.com - الطب الجبلي",
    "IlmTibQutbi.com - الطب القطبي",
    "IlmTibIstiwai.com - الطب الاستوائي",
    "IlmTibShamsi.com - الطب الشمسي",
    "IlmTibQamari.com - الطب القمري",
    "IlmTibNajmi.com - الطب النجمي",
    "IlmTibFalaki.com - الطب الفلكي",
    "IlmTibKawni.com - الطب الكوني",
    "IlmTibShamil.com - الطب الشامل",
    "IlmTibMutlaq.com - الطب المطلق",
    "IlmTibLaMahdud.com - الطب اللامحدود",
    "IlmTibFawri.com - الطب الفوري",

    # ===== 8. علوم النانو (50) =====
    "IlmNano.com - علم النانو",
    "IlmNanoMawad.com - نانو المواد",
    "IlmNanoIliktroniyyat.com - نانو الإلكترونيات",
    "IlmNanoBarmaji.com - نانو البرمجيات",
    "IlmNanoTib.com - نانو الطب",
    "IlmNanoTaqa.com - نانو الطاقة",
    "IlmNanoBia.com - نانو البيئة",
    "IlmNanoZira'a.com - نانو الزراعة",
    "IlmNanoSina'a.com - نانو الصناعة",
    "IlmNanoTijara.com - نانو التجارة",
    "IlmNanoTa'lim.com - نانو التعليم",
    "IlmNanoTarfih.com - نانو الترفيه",
    "IlmNanoIttisal.com - نانو الاتصالات",
    "IlmNanoNaql.com - نانو النقل",
    "IlmNanoTakhzin.com - نانو التخزين",
    "IlmNanoTashghil.com - نانو التشغيل",
    "IlmNanoAmn.com - نانو الأمن",
    "IlmNanoTashfir.com - نانو التشفير",
    "IlmNanoTawthiq.com - نانو التوثيق",
    "IlmNanoTashkhis.com - نانو التشخيص",
    "IlmNanoRasad.com - نانو الرصد",
    "IlmNanoTahdid.com - نانو التهديد",
    "IlmNanoHujum.com - نانو الهجوم",
    "IlmNanoDifa.com - نانو الدفاع",
    "IlmNanoSudud.com - نانو الصدود",
    "IlmNanoImtisas.com - نانو الامتصاص",
    "IlmNanoInikas.com - نانو الانعكاس",
    "IlmNanoTahyid.com - نانو التحييد",
    "IlmNanoTajahul.com - نانو التجاهل",
    "IlmNanoFashal.com - نانو الفشل",
    "IlmNanoTahqiq.com - نانو التحقيق",
    "IlmNanoTahlil.com - نانو التحليل",
    "IlmNanoTaqyim.com - نانو التقييم",
    "IlmNanoTahsin.com - نانو التحسين",
    "IlmNanoTatwir.com - نانو التطوير",
    "IlmNanoTahdith.com - نانو التحديث",
    "IlmNanoTajdid.com - نانو التجديد",
    "IlmNanoTarmim.com - نانو الترميم",
    "IlmNanoIslah.com - نانو الإصلاح",
    "IlmNanoShifa.com - نانو الشفاء",
    "IlmNanoIstida.com - نانو الاسترداد",
    "IlmNanoIstiada.com - نانو الاستعادة",
    "IlmNanoBina.com - نانو البناء",
    "IlmNanoTashkil.com - نانو التشكيل",
    "IlmNanoIhya.com - نانو الإحياء",
    "IlmNanoIstiqrar.com - نانو الاستقرار",
    "IlmNanoIstimrar.com - نانو الاستمرار",
    "IlmNanoKhulud.com - نانو الخلود",
    "IlmNanoShumul.com - نانو الشمول",

    # ===== 9. علوم الفضاء (50) =====
    "IlmFada.com - علم الفضاء",
    "IlmFalak.com - علم الفلك",
    "IlmKawakib.com - علم الكواكب",
    "IlmNujum.com - علم النجوم",
    "IlmMajarat.com - علم المجرات",
    "IlmKawn.com - علم الكون",
    "IlmAkwam.com - علم الأكوان",
    "IlmFadaKhariji.com - الفضاء الخارجي",
    "IlmFadaDakhili.com - الفضاء الداخلي",
    "IlmFadaQarib.com - الفضاء القريب",
    "IlmFadaBa'id.com - الفضاء البعيد",
    "IlmFadaWasi.com - الفضاء الواسع",
    "IlmFadaDayyiq.com - الفضاء الضيق",
    "IlmFadaShamil.com - الفضاء الشامل",
    "IlmFadaMutlaq.com - الفضاء المطلق",
    "IlmFadaLaMahdud.com - الفضاء اللامحدود",
    "IlmFadaFawri.com - الفضاء الفوري",
    "IlmFadaFa'al.com - الفضاء الفعال",
    "IlmFadaMuaththir.com - الفضاء المؤثر",
    "IlmFadaMuqni.com - الفضاء المقنع",
    "IlmFadaMulhim.com - الفضاء الملهم",
    "IlmFadaMuhaffiz.com - الفضاء المحفز",
    "IlmFadaMushajji.com - الفضاء المشجع",
    "IlmFadaDa'im.com - الفضاء الداعم",
    "IlmFadaMusanid.com - الفضاء المساند",
    "IlmFadaMuwajjih.com - الفضاء الموجه",
    "IlmFadaMurshid.com - الفضاء المرشد",
    "IlmFadaMudarrib.com - الفضاء المدرب",
    "IlmFadaMutawwir.com - الفضاء المطور",
    "IlmFadaMubdi.com - الفضاء المبدع",
    "IlmFadaMubtakir.com - الفضاء المبتكر",
    "IlmFadaMutakayyif.com - الفضاء المتكيف",
    "IlmFadaMarin.com - الفضاء المرن",
    "IlmFadaSamid.com - الفضاء الصامد",
    "IlmFadaMustadam.com - الفضاء المستدام",
    "IlmFadaMustamir.com - الفضاء المستمر",
    "IlmFadaKhalid.com - الفضاء الخالد",
    "IlmFadaShamil.com - الفضاء الشامل",
    "IlmFadaMutlaq.com - الفضاء المطلق",
    "IlmFadaLaMahdud.com - الفضاء اللامحدود",
    "IlmFadaFawri.com - الفضاء الفوري",
    "IlmFadaFa'al.com - الفضاء الفعال",
    "IlmFadaMuaththir.com - الفضاء المؤثر",
    "IlmFadaMuqni.com - الفضاء المقنع",
    "IlmFadaMulhim.com - الفضاء الملهم",
    "IlmFadaMuhaffiz.com - الفضاء المحفز",
    "IlmFadaMushajji.com - الفضاء المشجع",
    "IlmFadaDa'im.com - الفضاء الداعم",
    "IlmFadaMusanid.com - الفضاء المساند",

    # ===== 10. علوم الطاقة (50) =====
    "IlmTaqa.com - علم الطاقة",
    "IlmTaqaShamsiyya.com - الطاقة الشمسية",
    "IlmTaqaRiyah.com - طاقة الرياح",
    "IlmTaqaMaiyya.com - الطاقة المائية",
    "IlmTaqaNawawiyya.com - الطاقة النووية",
    "IlmTaqaHarariyya.com - الطاقة الحرارية",
    "IlmTaqaKahrabaiyya.com - الطاقة الكهربائية",
    "IlmTaqaKimyaiyya.com - الطاقة الكيميائية",
    "IlmTaqaHayawiyya.com - الطاقة الحيوية",
    "IlmTaqaJuthiyya.com - طاقة الكتلة",
    "IlmTaqaHarakiyya.com - الطاقة الحركية",
    "IlmTaqaKamina.com - الطاقة الكامنة",
    "IlmTaqaDhau'iyya.com - الطاقة الضوئية",
    "IlmTaqaSautiyya.com - الطاقة الصوتية",
    "IlmTaqaMagnatisiyya.com - الطاقة المغناطيسية",
    "IlmTaqaKahraba.com - الطاقة الكهربية",
    "IlmTaqaMutajaddida.com - الطاقة المتجددة",
    "IlmTaqaGhayrMutajaddida.com - الطاقة غير المتجددة",
    "IlmTaqaNazifa.com - الطاقة النظيفة",
    "IlmTaqaKhadra.com - الطاقة الخضراء",
    "IlmTaqaMustadama.com - الطاقة المستدامة",
    "IlmTaqaShamila.com - الطاقة الشاملة",
    "IlmTaqaMutlaqa.com - الطاقة المطلقة",
    "IlmTaqaLaMahduda.com - الطاقة اللامحدودة",
    "IlmTaqaFawriyya.com - الطاقة الفورية",
    "IlmTaqaFa'ala.com - الطاقة الفعالة",
    "IlmTaqaMuaththira.com - الطاقة المؤثرة",
    "IlmTaqaMuqnia.com - الطاقة المقنعة",
    "IlmTaqaMulhima.com - الطاقة الملهمة",
    "IlmTaqaMuhaffiza.com - الطاقة المحفزة",
    "IlmTaqaMushajjia.com - الطاقة المشجعة",
    "IlmTaqaDa'ima.com - الطاقة الداعمة",
    "IlmTaqaMusanida.com - الطاقة المساندة",
    "IlmTaqaMuwajjiha.com - الطاقة الموجهة",
    "IlmTaqaMurshida.com - الطاقة المرشدة",
    "IlmTaqaMudarriba.com - الطاقة المدربة",
    "IlmTaqaMutawwira.com - الطاقة المطورة",
    "IlmTaqaMubdia.com - الطاقة المبدعة",
    "IlmTaqaMubtakira.com - الطاقة المبتكرة",
    "IlmTaqaMutakayyifa.com - الطاقة المتكيفة",
    "IlmTaqaMarina.com - الطاقة المرنة",
    "IlmTaqaSamida.com - الطاقة الصامدة",
    "IlmTaqaMustadama.com - الطاقة المستدامة",
    "IlmTaqaMustamirra.com - الطاقة المستمرة",
    "IlmTaqaKhalida.com - الطاقة الخالدة",
    "IlmTaqaShamila.com - الطاقة الشاملة",
    "IlmTaqaMutlaqa.com - الطاقة المطلقة",
    "IlmTaqaLaMahduda.com - الطاقة اللامحدودة",
    "IlmTaqaFawriyya.com - الطاقة الفورية",
    "IlmTaqaFa'ala.com - الطاقة الفعالة"
]

def display_scientific_tech_part2():
    print("=" * 80)
    print(f"🔬  المكونات العلمية التقنية - الدفعة الثانية ({len(scientific_tech_part2)} مكوّن)  🔬")
    print("=" * 80)
    for i, item in enumerate(scientific_tech_part2, 1):
        print(f"    {i:3d}. {item}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_tech_part2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_tech_part2()
