#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_platforms_200.py - 200 منصة علمية شاملة

scientific_platforms_200 = [
    # ===== 1. المنصات العلمية العامة (20) =====
    "Google Scholar - البحث الأكاديمي الشامل",
    "ResearchGate - شبكة الباحثين",
    "Academia.edu - الأوراق الأكاديمية",
    "Semantic Scholar - البحث الدلالي",
    "Web of Science - قاعدة بيانات الاستشهادات",
    "Scopus - قاعدة البيانات الأكاديمية",
    "PubMed - الطب والعلوم الحيوية",
    "arXiv - الفيزياء والرياضيات",
    "JSTOR - الأرشيف الأكاديمي",
    "ScienceDirect - المجلات العلمية",
    "SpringerLink - الكتب والمجلات",
    "Wiley Online Library - المجلات العلمية",
    "Taylor & Francis - المجلات الأكاديمية",
    "SAGE Journals - المجلات العلمية",
    "Oxford Academic - المجلات الأكاديمية",
    "Cambridge Core - المجلات العلمية",
    "Nature.com - مجلة نيتشر",
    "Science.org - مجلة ساينس",
    "PLOS - المكتبة العامة للعلوم",
    "MDPI - النشر العلمي المفتوح",

    # ===== 2. المنصات الطبية والصحية (20) =====
    "PubMed Central - الطب الحيوي",
    "Medline - الأدبيات الطبية",
    "Cochrane Library - الأدلة الطبية",
    "UpToDate - المعلومات الطبية",
    "WebMD - المعلومات الصحية",
    "Mayo Clinic - المعلومات الطبية",
    "Medscape - التعليم الطبي",
    "BMJ - المجلة الطبية البريطانية",
    "The Lancet - المجلة الطبية",
    "NEJM - مجلة نيو إنجلاند الطبية",
    "JAMA - مجلة الجمعية الطبية الأمريكية",
    "ClinicalTrials.gov - التجارب السريرية",
    "WHO - منظمة الصحة العالمية",
    "CDC - مراكز مكافحة الأمراض",
    "NIH - المعاهد الوطنية للصحة",
    "EMBASE - القاعدة الطبية الأوروبية",
    "CINAHL - التمريض والصحة",
    "PsycINFO - علم النفس",
    "Dentistry Journal - طب الأسنان",
    "Pharmacy Journal - الصيدلة",

    # ===== 3. المنصات الكيميائية والفيزيائية (20) =====
    "ACS Publications - الجمعية الكيميائية الأمريكية",
    "RSC - الجمعية الملكية للكيمياء",
    "ChemSpider - قاعدة البيانات الكيميائية",
    "PubChem - المركبات الكيميائية",
    "ChemDraw - الرسم الكيميائي",
    "IOPscience - معهد الفيزياء",
    "APS Journals - الجمعية الفيزيائية الأمريكية",
    "AIP Publishing - المعهد الأمريكي للفيزياء",
    "Physical Review - المراجعة الفيزيائية",
    "Chemical Abstracts - الملخصات الكيميائية",
    "Reaxys - الكيمياء العضوية",
    "SciFinder - البحث الكيميائي",
    "Periodic Table - الجدول الدوري",
    "NIST - المعايير والقياسات",
    "CERN - المنظمة الأوروبية للأبحاث النووية",
    "Fermilab - مختبر فيرمي",
    "Los Alamos - مختبر لوس ألاموس",
    "Oak Ridge - مختبر أوك ريدج",
    "Argonne - مختبر أرغون",
    "Brookhaven - مختبر بروكهافن",

    # ===== 4. المنصات البيولوجية والجينية (20) =====
    "NCBI - المركز الوطني لمعلومات التقنية الحيوية",
    "GenBank - بنك الجينات",
    "BLAST - البحث في التسلسلات",
    "UniProt - قاعدة البروتينات",
    "PDB - بنك بيانات البروتينات",
    "EMBL-EBI - المعهد الأوروبي للمعلومات الحيوية",
    "Ensembl - قاعدة الجينوم",
    "UCSC Genome Browser - متصفح الجينوم",
    "KEGG - موسوعة الجينات والجينومات",
    "Gene Ontology - أنطولوجيا الجينات",
    "BioCyc - المسارات الأيضية",
    "Reactome - المسارات الحيوية",
    "STRING - تفاعلات البروتينات",
    "DDBJ - بنك البيانات الياباني",
    "ExPASy - بوابة المعلومات الحيوية",
    "SWISS-MODEL - نمذجة البروتينات",
    "Phylogeny.fr - تحليل التطور",
    "Tree of Life - شجرة الحياة",
    "Biodiversity Heritage Library - مكتبة التنوع الحيوي",
    "iNaturalist - مراقبة الطبيعة",

    # ===== 5. المنصات الفلكية والفضائية (20) =====
    "NASA - وكالة الفضاء الأمريكية",
    "ESA - وكالة الفضاء الأوروبية",
    "JAXA - وكالة الفضاء اليابانية",
    "Roscosmos - وكالة الفضاء الروسية",
    "CNSA - وكالة الفضاء الصينية",
    "ISRO - وكالة الفضاء الهندية",
    "SpaceX - سبيس إكس",
    "Blue Origin - بلو أوريجين",
    "Hubble Site - تلسكوب هابل",
    "James Webb - تلسكوب جيمس ويب",
    "Chandra - تلسكوب تشاندرا",
    "Spitzer - تلسكوب سبيتزر",
    "Kepler - مهمة كبلر",
    "TESS - مهمة تيس",
    "Gaia - مهمة جايا",
    "LIGO - مرصد الموجات الثقالية",
    "Event Horizon - تلسكوب أفق الحدث",
    "Sky & Telescope - مجلة الفلك",
    "Astronomy.com - مجلة علم الفلك",
    "Space.com - أخبار الفضاء",

    # ===== 6. المنصات البيئية والجيولوجية (20) =====
    "IPCC - الهيئة الحكومية لتغير المناخ",
    "UNEP - برنامج الأمم المتحدة للبيئة",
    "NOAA - الإدارة الوطنية للمحيطات والغلاف الجوي",
    "USGS - هيئة المسح الجيولوجي الأمريكية",
    "EPA - وكالة حماية البيئة",
    "WWF - الصندوق العالمي للطبيعة",
    "Greenpeace - منظمة السلام الأخضر",
    "Conservation International - الحفظ الدولي",
    "Nature Conservancy - المحافظة على الطبيعة",
    "Earth Observatory - مرصد الأرض",
    "Climate.gov - بوابة المناخ",
    "Carbon Brief - أخبار المناخ",
    "GeoScienceWorld - العلوم الجيولوجية",
    "SEPM - الجيولوجيا الرسوبية",
    "GSA - الجمعية الجيولوجية الأمريكية",
    "EGU - الاتحاد الأوروبي للجيولوجيا",
    "AGU - الاتحاد الجيوفيزيائي الأمريكي",
    "WMO - المنظمة العالمية للأرصاد",
    "UNFCCC - اتفاقية الأمم المتحدة للمناخ",
    "IUCN - الاتحاد الدولي لحفظ الطبيعة",

    # ===== 7. المنصات التقنية والحاسوبية (20) =====
    "IEEE Xplore - الهندسة الكهربائية",
    "ACM Digital Library - علوم الحاسوب",
    "GitHub - مستودعات البرمجيات",
    "Stack Overflow - مجتمع البرمجة",
    "CodePen - تطوير الويب",
    "Kaggle - علوم البيانات",
    "Coursera - التعليم التقني",
    "edX - التعليم التقني",
    "Udacity - التعليم التقني",
    "Codecademy - تعلم البرمجة",
    "LeetCode - تحديات البرمجة",
    "HackerRank - تحديات البرمجة",
    "Codeforces - مسابقات البرمجة",
    "TopCoder - مسابقات البرمجة",
    "PyPI - مكتبات بايثون",
    "npm - مكتبات جافاسكريبت",
    "Maven - مكتبات جافا",
    "Docker Hub - حاويات دوكر",
    "Kubernetes - إدارة الحاويات",
    "TensorFlow - التعلم الآلي",

    # ===== 8. المنصات الرياضية والإحصائية (20) =====
    "MathSciNet - المراجعات الرياضية",
    "Zentralblatt MATH - الملخصات الرياضية",
    "Wolfram Alpha - المحرك الحسابي",
    "MathWorld - موسوعة الرياضيات",
    "Project Euler - تحديات رياضية",
    "MathOverflow - أسئلة الرياضيات",
    "Statistics.com - الإحصاء",
    "R Project - لغة R الإحصائية",
    "SAS - التحليلات الإحصائية",
    "SPSS - التحليل الإحصائي",
    "Stata - الإحصاء",
    "MATLAB - الحوسبة الرياضية",
    "Mathematica - الحوسبة الرمزية",
    "Maple - الرياضيات الرمزية",
    "GeoGebra - الرياضيات التفاعلية",
    "Desmos - الرسوم البيانية",
    "Numberphile - فيديوهات رياضية",
    "3Blue1Brown - فيديوهات رياضية",
    "Khan Academy Math - تعليم الرياضيات",
    "Brilliant.org - تعليم الرياضيات",

    # ===== 9. المنصات الإنسانية والاجتماعية (20) =====
    "JSTOR - العلوم الإنسانية",
    "Project MUSE - العلوم الإنسانية",
    "SSRN - العلوم الاجتماعية",
    "SocArXiv - العلوم الاجتماعية",
    "PhilPapers - الفلسفة",
    "Stanford Encyclopedia - موسوعة ستانفورد",
    "Internet Encyclopedia - موسوعة الإنترنت",
    "HathiTrust - المكتبة الرقمية",
    "Internet Archive - الأرشيف الرقمي",
    "Digital Public Library - المكتبة العامة الرقمية",
    "Europeana - التراث الأوروبي",
    "World Digital Library - المكتبة الرقمية العالمية",
    "Google Arts & Culture - الفنون والثقافة",
    "Artstor - الفنون البصرية",
    "IMDb - قاعدة بيانات الأفلام",
    "MusicBrainz - قاعدة بيانات الموسيقى",
    "Discogs - قاعدة بيانات التسجيلات",
    "Goodreads - قاعدة بيانات الكتب",
    "Library of Congress - مكتبة الكونغرس",
    "British Library - المكتبة البريطانية",

    # ===== 10. المنصات التعليمية المفتوحة (20) =====
    "Khan Academy - التعليم المجاني",
    "Coursera - الدورات الجامعية",
    "edX - الدورات الجامعية",
    "Udemy - الدورات المهنية",
    "Udacity - الدورات التقنية",
    "MIT OpenCourseWare - مناهج MIT المفتوحة",
    "OpenStax - الكتب المفتوحة",
    "OER Commons - الموارد التعليمية المفتوحة",
    "MERLOT - الموارد التعليمية",
    "OpenLearn - الجامعة المفتوحة",
    "FutureLearn - الدورات البريطانية",
    "Saylor Academy - التعليم المجاني",
    "Alison - الدورات المجانية",
    "Canvas Network - الدورات المفتوحة",
    "Open Yale Courses - مناهج ييل المفتوحة",
    "Harvard Online - دورات هارفارد",
    "Stanford Online - دورات ستانفورد",
    "Oxford Online - دورات أكسفورد",
    "Cambridge Online - دورات كامبريدج",
    "TED-Ed - الدروس التعليمية"
]

def display_scientific_platforms():
    print("=" * 80)
    print(f"📚  المنصات العلمية الشاملة ({len(scientific_platforms_200)} منصة)  📚")
    print("=" * 80)
    for i, platform in enumerate(scientific_platforms_200, 1):
        print(f"    {i:3d}. {platform}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_platforms_200)} منصة")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_platforms()
