#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_platforms_extra2.py - الدفعة الثانية: 200 منصة علمية إضافية

scientific_platforms_extra2 = [
    # ===== 1. منصات علم النفس (20) =====
    "APA PsycNet - شبكة علم النفس الأمريكية",
    "PsychINFO - قاعدة علم النفس",
    "Psychology Today - مجلة علم النفس اليوم",
    "Simply Psychology - علم النفس المبسط",
    "Verywell Mind - عقل سليم جدًا",
    "PsyArXiv - أرشيف علم النفس",
    "Open Psychology - علم النفس المفتوح",
    "Frontiers in Psychology - حدود علم النفس",
    "Journal of Psychology - مجلة علم النفس",
    "Psychological Science - العلوم النفسية",
    "BPS - الجمعية البريطانية لعلم النفس",
    "APS - جمعية العلوم النفسية",
    "SPSP - علم النفس الاجتماعي والشخصية",
    "SCCR - علم النفس المعرفي والسريري",
    "Div12 - علم النفس السريري",
    "SFU Psychology - علم النفس جامعة سايمون فريزر",
    "Yale Psychology - علم النفس بجامعة ييل",
    "Harvard Psychology - علم النفس بجامعة هارفارد",
    "Stanford Psychology - علم النفس بجامعة ستانفورد",
    "MIT Psychology - علم النفس بمعهد ماساتشوستس",

    # ===== 2. منصات علم الاجتماع (20) =====
    "ASA - الجمعية الأمريكية لعلم الاجتماع",
    "BSA - الجمعية البريطانية لعلم الاجتماع",
    "ISA - الجمعية الدولية لعلم الاجتماع",
    "Sociology Compass - مجلة علم الاجتماع",
    "Social Forces - القوى الاجتماعية",
    "American Sociological Review - المراجعة الاجتماعية الأمريكية",
    "SocArXiv - أرشيف علم الاجتماع",
    "SSRN Sociology - أبحاث علم الاجتماع",
    "Social Science Research Network - شبكة بحوث العلوم الاجتماعية",
    "Sociological Science - العلوم الاجتماعية",
    "Contexts - مجلة السياقات",
    "Annual Review of Sociology - المراجعة السنوية لعلم الاجتماع",
    "Oxford Sociology - أكسفورد لعلم الاجتماع",
    "Cambridge Sociology - كامبريدج لعلم الاجتماع",
    "Harvard Sociology - هارفارد لعلم الاجتماع",
    "Yale Sociology - ييل لعلم الاجتماع",
    "Princeton Sociology - برينستون لعلم الاجتماع",
    "Columbia Sociology - كولومبيا لعلم الاجتماع",
    "Berkeley Sociology - بيركلي لعلم الاجتماع",
    "Chicago Sociology - شيكاغو لعلم الاجتماع",

    # ===== 3. منصات العلوم السياسية (20) =====
    "APSA - الجمعية الأمريكية للعلوم السياسية",
    "PSA - الجمعية السياسية البريطانية",
    "ISA - الجمعية الدولية للدراسات السياسية",
    "Political Science Quarterly - ربع سنوية العلوم السياسية",
    "Journal of Politics - مجلة السياسة",
    "American Political Science Review - المراجعة السياسية الأمريكية",
    "SSRN Politics - أبحاث العلوم السياسية",
    "Polity - مجلة بوليتي",
    "Political Studies - الدراسات السياسية",
    "World Politics - السياسة العالمية",
    "Comparative Politics - السياسة المقارنة",
    "International Organization - المنظمة الدولية",
    "Foreign Affairs - الشؤون الخارجية",
    "Foreign Policy - السياسة الخارجية",
    "National Interest - المصلحة الوطنية",
    "The Diplomat - الدبلوماسي",
    "Brookings - معهد بروكينغز",
    "Chatham House - تشاتام هاوس",
    "RAND Corporation - مؤسسة راند",
    "Council on Foreign Relations - مجلس العلاقات الخارجية",

    # ===== 4. منصات التعليم (20) =====
    "ERIC - مركز معلومات الموارد التعليمية",
    "Education Resources - الموارد التعليمية",
    "JSTOR Education - التعليم",
    "Taylor & Francis Education - التعليم",
    "Springer Education - التعليم",
    "Educational Researcher - الباحث التربوي",
    "Review of Educational Research - مراجعة البحوث التربوية",
    "American Educational Research Association - جمعية البحوث التربوية",
    "NEA - الجمعية الوطنية للتعليم",
    "AFT - الاتحاد الأمريكي للمعلمين",
    "UNESCO Education - اليونسكو للتعليم",
    "World Bank Education - البنك الدولي للتعليم",
    "OECD Education - منظمة التعاون للتعليم",
    "Edutopia - إيدوتوبيا",
    "TeachThought - فكر التدريس",
    "Education Week - أسبوع التعليم",
    "EdSurge - إيدسيرج",
    "Inside Higher Ed - داخل التعليم العالي",
    "Chronicle of Higher Education - كرونيكل التعليم العالي",
    "Times Higher Education - تايمز للتعليم العالي",

    # ===== 5. منصات علوم الحاسوب (20) =====
    "ACM Digital Library - مكتبة ACM الرقمية",
    "IEEE Xplore - IEEE",
    "CiteSeerX - سايت سير",
    "DBLP - DBLP لعلوم الحاسوب",
    "arXiv CS - أرشيف علوم الحاسوب",
    "Google AI - أبحاث جوجل للذكاء الاصطناعي",
    "DeepMind - ديب مايند",
    "OpenAI - أوبن إيه آي",
    "Anthropic - أنثروبيك",
    "Microsoft Research - أبحاث مايكروسوفت",
    "IBM Research - أبحاث آي بي إم",
    "Facebook AI Research - أبحاث فيسبوك للذكاء الاصطناعي",
    "Stanford CS - علوم الحاسوب بجامعة ستانفورد",
    "MIT CS - علوم الحاسوب بمعهد ماساتشوستس",
    "Berkeley CS - علوم الحاسوب بجامعة بيركلي",
    "CMU CS - علوم الحاسوب بجامعة كارنيجي ميلون",
    "Oxford CS - علوم الحاسوب بجامعة أكسفورد",
    "Cambridge CS - علوم الحاسوب بجامعة كامبريدج",
    "GitHub - جيت هاب",
    "Stack Overflow - ستاك أوفرفلو",

    # ===== 6. منصات الفيزياء (20) =====
    "Physical Review Journals - مجلات المراجعة الفيزيائية",
    "APS Physics - الفيزياء الأمريكية",
    "IOPscience - معهد الفيزياء",
    "AIP Publishing - النشر الفيزيائي الأمريكي",
    "arXiv Physics - أرشيف الفيزياء",
    "Physics Today - الفيزياء اليوم",
    "Phys.org - الفيزياء",
    "Physics World - عالم الفيزياء",
    "CERN - سيرن",
    "Fermilab - فيرميلاب",
    "SLAC - مركز ستانفورد للمسرع الخطي",
    "Brookhaven - بروكهافن",
    "Los Alamos - لوس ألاموس",
    "Oak Ridge - أوك ريدج",
    "Argonne - أرغون",
    "Lawrence Berkeley - لورنس بيركلي",
    "Max Planck - ماكس بلانك",
    "CNRS Physics - المركز الوطني الفرنسي",
    "NIST Physics - المعهد الوطني للمعايير",
    "Physics Forums - منتديات الفيزياء",

    # ===== 7. منصات الكيمياء (20) =====
    "ACS Publications - منشورات الجمعية الكيميائية الأمريكية",
    "RSC - الجمعية الملكية للكيمياء",
    "ChemSpider - كيم سبايدر",
    "PubChem - بوب كيم",
    "Reaxys - رياكسيس",
    "SciFinder - ساي فايندر",
    "Chemistry World - عالم الكيمياء",
    "ChemRxiv - كيم ركسيف",
    "Organic Chemistry Portal - بوابة الكيمياء العضوية",
    "Chemical & Engineering News - أخبار الكيمياء والهندسة",
    "Chemistry Europe - كيمياء أوروبا",
    "Royal Society Chemistry - الجمعية الملكية للكيمياء",
    "American Chemical Society - الجمعية الكيميائية الأمريكية",
    "IUPAC - الاتحاد الدولي للكيمياء البحتة والتطبيقية",
    "ChemTube3D - كيم تيوب ثلاثي الأبعاد",
    "Periodic Videos - فيديوهات الجدول الدوري",
    "Chemguide - دليل الكيمياء",
    "Chemistry LibreTexts - نصوص الكيمياء",
    "MIT Chemistry - كيمياء MIT",
    "Stanford Chemistry - كيمياء ستانفورد",

    # ===== 8. منصات علم الأحياء (20) =====
    "Nature Biology - نيتشر للأحياء",
    "Cell - مجلة الخلية",
    "Journal of Molecular Biology - مجلة الأحياء الجزيئية",
    "BioRxiv - بايو ركسيف",
    "PubMed Biology - بب ميد للأحياء",
    "NCBI - المركز الوطني لمعلومات التقنية الحيوية",
    "EMBL - المختبر الأوروبي للبيولوجيا الجزيئية",
    "Sanger Institute - معهد سانجر",
    "Broad Institute - معهد برود",
    "Howard Hughes Medical Institute - معهد هوارد هيوز الطبي",
    "Biology LibreTexts - نصوص الأحياء",
    "BioMed Central - بيو ميد سنترال",
    "PLOS Biology - بلوس للأحياء",
    "Frontiers in Biology - حدود الأحياء",
    "Oxford Biology - أكسفورد للأحياء",
    "Cambridge Biology - كامبريدج للأحياء",
    "Harvard Biology - هارفارد للأحياء",
    "Stanford Biology - ستانفورد للأحياء",
    "MIT Biology - MIT للأحياء",
    "Berkeley Biology - بيركلي للأحياء",

    # ===== 9. منصات الطب (20) =====
    "The Lancet - اللانسيت",
    "NEJM - مجلة نيو إنجلاند الطبية",
    "JAMA - مجلة الجمعية الطبية الأمريكية",
    "BMJ - المجلة الطبية البريطانية",
    "Annals of Internal Medicine - حوليات الطب الباطني",
    "Nature Medicine - نيتشر للطب",
    "Cell Medicine - خلية للطب",
    "Mayo Clinic Proceedings - إجراءات مايو كلينيك",
    "Cochrane Library - مكتبة كوكرين",
    "PubMed - بب ميد",
    "Medscape - ميدسكيب",
    "WebMD - ويب إم دي",
    "UpToDate - أب تو ديت",
    "ClinicalKey - كلينيكال كي",
    "AccessMedicine - أكسيس ميديسن",
    "Harrison's Online - هاريسون أونلاين",
    "MD Anderson - إم دي أندرسون",
    "Johns Hopkins Medicine - جونز هوبكنز للطب",
    "Mayo Clinic - مايو كلينيك",
    "Cleveland Clinic - كليفلاند كلينيك",

    # ===== 10. منصات الرياضيات والإحصاء (20) =====
    "MathSciNet - قاعدة المراجعات الرياضية",
    "Zentralblatt MATH - الملخصات الرياضية",
    "arXiv Math - أرشيف الرياضيات",
    "Wolfram Alpha - ولفرام ألفا",
    "MathWorld - عالم الرياضيات",
    "Project Euler - مشروع أويلر",
    "Khan Academy Math - أكاديمية خان للرياضيات",
    "Brilliant.org - بريليانت",
    "Art of Problem Solving - فن حل المشكلات",
    "Desmos - ديسموس",
    "GeoGebra - جيوجبرا",
    "Statistics.com - إحصاء دوت كوم",
    "R Project - مشروع R",
    "SAS - ساس",
    "SPSS - سبسس",
    "Stata - ستاتا",
    "MATLAB - ماتلاب",
    "Mathematica - ماثيماتيكا",
    "Maple - مابل",
    "MathOverflow - ماث أوفرفلو"
]

def display_scientific_platforms_extra2():
    print("=" * 80)
    print(f"📚  المنصات العلمية الإضافية - الدفعة الثانية ({len(scientific_platforms_extra2)} منصة)  📚")
    print("=" * 80)
    for i, platform in enumerate(scientific_platforms_extra2, 1):
        print(f"    {i:3d}. {platform}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_platforms_extra2)}")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_platforms_extra2()
