#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_platforms_extra3.py - الدفعة الثالثة: 200 منصة علمية إضافية

scientific_platforms_extra3 = [
    # ===== 1. منصات الذكاء الاصطناعي (20) =====
    "OpenAI - أوبن إيه آي",
    "DeepMind - ديب مايند",
    "Anthropic - أنثروبيك",
    "Hugging Face - هاغينغ فيس",
    "Kaggle AI - كاغل للذكاء الاصطناعي",
    "Papers with Code - أوراق مع كود",
    "arXiv AI - أرشيف الذكاء الاصطناعي",
    "TensorFlow - تنسرفلو",
    "PyTorch - باي تورش",
    "Keras - كيراس",
    "Scikit-learn - سايكيت ليرن",
    "OpenCV - أوبن سي في",
    "NVIDIA AI - إنفيديا",
    "IBM Watson - آي بي إم واتسون",
    "Microsoft AI - مايكروسوفت للذكاء الاصطناعي",
    "Google AI - جوجل للذكاء الاصطناعي",
    "Amazon AI - أمازون للذكاء الاصطناعي",
    "Apple AI - أبل للذكاء الاصطناعي",
    "Meta AI - ميتا للذكاء الاصطناعي",
    "Baidu AI - بايدو للذكاء الاصطناعي",

    # ===== 2. منصات علوم البيانات (20) =====
    "Kaggle - كاغل",
    "DataCamp - داتاكامب",
    "Data.gov - بيانات الحكومة",
    "Data.world - داتا وورلد",
    "UCI Machine Learning - يو سي آي للتعلم الآلي",
    "Data.gov.uk - بيانات المملكة المتحدة",
    "European Data Portal - بوابة البيانات الأوروبية",
    "AWS Open Data - بيانات أوبن داتا",
    "Google Dataset Search - بحث جوجل للبيانات",
    "FiveThirtyEight - فايف ثيرتي إيت",
    "BuzzFeed News Data - بيانات بازفيد",
    "NASA Open Data - بيانات ناسا المفتوحة",
    "WHO Data - بيانات منظمة الصحة",
    "World Bank Data - بيانات البنك الدولي",
    "IMF Data - بيانات صندوق النقد",
    "OECD Data - بيانات منظمة التعاون",
    "UN Data - بيانات الأمم المتحدة",
    "EU Open Data - بيانات الاتحاد الأوروبي",
    "GitHub Data - بيانات جيت هاب",
    "Tableau Public - تابلوه ببليك",

    # ===== 3. منصات الأمن السيبراني (20) =====
    "SANS Institute - معهد سانس",
    "NIST Cybersecurity - الأمن السيبراني NIST",
    "OWASP - أواسب",
    "CVE - قاعدة الثغرات",
    "CERT - مركز الاستجابة للطوارئ",
    "ISC2 - جمعية الأمن السيبراني",
    "ISACA - إيزاكا",
    "Cybrary - سيبراري",
    "Hack The Box - هاك ذا بوكس",
    "TryHackMe - تراي هاك مي",
    "Bugcrowd - باغ كراود",
    "HackerOne - هاكر وان",
    "Cybersecurity Ventures - مشاريع الأمن السيبراني",
    "Dark Reading - دارك ريدينغ",
    "Krebs on Security - كريبس للأمن",
    "Schneier on Security - شناير للأمن",
    "The Hacker News - أخبار الهاكر",
    "Bleeping Computer - بليبيغ كومبيوتر",
    "SecurityWeek - أسبوع الأمن",
    "Infosecurity Magazine - مجلة الأمن المعلوماتي",

    # ===== 4. منصات البلوكشين (20) =====
    "Bitcoin.org - بيتكوين",
    "Ethereum.org - إيثيريوم",
    "Coinbase - كوين بيز",
    "Binance - باينانس",
    "CoinMarketCap - كوين ماركت كاب",
    "CoinGecko - كوين جيكو",
    "Blockchain.com - بلوكشين",
    "CryptoCompare - كريبتو كومبير",
    "CryptoSlate - كريبتو سليت",
    "CoinDesk - كوين ديسك",
    "Cointelegraph - كوين تيليغراف",
    "DeFi Pulse - ديفي بالس",
    "Uniswap - يونيسواب",
    "Aave - آيف",
    "Compound - كومباوند",
    "MakerDAO - ميكر داو",
    "Chainlink - تشين لينك",
    "Polkadot - بولكادوت",
    "Cardano - كاردانو",
    "Solana - سولانا",

    # ===== 5. منصات الفضاء (20) =====
    "NASA - ناسا",
    "SpaceX - سبيس إكس",
    "Blue Origin - بلو أوريجين",
    "Virgin Galactic - فيرجن غالاكتيك",
    "Boeing Space - بوينغ للفضاء",
    "Lockheed Martin Space - لوكهيد مارتن للفضاء",
    "Northrop Grumman - نورثروب غرومان",
    "Arianespace - أريان سبيس",
    "Roscosmos - روسكوسموس",
    "JAXA - جاكسا",
    "CNSA - وكالة الفضاء الصينية",
    "ISRO - إسرو",
    "ESA - إيسا",
    "Space.com - سبيس دوت كوم",
    "Space News - أخبار الفضاء",
    "Universe Today - الكون اليوم",
    "Sky & Telescope - السماء والتلسكوب",
    "Astronomy Magazine - مجلة الفلك",
    "Planetary Society - الجمعية الكوكبية",
    "International Space Station - محطة الفضاء الدولية",

    # ===== 6. منصات الطاقة (20) =====
    "IEA - الوكالة الدولية للطاقة",
    "IRENA - الوكالة الدولية للطاقة المتجددة",
    "DOE Energy - وزارة الطاقة الأمريكية",
    "NREL - المختبر الوطني للطاقة المتجددة",
    "Energy.gov - وزارة الطاقة",
    "World Energy Council - مجلس الطاقة العالمي",
    "Energy Policy - مجلة سياسة الطاقة",
    "Renewable Energy - مجلة الطاقة المتجددة",
    "Solar Energy - مجلة الطاقة الشمسية",
    "Wind Energy - مجلة طاقة الرياح",
    "Nuclear Energy - مجلة الطاقة النووية",
    "Hydrogen Energy - مجلة طاقة الهيدروجين",
    "Biomass Energy - مجلة طاقة الكتلة الحيوية",
    "Geothermal Energy - مجلة الطاقة الحرارية الأرضية",
    "Energy Storage - مجلة تخزين الطاقة",
    "Smart Grid - مجلة الشبكة الذكية",
    "Carbon Brief Energy - كربون بريف للطاقة",
    "Renewable Energy World - عالم الطاقة المتجددة",
    "Green Tech Media - غرين تك ميديا",
    "Energy Central - سنترال الطاقة",

    # ===== 7. منصات البيئة (20) =====
    "UNEP - برنامج الأمم المتحدة للبيئة",
    "IPCC - الهيئة الحكومية لتغير المناخ",
    "WWF - الصندوق العالمي للطبيعة",
    "Greenpeace - غرينبيس",
    "Conservation International - الحفظ الدولي",
    "Nature Conservancy - المحافظة على الطبيعة",
    "IUCN - الاتحاد الدولي لحفظ الطبيعة",
    "Friends of the Earth - أصدقاء الأرض",
    "Earth Justice - عدالة الأرض",
    "Sierra Club - نادي سييرا",
    "Greenpeace USA - غرينبيس أمريكا",
    "350.org - 350",
    "Climate Reality - حقيقة المناخ",
    "Earth Day Network - شبكة يوم الأرض",
    "World Wildlife Fund - الصندوق العالمي للطبيعة",
    "Environmental Defense Fund - صندوق الدفاع البيئي",
    "Natural Resources Defense Council - مجلس الدفاع عن الموارد",
    "Rainforest Alliance - تحالف الغابات المطيرة",
    "Ocean Conservancy - المحافظة على المحيطات",
    "Clean Water Action - عمل المياه النظيفة",

    # ===== 8. منصات الزراعة (20) =====
    "FAO - منظمة الأغذية والزراعة",
    "USDA - وزارة الزراعة الأمريكية",
    "Agriculture.com - الزراعة",
    "AgWeb - أج ويب",
    "Farm Journal - مجلة المزرعة",
    "AgriBusiness - الأعمال الزراعية",
    "CropLife - حياة المحاصيل",
    "Agronomy Journal - مجلة الزراعة العلمية",
    "Field Crops Research - أبحاث المحاصيل",
    "Soil Science - علم التربة",
    "Plant Pathology - علم أمراض النبات",
    "Entomology - علم الحشرات",
    "AgriTech - التكنولوجيا الزراعية",
    "Precision Ag - الزراعة الدقيقة",
    "Smart Farming - الزراعة الذكية",
    "Vertical Farming - الزراعة العمودية",
    "Hydroponics - الزراعة المائية",
    "Aquaponics - الزراعة المائية السمكية",
    "Organic Farming - الزراعة العضوية",
    "Sustainable Agriculture - الزراعة المستدامة",

    # ===== 9. منصات الصناعة (20) =====
    "Industry Week - أسبوع الصناعة",
    "Manufacturing.net - التصنيع",
    "Industry Today - الصناعة اليوم",
    "Automation World - عالم الأتمتة",
    "Control Engineering - هندسة التحكم",
    "Plant Engineering - هندسة المصانع",
    "Material Handling - معالجة المواد",
    "Assembly Magazine - مجلة التجميع",
    "Quality Magazine - مجلة الجودة",
    "Industrial Maintenance - الصيانة الصناعية",
    "Smart Manufacturing - التصنيع الذكي",
    "Industry 4.0 - الصناعة 4.0",
    "Lean Manufacturing - التصنيع الرشيق",
    "Six Sigma - ستة سيجما",
    "ISO Standards - معايير ISO",
    "ASTM - الجمعية الأمريكية للاختبارات",
    "ANSI - المعهد الأمريكي للمعايير",
    "NIST Manufacturing - التصنيع NIST",
    "SME - جمعية مهندسي التصنيع",
    "Manufacturing Leadership - قيادة التصنيع",

    # ===== 10. منصات النقل (20) =====
    "DOT - وزارة النقل الأمريكية",
    "Transportation Research - أبحاث النقل",
    "ITS - النقل الذكي",
    "Mobility Lab - مختبر التنقل",
    "Transit Cooperative - النقل التعاوني",
    "Smart Transportation - النقل الذكي",
    "Autonomous Vehicles - المركبات الذاتية",
    "Electric Vehicles - المركبات الكهربائية",
    "High Speed Rail - السكك الحديدية السريعة",
    "Urban Mobility - التنقل الحضري",
    "Logistics Management - إدارة اللوجستيات",
    "Supply Chain - سلسلة التوريد",
    "Freight Transport - نقل البضائع",
    "Passenger Transport - نقل الركاب",
    "Air Transport - النقل الجوي",
    "Sea Transport - النقل البحري",
    "Land Transport - النقل البري",
    "Rail Transport - النقل بالسكك",
    "Pipeline Transport - النقل بالأنابيب",
    "Intermodal Transport - النقل المتعدد الوسائط"
]

def display_scientific_platforms_extra3():
    print("=" * 80)
    print(f"📚  المنصات العلمية الإضافية - الدفعة الثالثة ({len(scientific_platforms_extra3)} منصة)  📚")
    print("=" * 80)
    for i, platform in enumerate(scientific_platforms_extra3, 1):
        print(f"    {i:3d}. {platform}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_platforms_extra3)}")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_platforms_extra3()
