#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scientific_platforms_extra1.py - الدفعة الأولى: 200 منصة علمية إضافية

scientific_platforms_extra1 = [
    # ===== 1. منصات الهندسة (20) =====
    "ASCE - الجمعية الأمريكية للمهندسين المدنيين",
    "ASME - الجمعية الأمريكية للمهندسين الميكانيكيين",
    "IEEE - معهد مهندسي الكهرباء والإلكترونيات",
    "AICHE - المعهد الأمريكي للمهندسين الكيميائيين",
    "SAE - جمعية مهندسي السيارات",
    "ASHRAE - جمعية التدفئة والتبريد",
    "ASM International - جمعية المواد",
    "SPE - جمعية مهندسي البترول",
    "AISC - المعهد الأمريكي للإنشاءات الفولاذية",
    "ACI - المعهد الأمريكي للخرسانة",
    "Engineering.com - بوابة الهندسة",
    "Engineering360 - مجتمع الهندسة",
    "IHS Engineering - مكتبة الهندسة",
    "ENGnetBASE - قاعدة كتب الهندسة",
    "Knovel - مرجع الهندسة",
    "AccessEngineering - مكتبة الهندسة",
    "ASEE - جمعية تعليم الهندسة",
    "NSF Engineering - المؤسسة الوطنية للهندسة",
    "Engineering Village - منصة الهندسة",
    "MatWeb - قاعدة بيانات المواد",

    # ===== 2. منصات الاقتصاد (20) =====
    "RePEc - أبحاث الاقتصاد",
    "IDEAS - قاعدة الاقتصاد",
    "NBER - المكتب الوطني للبحوث الاقتصادية",
    "CEPR - مركز البحوث الاقتصادية",
    "IMF - صندوق النقد الدولي",
    "World Bank - البنك الدولي",
    "OECD - منظمة التعاون الاقتصادي",
    "Federal Reserve - الاحتياطي الفيدرالي",
    "ECB - البنك المركزي الأوروبي",
    "BIS - بنك التسويات الدولية",
    "EconLit - قاعدة الأدبيات الاقتصادية",
    "SSRN Economics - أبحاث الاقتصاد",
    "Google Finance - المالية",
    "Yahoo Finance - المالية",
    "Bloomberg - بلومبرغ",
    "Reuters - رويترز",
    "Economist - مجلة الإيكونوميست",
    "Financial Times - فاينانشال تايمز",
    "Forbes - فوربس",
    "Business Insider - بيزنس إنسايدر",

    # ===== 3. منصات القانون (20) =====
    "Westlaw - قاعدة القانون",
    "LexisNexis - قاعدة القانون",
    "HeinOnline - المكتبة القانونية",
    "JSTOR Law - القانون",
    "Oxford Legal - أكسفورد القانونية",
    "Cambridge Law - كامبريدج القانونية",
    "SSRN Legal - أبحاث القانون",
    "Law.com - بوابة القانون",
    "FindLaw - القانون للمحترفين",
    "Justia - القانون والمعلومات",
    "ABA - نقابة المحامين الأمريكية",
    "ICLR - تقارير القانون",
    "ECHR - المحكمة الأوروبية",
    "UN Treaty - معاهدات الأمم المتحدة",
    "WIPO - الملكية الفكرية",
    "USPTO - براءات الاختراع",
    "EUPO - براءات الاختراع الأوروبية",
    "LegalTrac - فهرس القانون",
    "Index to Legal Periodicals - فهرس الدوريات",
    "BAILII - معهد المعلومات القانونية",

    # ===== 4. منصات الفنون (20) =====
    "Artstor - الفنون البصرية",
    "Google Arts & Culture - الفنون",
    "WikiArt - موسوعة الفنون",
    "Art History Resources - تاريخ الفن",
    "The Art Newspaper - صحيفة الفن",
    "Artforum - مجلة الفن",
    "Tate - تيت",
    "MoMA - متحف الفن الحديث",
    "Louvre - اللوفر",
    "Met Museum - متحف المتروبوليتان",
    "Getty - جيتي",
    "Smithsonian Art - سميثسونيان للفنون",
    "National Gallery - المعرض الوطني",
    "Artsy - آرتسي",
    "DeviantArt - ديفيانت آرت",
    "Behance - بيهانس",
    "Dribbble - دريبل",
    "Pinterest - بينترست",
    "ArtStation - آرت ستيشن",
    "CGSociety - مجتمع الفنون",

    # ===== 5. منصات اللغات (20) =====
    "Duolingo - دوولينغو",
    "Babbel - بابل",
    "Rosetta Stone - روزيتا ستون",
    "Busuu - بوسوو",
    "Memrise - ممرايز",
    "Lingoda - لينغودا",
    "Italki - إيتالكي",
    "Preply - بريبلي",
    "Verbling - فيربلينغ",
    "HelloTalk - هيلو توك",
    "Tandem - تاندم",
    "Lingvist - لينغفيست",
    "Drops - دروبس",
    "Mondly - موندلي",
    "Pimsleur - بيمسلور",
    "Assimil - أسيميل",
    "Berlitz - بيرلتز",
    "EF Education - إي إف",
    "British Council - المجلس الثقافي البريطاني",
    "Alliance Française - الأليانس الفرنسية",

    # ===== 6. منصات التاريخ (20) =====
    "History.com - قناة التاريخ",
    "BBC History - بي بي سي التاريخ",
    "Smithsonian History - سميثسونيان للتاريخ",
    "National Archives - الأرشيف الوطني",
    "Internet History Sourcebook - كتاب التاريخ",
    "World History Encyclopedia - موسوعة تاريخ العالم",
    "Ancient History Encyclopedia - موسوعة التاريخ القديم",
    "Medieval History - التاريخ الوسيط",
    "Modern History - التاريخ الحديث",
    "JSTOR History - التاريخ",
    "Cambridge History - كامبريدج للتاريخ",
    "Oxford History - أكسفورد للتاريخ",
    "History Today - مجلة التاريخ",
    "Past & Present - الماضي والحاضر",
    "American Historical Review - المراجعة التاريخية",
    "European History - التاريخ الأوروبي",
    "Asian History - التاريخ الآسيوي",
    "African History - التاريخ الأفريقي",
    "Latin American History - تاريخ أمريكا اللاتينية",
    "Middle East History - تاريخ الشرق الأوسط",

    # ===== 7. منصات الجغرافيا (20) =====
    "National Geographic - ناشيونال جيوغرافيك",
    "Google Earth - جوجل إيرث",
    "ArcGIS - آرك جي آي إس",
    "USGS Geography - الجغرافيا الأمريكية",
    "Ordnance Survey - المسح الجغرافي البريطاني",
    "GeoScienceWorld - العلوم الجغرافية",
    "Geography Compass - مجلة الجغرافيا",
    "GIS Geography - الجغرافيا ونظم المعلومات",
    "OpenStreetMap - الخرائط المفتوحة",
    "Mapbox - ماب بوكس",
    "Cartography Journal - مجلة رسم الخرائط",
    "Geographical Journal - المجلة الجغرافية",
    "Royal Geographical Society - الجمعية الجغرافية الملكية",
    "American Geographical Society - الجمعية الجغرافية الأمريكية",
    "Canadian Geographic - الجغرافيا الكندية",
    "Australian Geographic - الجغرافيا الأسترالية",
    "Asia Geographic - الجغرافيا الآسيوية",
    "Africa Geographic - الجغرافيا الأفريقية",
    "Europe Geographic - الجغرافيا الأوروبية",
    "Polar Geography - الجغرافيا القطبية",

    # ===== 8. منصات الأدب (20) =====
    "Project Gutenberg - مشروع غوتنبرغ",
    "Internet Archive - الأرشيف الرقمي",
    "Google Books - كتب جوجل",
    "Open Library - المكتبة المفتوحة",
    "HathiTrust - هاثي تراست",
    "Europeana - يوروبيانا",
    "World Digital Library - المكتبة الرقمية العالمية",
    "Library of Congress - مكتبة الكونغرس",
    "British Library - المكتبة البريطانية",
    "Bibliothèque Nationale - المكتبة الوطنية الفرنسية",
    "Deutsche Nationalbibliothek - المكتبة الألمانية",
    "Poetry Foundation - مؤسسة الشعر",
    "Poets.org - شعراء",
    "Literary Hub - ليتيراري هب",
    "Goodreads - غود ريدز",
    "Shelfari - شيلفاري",
    "BookLikes - بوك لايكس",
    "LibraryThing - لايبراري ثينغ",
    "Bookish - بوكيش",
    "Readernaut - ريدر نوت",

    # ===== 9. منصات الموسيقى (20) =====
    "Spotify - سبوتيفاي",
    "Apple Music - أبل ميوزك",
    "YouTube Music - يوتيوب ميوزك",
    "Amazon Music - أمازون ميوزك",
    "Deezer - ديزر",
    "Tidal - تيدال",
    "SoundCloud - ساوند كلاود",
    "Bandcamp - باندكامب",
    "MusicBrainz - ميوزيك برينز",
    "Discogs - ديسكوجز",
    "Last.fm - لاست إف إم",
    "AllMusic - أول ميوزك",
    "Classical Archives - الأرشيف الكلاسيكي",
    "IMSLP - مكتبة الموسيقى الكلاسيكية",
    "8tracks - 8 تراكس",
    "Pandora - باندورا",
    "iHeartRadio - آي هارت راديو",
    "TuneIn - تيون إن",
    "Live365 - لايف 365",
    "Radio.com - راديو"

    # ===== 10. منصات الفلسفة (20) =====
    "Stanford Encyclopedia of Philosophy - موسوعة ستانفورد",
    "Internet Encyclopedia of Philosophy - موسوعة الإنترنت",
    "PhilPapers - فيل بيبرز",
    "Philosophy Compass - مجلة الفلسفة",
    "Philosophy Now - مجلة الفلسفة الآن",
    "The Philosopher's Magazine - مجلة الفيلسوف",
    "Philosophy Talk - حديث الفلسفة",
    "Philosophy Bites - لقيمات الفلسفة",
    "Partially Examined Life - الحياة المدروسة جزئيًا",
    "Philosophy Tube - أنبوب الفلسفة",
    "Wireless Philosophy - فلسفة لاسلكية",
    "Open Culture Philosophy - ثقافة مفتوحة",
    "Philosophy Pages - صفحات الفلسفة",
    "Philosophy Index - فهرس الفلسفة",
    "Philosophy Documentation Center - مركز التوثيق الفلسفي",
    "Routledge Encyclopedia - موسوعة روتليدج",
    "Oxford Philosophy - أكسفورد للفلسفة",
    "Cambridge Philosophy - كامبريدج للفلسفة",
    "Harvard Philosophy - هارفارد للفلسفة",
    "MIT Philosophy - إم آي تي للفلسفة"
]

def display_scientific_platforms_extra1():
    print("=" * 80)
    print(f"📚  المنصات العلمية الإضافية - الدفعة الأولى ({len(scientific_platforms_extra1)} منصة)  📚")
    print("=" * 80)
    for i, platform in enumerate(scientific_platforms_extra1, 1):
        print(f"    {i:3d}. {platform}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(scientific_platforms_extra1)}")
    print("=" * 80)

if __name__ == "__main__":
    display_scientific_platforms_extra1()
