#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# sector_health_full.py - أنظمة الصحة التفصيلية

health_systems_full = [
    # ===== 1. طب القلب (20) =====
    "CardiologyAI - نظام طب القلب",
    "CardiacSurgeryAI - جراحة القلب",
    "ECG_AI - تخطيط القلب",
    "EchocardiographyAI - تخطيط صدى القلب",
    "AngiographyAI - تصوير الأوعية",
    "PacemakerAI - منظم ضربات القلب",
    "CardiacCatheterizationAI - قسطرة القلب",
    "HeartFailureAI - فشل القلب",
    "ArrhythmiaAI - اضطراب النظم",
    "HypertensionAI - ارتفاع الضغط",
    "CoronaryAI - الشرايين التاجية",
    "ValveAI - صمامات القلب",
    "CardiomyopathyAI - اعتلال عضلة القلب",
    "PericarditisAI - التهاب التامور",
    "EndocarditisAI - التهاب الشغاف",
    "CongenitalHeartAI - عيوب القلب الخلقية",
    "CardiacRehabAI - تأهيل القلب",
    "PreventiveCardiologyAI - وقاية القلب",
    "PediatricCardiologyAI - قلب الأطفال",
    "GeriatricCardiologyAI - قلب المسنين",

    # ===== 2. طب الأعصاب (20) =====
    "NeurologyAI - طب الأعصاب",
    "NeurosurgeryAI - جراحة الأعصاب",
    "EEG_AI - تخطيط الدماغ",
    "MRI_BrainAI - رنين الدماغ",
    "StrokeAI - السكتة الدماغية",
    "EpilepsyAI - الصرع",
    "ParkinsonAI - باركنسون",
    "AlzheimerAI - الزهايمر",
    "MultipleSclerosisAI - التصلب المتعدد",
    "MigraineAI - الشقيقة",
    "NeuropathyAI - اعتلال الأعصاب",
    "MyastheniaAI - الوهن العضلي",
    "BrainTumorAI - أورام الدماغ",
    "SpinalCordAI - إصابات النخاع",
    "NeurorehabAI - تأهيل الأعصاب",
    "NeurogeneticsAI - وراثة الأعصاب",
    "NeuroimmunologyAI - مناعة الأعصاب",
    "NeuropharmacologyAI - أدوية الأعصاب",
    "PediatricNeurologyAI - أعصاب الأطفال",
    "NeuroCriticalCareAI - العناية الحرجة العصبية",

    # ===== 3. طب الأورام (20) =====
    "OncologyAI - طب الأورام",
    "MedicalOncologyAI - الأورام الطبية",
    "SurgicalOncologyAI - جراحة الأورام",
    "RadiationOncologyAI - الأورام الإشعاعية",
    "ChemotherapyAI - العلاج الكيميائي",
    "ImmunotherapyAI - العلاج المناعي",
    "TargetedTherapyAI - العلاج الموجه",
    "HormoneTherapyAI - العلاج الهرموني",
    "BreastCancerAI - سرطان الثدي",
    "LungCancerAI - سرطان الرئة",
    "ColonCancerAI - سرطان القولون",
    "ProstateCancerAI - سرطان البروستاتا",
    "LeukemiaAI - اللوكيميا",
    "LymphomaAI - الليمفوما",
    "MelanomaAI - الميلانوما",
    "BrainTumorAI - أورام الدماغ",
    "PediatricOncologyAI - أورام الأطفال",
    "CancerScreeningAI - فحص السرطان",
    "CancerPreventionAI - وقاية السرطان",
    "PalliativeCareAI - الرعاية التلطيفية",

    # ===== 4. طب الأطفال (20) =====
    "PediatricsAI - طب الأطفال",
    "NeonatologyAI - حديثي الولادة",
    "PediatricSurgeryAI - جراحة الأطفال",
    "PediatricCardiologyAI - قلب الأطفال",
    "PediatricNeurologyAI - أعصاب الأطفال",
    "PediatricOncologyAI - أورام الأطفال",
    "PediatricGastroenterologyAI - هضمية الأطفال",
    "PediatricPulmonologyAI - تنفسية الأطفال",
    "PediatricNephrologyAI - كلوية الأطفال",
    "PediatricEndocrinologyAI - غدد الأطفال",
    "PediatricInfectiousAI - عدوى الأطفال",
    "PediatricImmunologyAI - مناعة الأطفال",
    "PediatricAllergyAI - حساسية الأطفال",
    "PediatricRheumatologyAI - روماتيزم الأطفال",
    "PediatricHematologyAI - دم الأطفال",
    "PediatricDermatologyAI - جلدية الأطفال",
    "PediatricPsychiatryAI - نفسية الأطفال",
    "PediatricNutritionAI - تغذية الأطفال",
    "PediatricEmergencyAI - طوارئ الأطفال",
    "PediatricICU_AI - عناية الأطفال",

    # ===== 5. طب الجراحة (20) =====
    "GeneralSurgeryAI - الجراحة العامة",
    "LaparoscopicSurgeryAI - الجراحة التنظيرية",
    "RoboticSurgeryAI - الجراحة الروبوتية",
    "MinimallyInvasiveAI - الجراحة طفيفة التوغل",
    "TraumaSurgeryAI - جراحة الإصابات",
    "VascularSurgeryAI - جراحة الأوعية",
    "PlasticSurgeryAI - جراحة التجميل",
    "ReconstructiveSurgeryAI - الجراحة الترميمية",
    "OrthopedicSurgeryAI - جراحة العظام",
    "SpineSurgeryAI - جراحة العمود الفقري",
    "JointReplacementAI - استبدال المفاصل",
    "ArthroscopyAI - تنظير المفاصل",
    "ThoracicSurgeryAI - جراحة الصدر",
    "AbdominalSurgeryAI - جراحة البطن",
    "UrologicalSurgeryAI - جراحة المسالك",
    "GynecologicalSurgeryAI - جراحة النساء",
    "OphthalmicSurgeryAI - جراحة العيون",
    "ENT_SurgeryAI - جراحة الأذن والأنف",
    "NeurosurgeryAI - جراحة الأعصاب",
    "TransplantSurgeryAI - جراحة الزراعة",

    # ===== 6. طب الطوارئ (20) =====
    "EmergencyMedicineAI - طب الطوارئ",
    "TraumaCareAI - رعاية الإصابات",
    "CriticalCareAI - العناية الحرجة",
    "ICU_AI - العناية المركزة",
    "EmergencySurgeryAI - جراحة الطوارئ",
    "ResuscitationAI - الإنعاش",
    "PoisoningAI - التسمم",
    "BurnsAI - الحروق",
    "FracturesAI - الكسور",
    "DislocationsAI - الخلع",
    "WoundsAI - الجروح",
    "HemorrhageAI - النزيف",
    "ShockAI - الصدمة",
    "RespiratoryFailureAI - فشل تنفسي",
    "CardiacArrestAI - توقف القلب",
    "StrokeEmergencyAI - طوارئ السكتة",
    "AnaphylaxisAI - الحساسية المفرطة",
    "SepsisAI - الإنتان",
    "EmergencyImagingAI - تصوير الطوارئ",
    "EmergencyTriageAI - فرز الطوارئ",

    # ===== 7. طب التشخيص (20) =====
    "DiagnosticMedicineAI - الطب التشخيصي",
    "RadiologyAI - الأشعة",
    "XRay_AI - الأشعة السينية",
    "CT_ScanAI - الأشعة المقطعية",
    "MRI_AI - الرنين المغناطيسي",
    "UltrasoundAI - الموجات فوق الصوتية",
    "NuclearMedicineAI - الطب النووي",
    "PET_ScanAI - التصوير المقطعي البوزيتروني",
    "PathologyAI - علم الأمراض",
    "HistopathologyAI - أمراض الأنسجة",
    "CytologyAI - علم الخلايا",
    "MicrobiologyAI - الأحياء الدقيقة",
    "VirologyAI - الفيروسات",
    "BacteriologyAI - البكتيريا",
    "ParasitologyAI - الطفيليات",
    "MycologyAI - الفطريات",
    "ImmunologyAI - المناعة",
    "HematologyAI - أمراض الدم",
    "BiochemistryAI - الكيمياء الحيوية",
    "GeneticsDiagnosticsAI - تشخيص الوراثة",

    # ===== 8. طب الصيدلة (20) =====
    "PharmacyAI - الصيدلة",
    "PharmacologyAI - علم الأدوية",
    "PharmacokineticsAI - حركية الأدوية",
    "PharmacodynamicsAI - ديناميكية الأدوية",
    "PharmaceuticalCareAI - الرعاية الصيدلانية",
    "ClinicalPharmacyAI - الصيدلة السريرية",
    "HospitalPharmacyAI - صيدلة المستشفيات",
    "CommunityPharmacyAI - صيدلة المجتمع",
    "IndustrialPharmacyAI - الصيدلة الصناعية",
    "PharmacognosyAI - العقاقير",
    "PharmaceuticalChemistryAI - كيمياء الأدوية",
    "PharmaceuticalAnalysisAI - تحليل الأدوية",
    "PharmaceuticalTechnologyAI - تكنولوجيا الأدوية",
    "DrugDiscoveryAI - اكتشاف الأدوية",
    "DrugDevelopmentAI - تطوير الأدوية",
    "DrugSafetyAI - سلامة الأدوية",
    "DrugInteractionsAI - تداخلات الأدوية",
    "AdverseDrugReactionsAI - تفاعلات الأدوية الضارة",
    "PersonalizedMedicineAI - الطب الشخصي",
    "PharmacogenomicsAI - وراثة الأدوية",

    # ===== 9. طب الأسنان (20) =====
    "DentistryAI - طب الأسنان",
    "DentalSurgeryAI - جراحة الأسنان",
    "OrthodonticsAI - تقويم الأسنان",
    "EndodonticsAI - علاج الجذور",
    "PeriodonticsAI - أمراض اللثة",
    "ProsthodonticsAI - التعويضات السنية",
    "PediatricDentistryAI - أسنان الأطفال",
    "OralSurgeryAI - جراحة الفم",
    "OralMedicineAI - طب الفم",
    "OralPathologyAI - أمراض الفم",
    "OralRadiologyAI - أشعة الفم",
    "DentalImplantAI - زراعة الأسنان",
    "CosmeticDentistryAI - تجميل الأسنان",
    "RestorativeDentistryAI - ترميم الأسنان",
    "PreventiveDentistryAI - وقاية الأسنان",
    "DentalHygieneAI - صحة الأسنان",
    "DentalTechnologyAI - تقنية الأسنان",
    "DentalMaterialsAI - مواد الأسنان",
    "GeriatricDentistryAI - أسنان المسنين",
    "SpecialNeedsDentistryAI - أسنان ذوي الاحتياجات",

    # ===== 10. طب العيون (20) =====
    "OphthalmologyAI - طب العيون",
    "OphthalmicSurgeryAI - جراحة العيون",
    "CataractAI - الساد",
    "GlaucomaAI - الجلوكوما",
    "RetinaAI - الشبكية",
    "CorneaAI - القرنية",
    "RefractiveSurgeryAI - جراحة تصحيح النظر",
    "LASIK_AI - الليزك",
    "StrabismusAI - الحول",
    "PediatricOphthalmologyAI - عيون الأطفال",
    "NeuroOphthalmologyAI - عيون عصبية",
    "OculoplasticsAI - تجميل العيون",
    "UveitisAI - التهاب العنبية",
    "MacularDegenerationAI - التنكس البقعي",
    "DiabeticRetinopathyAI - اعتلال الشبكية السكري",
    "RetinalDetachmentAI - انفصال الشبكية",
    "OcularOncologyAI - أورام العين",
    "OcularTraumaAI - إصابات العين",
    "LowVisionAI - ضعف البصر",
    "ContactLensAI - العدسات اللاصقة"
]

def display_health_sector():
    print("=" * 80)
    print(f"🏥  قطاع الصحة التفصيلي ({len(health_systems_full)} نظام)  🏥")
    print("=" * 80)
    for i, system in enumerate(health_systems_full, 1):
        print(f"    {i:3d}. {system}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(health_systems_full)}")
    print("=" * 80)

if __name__ == "__main__":
    display_health_sector()
