#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# sector_agriculture_full.py - أنظمة الزراعة التفصيلية

agriculture_systems_full = [
    # ===== 1. الزراعة العامة (25) =====
    "AgricultureAI - الزراعة العامة",
    "CropProductionAI - إنتاج المحاصيل",
    "HorticultureAI - البستنة",
    "AgronomyAI - الهندسة الزراعية",
    "SoilScienceAI - علوم التربة",
    "PlantScienceAI - علوم النبات",
    "PlantBreedingAI - تربية النبات",
    "PlantGeneticsAI - وراثة النبات",
    "PlantPathologyAI - أمراض النبات",
    "PlantProtectionAI - وقاية النبات",
    "WeedScienceAI - علوم الأعشاب",
    "EntomologyAI - علم الحشرات",
    "NematologyAI - علم الديدان",
    "AgriculturalEconomicsAI - الاقتصاد الزراعي",
    "AgriculturalExtensionAI - الإرشاد الزراعي",
    "AgriculturalMarketingAI - التسويق الزراعي",
    "AgriculturalPolicyAI - السياسة الزراعية",
    "AgriculturalStatisticsAI - الإحصاء الزراعي",
    "AgriculturalResearchAI - البحوث الزراعية",
    "AgriculturalEducationAI - التعليم الزراعي",
    "FarmManagementAI - إدارة المزرعة",
    "AgriBusinessAI - الأعمال الزراعية",
    "AgriFinanceAI - التمويل الزراعي",
    "AgriInsuranceAI - التأمين الزراعي",
    "SustainableAgricultureAI - الزراعة المستدامة",

    # ===== 2. المحاصيل الحقلية (25) =====
    "FieldCropsAI - المحاصيل الحقلية",
    "WheatAI - القمح",
    "RiceAI - الأرز",
    "CornAI - الذرة",
    "BarleyAI - الشعير",
    "OatsAI - الشوفان",
    "SorghumAI - الذرة الرفيعة",
    "MilletAI - الدخن",
    "SoybeanAI - فول الصويا",
    "LentilAI - العدس",
    "ChickpeaAI - الحمص",
    "BeanAI - الفاصوليا",
    "PeaAI - البازلاء",
    "PeanutAI - الفول السوداني",
    "SunflowerAI - عباد الشمس",
    "CottonAI - القطن",
    "SugarcaneAI - قصب السكر",
    "SugarBeetAI - بنجر السكر",
    "PotatoAI - البطاطس",
    "SweetPotatoAI - البطاطا",
    "CassavaAI - الكاسافا",
    "YamAI - اليام",
    "TaroAI - القلقاس",
    "QuinoaAI - الكينوا",
    "BuckwheatAI - الحنطة السوداء",

    # ===== 3. الخضروات والفواكه (25) =====
    "VegetableAI - الخضروات",
    "TomatoAI - الطماطم",
    "CucumberAI - الخيار",
    "PepperAI - الفلفل",
    "EggplantAI - الباذنجان",
    "OnionAI - البصل",
    "GarlicAI - الثوم",
    "CarrotAI - الجزر",
    "LettuceAI - الخس",
    "SpinachAI - السبانخ",
    "CabbageAI - الملفوف",
    "CauliflowerAI - القرنبيط",
    "BroccoliAI - البروكلي",
    "FruitAI - الفواكه",
    "AppleAI - التفاح",
    "OrangeAI - البرتقال",
    "BananaAI - الموز",
    "GrapeAI - العنب",
    "MangoAI - المانجو",
    "StrawberryAI - الفراولة",
    "WatermelonAI - البطيخ",
    "MelonAI - الشمام",
    "DateAI - التمر",
    "OliveAI - الزيتون",
    "PomegranateAI - الرمان",

    # ===== 4. الزراعة المائية والعمودية (25) =====
    "HydroponicsAI - الزراعة المائية",
    "AquaponicsAI - الأكوابونيك",
    "AeroponicsAI - الزراعة الهوائية",
    "VerticalFarmingAI - الزراعة العمودية",
    "GreenhouseAI - البيوت المحمية",
    "IndoorFarmingAI - الزراعة الداخلية",
    "UrbanFarmingAI - الزراعة الحضرية",
    "RooftopFarmingAI - زراعة الأسطح",
    "ContainerFarmingAI - الزراعة بالحاويات",
    "VerticalHydroponicsAI - الزراعة المائية العمودية",
    "VerticalAeroponicsAI - الزراعة الهوائية العمودية",
    "SmartGreenhouseAI - البيوت المحمية الذكية",
    "AutomatedGreenhouseAI - البيوت المحمية الآلية",
    "LEDFarmingAI - الزراعة بالإضاءة LED",
    "ClimateControlledAI - الزراعة المتحكم بها مناخيًا",
    "SoillessFarmingAI - الزراعة بدون تربة",
    "NutrientFilmAI - تقنية الفيلم المغذي",
    "DeepWaterCultureAI - الزراعة بالمياه العميقة",
    "DripHydroponicsAI - الزراعة المائية بالتنقيط",
    "EbbFlowAI - تقنية المد والجزر",
    "WickSystemAI - نظام الفتيل",
    "FogponicsAI - الزراعة الضبابية",
    "AquacultureAI - الزراعة المائية السمكية",
    "IntegratedFarmingAI - الزراعة المتكاملة",
    "PrecisionVerticalAI - الزراعة العمودية الدقيقة",

    # ===== 5. الثروة الحيوانية (25) =====
    "LivestockAI - الثروة الحيوانية",
    "CattleAI - الأبقار",
    "SheepAI - الأغنام",
    "GoatAI - الماعز",
    "CamelAI - الإبل",
    "HorseAI - الخيول",
    "DonkeyAI - الحمير",
    "PoultryAI - الدواجن",
    "ChickenAI - الدجاج",
    "TurkeyAI - الديك الرومي",
    "DuckAI - البط",
    "GooseAI - الإوز",
    "QuailAI - السمان",
    "OstrichAI - النعام",
    "RabbitAI - الأرانب",
    "BeekeepingAI - تربية النحل",
    "FishFarmingAI - تربية الأسماك",
    "ShrimpFarmingAI - تربية الروبيان",
    "AnimalNutritionAI - تغذية الحيوان",
    "AnimalBreedingAI - تربية الحيوان",
    "AnimalHealthAI - صحة الحيوان",
    "VeterinaryAI - الطب البيطري",
    "AnimalWelfareAI - رفاهية الحيوان",
    "AnimalHousingAI - إسكان الحيوان",
    "AnimalProductionAI - إنتاج الحيوان",

    # ===== 6. الري وإدارة المياه (25) =====
    "IrrigationAI - الري",
    "DripIrrigationAI - الري بالتنقيط",
    "SprinklerAI - الري بالرش",
    "SurfaceIrrigationAI - الري السطحي",
    "SubsurfaceIrrigationAI - الري تحت السطحي",
    "SmartIrrigationAI - الري الذكي",
    "PrecisionIrrigationAI - الري الدقيق",
    "AutomatedIrrigationAI - الري الآلي",
    "WaterManagementAI - إدارة المياه",
    "WaterConservationAI - حفظ المياه",
    "WaterEfficiencyAI - كفاءة المياه",
    "WaterQualityAI - جودة المياه",
    "DrainageAI - الصرف الزراعي",
    "WatershedAI - مستجمعات المياه",
    "GroundwaterAI - المياه الجوفية",
    "RainwaterAI - مياه الأمطار",
    "RecycledWaterAI - المياه المعاد تدويرها",
    "DesalinationAI - تحلية المياه",
    "FloodControlAI - التحكم بالفيضانات",
    "DroughtManagementAI - إدارة الجفاف",
    "SoilMoistureAI - رطوبة التربة",
    "WaterSensorsAI - مستشعرات المياه",
    "PumpSystemsAI - أنظمة المضخات",
    "CanalSystemsAI - أنظمة القنوات",
    "WaterStorageAI - تخزين المياه",

    # ===== 7. الآفات والمبيدات (25) =====
    "PestManagementAI - إدارة الآفات",
    "PestControlAI - مكافحة الآفات",
    "BiologicalControlAI - المكافحة البيولوجية",
    "ChemicalControlAI - المكافحة الكيميائية",
    "IntegratedPestAI - المكافحة المتكاملة",
    "PesticideAI - المبيدات",
    "InsecticideAI - المبيدات الحشرية",
    "FungicideAI - المبيدات الفطرية",
    "HerbicideAI - مبيدات الأعشاب",
    "RodenticideAI - مبيدات القوارض",
    "NematicideAI - مبيدات الديدان",
    "OrganicPesticideAI - المبيدات العضوية",
    "BioPesticideAI - المبيدات الحيوية",
    "PestMonitoringAI - مراقبة الآفات",
    "PestForecastingAI - التنبؤ بالآفات",
    "PestDetectionAI - كشف الآفات",
    "PestIdentificationAI - تحديد الآفات",
    "PestResistanceAI - مقاومة الآفات",
    "PestPreventionAI - وقاية الآفات",
    "InsectMonitoringAI - مراقبة الحشرات",
    "WeedManagementAI - إدارة الأعشاب",
    "DiseaseManagementAI - إدارة الأمراض",
    "PathogenDetectionAI - كشف المسببات",
    "QuarantineAI - الحجر الزراعي",
    "FumigationAI - التبخير",

    # ===== 8. التكنولوجيا الزراعية (25) =====
    "AgriTechAI - التكنولوجيا الزراعية",
    "PrecisionAgricultureAI - الزراعة الدقيقة",
    "SmartFarmingAI - الزراعة الذكية",
    "DigitalFarmingAI - الزراعة الرقمية",
    "AgriRoboticsAI - الروبوتات الزراعية",
    "AgriDronesAI - الطائرات الزراعية",
    "AgriSensorsAI - المستشعرات الزراعية",
    "AgriIoT_AI - إنترنت الأشياء الزراعي",
    "AgriBigDataAI - البيانات الزراعية الضخمة",
    "AgriAI_AI - الذكاء الاصطناعي الزراعي",
    "AgriMachineLearningAI - التعلم الآلي الزراعي",
    "AgriComputerVisionAI - الرؤية الحاسوبية الزراعية",
    "AgriGPS_AI - التموضع الزراعي",
    "AgriGIS_AI - نظم المعلومات الجغرافية الزراعية",
    "AgriRemoteSensingAI - الاستشعار الزراعي عن بعد",
    "AgriSatelliteAI - الأقمار الزراعية",
    "AgriAutomationAI - الأتمتة الزراعية",
    "AgriBlockchainAI - بلوكشين زراعي",
    "AgriCloudAI - حوسبة زراعية سحابية",
    "AgriMobileAppsAI - تطبيقات زراعية",
    "AgriSoftwareAI - برمجيات زراعية",
    "AgriModelingAI - نمذجة زراعية",
    "AgriSimulationAI - محاكاة زراعية",
    "AgriForecastingAI - تنبؤ زراعي",
    "AgriInnovationAI - ابتكار زراعي"
]

def display_agriculture_sector():
    print("=" * 80)
    print(f"🌾  قطاع الزراعة التفصيلي ({len(agriculture_systems_full)} نظام)  🌾")
    print("=" * 80)
    for i, system in enumerate(agriculture_systems_full, 1):
        print(f"    {i:3d}. {system}")
    print("\n" + "=" * 80)
    print(f"✨  الإجمالي: {len(agriculture_systems_full)}")
    print("=" * 80)

if __name__ == "__main__":
    display_agriculture_sector()
